$schema: http://json-schema.org/draft-07/schema#
$id: urn:mef:lso:spec:legato:carrier-ethernet-performance-monitoring-configuration:v0.0.1:all
x-mef-target: ServicePayloadSpecificAttributes
description: Carrier Ethernet Performance Monitoring Configuration Schema.
title: 
    MEF LSO Legato - Carrier Ethernet Performance Monitoring Configuration
    # MEF Forum - Date: 20230622  Edit-level: 
    # File: carrierEthernet/faultAndPerformanceManagement/carrierEthernetPerformanceMonitoringConfiguration.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # © MEF Forum 2023. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
type: object
properties:
  description: >-
    Data type representing the Carrier Ethernet Layer 2 frame performance statistics configuration
    for receive and transmit.
  interface:
    type: string
  rxEthIINum:
    description: Number of frames encapsulated by using Ethernet II.
    type: boolean
  rxSnapNum:
    description: Number of frames encapsulated by using SNAP.
    type: boolean
  rxRawNum:
    description: Number of frames encapsulated by using RAW.
    type: boolean
  rxIsisNum:
    description: Number of frames encapsulated by using IS-IS.
    type: boolean
  rxLlcNum:
    description: Number of frames encapsulated by using LLC.
    type: boolean
  rxUnknownNum:
    description: Number of frames encapsulated by using unknown methods.
    type: boolean
  rxForwardNum:
    description: Number of frames forwarded at Layer 2.
    type: boolean
  rxArp:
    description: Number of ARP frames.
    type: boolean
  rxMpls:
    description: Number of MPLS frames.
    type: boolean
  rxIsis:
    description: Number of IS-IS frames.
    type: boolean
  rxIsis2:
    description: Number of large 802.3/802.2 frames encapsulated by using IS-IS.
    type: boolean
  rxIpv4:
    description: Number of IPv4 frames.
    type: boolean
  rxIpv6:
    description: Number of IPv6 frames.
    type: boolean
  txL3OutNum:
    description: Number of frames sent out of Layer 3 Ethernet interfaces.
    type: boolean
  txVlanOutNum:
    description: Number of frames sent out of VLAN interfaces.
    type: boolean
  txFastOutNum:
    description: Number of frames fast forwarded.
    type: boolean
  rxL2OutNum:
    description: Number of frames sent out of Layer 2 Ethernet interfaces.
    type: boolean
  txMbufRelayNum:
    description: Number of frames transparently sent.
    type: boolean
  utilizationIn:
    type: boolean
  utilizationOut:
    type: boolean
  peakUtilizationIn:
    type: boolean
  peakUtilizationOut:
    type: boolean