@startuml

hide footbox

participant Buyer as "Buyer/Client"
participant Seller as "Seller/Server"

group loop
    Buyer -> Seller :   GET {{baseUrl}}/serviceOrder/{{id}}
    return 200 ProductOrder in current state
end


Buyer -> Seller : DELETE {{baseUrl}}/serviceOrder/{{id}}
Seller -->  Buyer : 204 confirmation

@enduml