@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(Ipv4Address) {
    String/ipv4: format ipv4
}


datatype(Ipv4Prefix) {
    ipv4Address: Ipv4Address
    prefixLength: Integer
}

Ipv4Prefix *--> Ipv4Address: ipv4Address

datatype(Ipv4PrimarySubnet) {
    subscriberIpAddress: Ipv4Address [0..1] currently not supported
}

Ipv4PrimarySubnet *--> [0..1] Ipv4Address

datatype(Ipv4Subnet) {
    ipv4Prefix: Ipv4Prefix
    serviceProviderIpv4Addresses: Ipv4Address [1..*]
    reservedPrefixes: Ipv4Prefix [0..*]
}

Ipv4Subnet *--> Ipv4Prefix: ipv4Prefix
Ipv4Subnet *--> Ipv4Prefix: reservedPrefixes
Ipv4Subnet *--> "1..*" Ipv4Address

Ipv4Subnet <|-- Ipv4PrimarySubnet


@enduml