@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(PerformanceTimeIntervals) {
    evalInterval: Integer [1]
    arrivalInterval: Integer [1]
    irDuration:  Integer [1]
}

@enduml