@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>
!define enum(x) class x << (E,#ADD1B2) Enum>>

datatype(Policy) {
    polName: String [1]
    polCl: PolicyCriteria [1..*]
}

Policy *--> "1..*" PolicyCriteria: polCl


datatype(PolicyCriteria) {
    encryptionType: EncryptionType[1]
    internetBreakout: InternetBreakout [1]
    internetBreakoutDirection: InternetBreakoutDirection [1]
    publicPrivate: PublicPrivate [1]
    backUp: Backup [1]
    virtualTopology: VirtualTopology [1]
    allowedDestinationZones: Zone [0..*]
    billingMethod: BillingMethod [1]
    businessImportance: ApplicationFlowBusinessImportanceLevelIdentifier [1]
    performance: PerformancePolicyCriterion [1]
    bandwidth: BandwidthPolicyCriterion [1]
    afSecurityIngress: SecurityPolicy [1]
    blockSource: BlockSource[1]
    afSecurityEgress: SecurityPolicy [1]
    serviceProviderDefinedPolicyCriterion: ServiceProviderDefinedPolicyCriterion [1]

}

PolicyCriteria *-->"1" VirtualTopology: virtualTopology
PolicyCriteria *-->"0..*" Zone: allowedDestinationZones
PolicyCriteria *-->"1" ApplicationFlowBusinessImportanceLevelIdentifier: businessImportance
PolicyCriteria *-->"1" PerformancePolicyCriterion: performance
PolicyCriteria *-->"1" BandwidthPolicyCriterion: bandwidth
PolicyCriteria *-->"1" SecurityPolicy: afSecurityIngress
PolicyCriteria *-->"1" SecurityPolicy: afSecurityEgress
PolicyCriteria *-->"1" ServiceProviderDefinedPolicyCriterion: serviceProviderDefinedPolicyCriterion

enum EncryptionType {
    - REQUIRED_ALWAYS 
    - REQUIRED_PUBLIC_ONLY 
    - OPTIONAL
    }
enum InternetBreakout {
    - ENABLED 
    - DISABLED 
    }
enum InternetBreakoutDirection {
    - INGRESS 
    - EGRESS 
    }
enum PublicPrivate {
    - PRIVATE_ONLY 
    - EITHER 
    }
enum Backup {
    - ENABLED 
    - DISABLED 
}

enum BillingMethod {
    - FLAT_RATE_ONLY
    - USAGE_BASED_ONLY
    - EITHER
}

enum BlockSource {
    - UNI
    - INTERNET
    - UNI_INTERNET
    - EMPTY_LIST
    }

datatype(VirtualTopology) {
    <<skipped>>
}

datatype(Zone) {
    <<skipped>>
}

datatype(ApplicationFlowBusinessImportanceLevelIdentifier) {
    <<skipped>>
}

datatype(PerformancePolicyCriterion) {
    <<skipped>>
}

datatype(BandwidthPolicyCriterion) {
    <<skipped>>
}

datatype(SecurityPolicy) {
    <<skipped>>
}

datatype(ServiceProviderDefinedPolicyCriterion) {
    <<skipped>>
}

@enduml
