@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(SecurityFunctionPolicy) {
    securityPolicyIdentifier: SecurityPolicyIdentifier[1]
    securityFunctionPolicyIdentifier: SecurityFunctionPolicyIdentifier[1]
    middleBoxSecurityFunctionPolicy: MiddleboxSecurityFunctionPolicy[0..1]
    ipPortProtocolFilteringSecurityFunctionPolicy: IpPortProtocolFilteringSecurityFunctionPolicy[0..1]
    domainNameFilteringSecurityFunctionPolicy: DomainNameFilteringSecurityFunctionPolicy[0..1]
    urlFilteringSecurityFunctionPolicy: UrlFilteringSecurityFunctionPolicy[0..1]
    malwareDetectionRemovalSecurityFunctionPolicy: MalwareDetectionRemovalSecurityFunctionPolicy[0..1]
    dataLossPreventionSecurityFunctionPolicy: DataLossPreventionSecurityFunctionPolicy[0..1]
    dnsProtocolFilteringSecurityFunctionPolicy: DnsProtocolFilteringSecurityFunctionPolicy[0..1]
    protectiveDnsSecurityFunctionPolicy: ProtectiveDnsSecurityFunctionPolicy[0..1]
}

SecurityFunctionPolicy *--> "0..1" MiddleboxSecurityFunctionPolicy: middleBoxSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" IpPortProtocolFilteringSecurityFunctionPolicy: ipPortProtocolFilteringSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" DomainNameFilteringSecurityFunctionPolicy: domainNameFilteringSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" UrlFilteringSecurityFunctionPolicy: urlFilteringSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" MalwareDetectionRemovalSecurityFunctionPolicy: malwareDetectionRemovalSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" DataLossPreventionSecurityFunctionPolicy: dataLossPreventionSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" DnsProtocolFilteringSecurityFunctionPolicy: dnsProtocolFilteringSecurityFunctionPolicy
SecurityFunctionPolicy *--> "0..1" ProtectiveDnsSecurityFunctionPolicy: protectiveDnsSecurityFunctionPolicy

datatype(MiddleboxSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(IpPortProtocolFilteringSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(DomainNameFilteringSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(UrlFilteringSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(MalwareDetectionRemovalSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(DataLossPreventionSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(DnsProtocolFilteringSecurityFunctionPolicy) {
    <<skipped>>
}

datatype(ProtectiveDnsSecurityFunctionPolicy) {
    <<skipped>>
}

@enduml