@startuml Service Order

hide footbox

box "BA" #LightBlue
  participant "Client" as ba
end box

box "SOF" #LightGrey
  participant "Server" as sof
end box

autonumber

note right ba: Legato: Buyer requests Service Order

ba -> sof : Subscribe to Service Order Notifications
sof -> ba: Acknowledge Client Request
ba -> ba: Instantiate ServiceOrderCreate (Envelope)
ba -> ba: Set ServiceOrderCreate attributes
ba -> ba: Create ServiceOrderItem (Envelope)
ba -> ba: Create Payload Component (SD-WAN UNI)
ba -> ba: Instantiate a MEFServiceConfiguration to use for SD-WAN UNI
ba -> ba: Create a Service Order Item Relationship
ba -> ba: Associate SD-WAN UNI (Payload) to Order Item (Envelope)
ba -> ba: Add ServiceOrderItem to ServiceOrder

ba -> sof : Send Add Service Order request
sof -> ba: Acknowledge receipt of Add Service Order

@enduml
