@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
!define datatype(x) class x << (D,#FF7700) DataType>>


datatype(Static) {
    staticIpEntry: StaticIpEntry [0..*]
}

datatype(StaticIpEntry) {
    staticPrefix: Ipv4OrIpv6Prefix [0..1]
    administrativeDistance: Integer [0..1]
    forwardingInformation: ForwardingInformation [0..1]
}

Static "1" *--> "0..*" StaticIpEntry

datatype(Ipv4OrIpv6Prefix) {
    <<skipped>>
}

StaticIpEntry "1" *--> "0..1" Ipv4OrIpv6Prefix

datatype(ForwardingInformation) {
    nextHopIpAddress: Ipv4OrIpv6Address [0..1]
}

datatype(Ipv4OrIpv6Address) {

}

StaticIpEntry "1" *--> "0..1" ForwardingInformation
ForwardingInformation "1" *--> "Ipv4OrIpv6Address"

@enduml