@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(SwVcEndPoint) {
    swVcEndPointdentifier: SwVcEndPointIdentifier [1]
    policyMap: PolicyMap [*]
    networkAddressTranslation: NetworkAddressTranslation [0..1]
}

SwVcEndPoint "1" *--> "*" PolicyMap
SwVcEndPoint "1" *--> "0..1" NetworkAddressTranslation

datatype(PolicyMap) {

    zone: Zone [1]
    applicationFlowSpecification: ApplicationFlowSpecification [0..1]
    applicationFlowSpecificationGroup: ApplicationFlowSpecificationGroup [0..1]
    ingressPolicy: IngressPolicy [0..1]
    egressPolicy: EgressPolicy [0..1]
    
}

datatype(NetworkAddressTranslation) {

    ipversion: IpVersion [1]
    publicPrefix: Ipv4Prefix [1..*]
    exceptions: Ipv4Prefix [0..*]
    
}

enum IpVersion {
    - IPV4
    - IPV6
    - BOTH 
}

@enduml