@startuml zone.puml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
    !define datatype(x) class x << (D,#FF7700) DataType>>
    datatype(VirtualTopology) {
        vtName: String
        vtType: VtType
        vtEp: VirtualTopologyEndPoint
        }

    enum VtType {
        - MPT_TO_MPT 
        - ROOTED_MPT 
    }

    datatype(VirtualTopologyEndPoint) {
        multipointToMultipoint: String[2..*]
        rootedMultipoint: VtRootedMultipoint
        }

    datatype(VtRootedMultipoint) {
        rootList: String[1..*]
        leafList: String[1..*]
        }    

    VirtualTopology "1" *--> "1" VtType
    VirtualTopology "1" *--> "1" VirtualTopologyEndPoint

    VirtualTopologyEndPoint "1" *--> "1" VtRootedMultipoint
    
@enduml