@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class L1ServiceLevelSpecification {
    startTime: TimeAndDate[1]
    duration: TimeInterval[1]
}

class Sls1wDelayPerformanceMetric {
    percentile: PositiveInteger[1]
    delayObjective: TimeInterval[1]
    orderedPair: Identifier45[1]
 }

class Sls1wErroredSecondPerformanceMetric {
    erroredSecondObjective: PositiveInteger[1]
    orderedPair: Identifier45[1]
}

class Sls1wSeverelyErroredSecondPerformanceMetric {
    severelyErrorSecondObjective: PositiveInteger[1]
    orderedPair: Identifier45[1]
}

class Sls1wUnavailableSecondPerformanceMetric {
    unavailableSecondObjective: PositiveInteger[1]
    orderedPair: Identifier45
}

class Sls1wAvailabilityPerformanceMetric {
    availabilityObjective: PositiveInteger[1]
    orderedPair: Identifier45
}


L1ServiceLevelSpecification "1" *-->"0..*" Sls1wDelayPerformanceMetric
L1ServiceLevelSpecification "1" *-->"0..2" Sls1wErroredSecondPerformanceMetric
L1ServiceLevelSpecification "1" *-->"0..2" Sls1wSeverelyErroredSecondPerformanceMetric
L1ServiceLevelSpecification "1" *-->"0..2" Sls1wUnavailableSecondPerformanceMetric
L1ServiceLevelSpecification "1" *-->"0..2" Sls1wAvailabilityPerformanceMetric

@enduml