@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
set namespaceSeparator none

class PerformanceJob{

    id: string 
    href: string 
    jobType: JobType
    reportingPeriod: ReportingPeriod
    scheduleDefinition: ScheduleDefinition
}

class ServicePayloadSpecificAttributes {
    @type*: string <<discriminator>>
}


PerformanceJob *--> ServicePayloadSpecificAttributes: servicePayloadSpecificAttributes

enum Protocol {
    ARP 
    IPV4 
    IPV6
    }

class IpPerformanceMonitoringConfiguration {
    protocol: Protocol[1]
    packetsIn: boolean[1] 
    charsIn: boolean[1]
    packetsOut: boolean[1]
    charsOut: boolean[1]
    utilizationIn: boolean[1]
    utilizationOut: boolean[1]
    peakUtilizationIn: boolean[1]
    peakUtilizationOut: boolean[1]

}
ServicePayloadSpecificAttributes <|-- IpPerformanceMonitoringConfiguration


@enduml