@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
set namespaceSeparator none

!define datatype(x) class x << (D,#FF7700) DataType>>

class IpPerformanceMonitoringConfiguration {

    protocol: Protocol[1]
    packetsIn: boolean[1] 
    charsIn: boolean[1]
    packetsOut: boolean[1]
    charsOut: boolean[1]
    utilizationIn: boolean[1]
    utilizationOut: boolean[1]
    peakUtilizationIn: boolean[1]
    peakUtilizationOut: boolean[1]
}

class IpPerformanceMonitoringResult {
    protocol: Protocol[1]
    packetsIn: integer[1]
    charsIn: integer[1]
    packetsOut: integer[1]
    charsOut: integer[1]
    utilizationIn: Percentage[1]
    utilizationOut: Percentage[1]
    peakUntilizationIn: Percentage[1]
    peakUtilizationOut: Percentage[1]
}
enum Protocol {
    ARP 
    IPV4 
    IPV6
    }

datatype(Percentage) {
    type: number: minimum=0,maximum=100
}

@enduml