@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(PerformanceReport) {
    granularity: Enum <Granularity>
    lastModifiedDate: date-time
    servicePayloadSpecificAttributes: Any
}

PerformanceReport *-->"*" ReportContentRow : reportContent
PerformanceReport *--> "1" Period : reportingPeriod
ReportContentRow *--> "*" Period: measurementPeriod


datatype(ReportContentRow) {
    measurementPeriod: Period [1]
    measurementPoints: GroupedMultipleStatistics [0..*]
}

ReportContentRow *--> GroupedMultipleStatistics: measurementPoints

datatype(Period) {

    start: DateTime [1]
    end: DateTime [1]
}

datatype(GroupedMultipleStatistics) {
    key: Key [1]
    statistics: Statistics [1..*]
}

GroupedMultipleStatistics *--> Key: key
GroupedMultipleStatistics *--> Statistics: statistics

datatype(Statistics) {
    vsatStatus: boolean[1]
}

datatype(Key) {
    partnerId: String [1]
    siteId: String [1]
    terminalId: String [1]
    platformType: String [1]
}

datatype(ForwardThroughput) {
    characteristics: Characteristics [1]
}

Statistics *--> ForwardThroughput: fwdThroughput

@enduml