@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
set namespaceSeparator none

class PerformanceReport{

    id: string 
    href: string 
    <<...attributes are skipped...>>
}

class ReportContent {

}

enum Protocol {
    ARP 
    IPV4 
    IPV6
    }
    
PerformanceReport *-->"0..1" ReportContent: reportContent

class ResultPayload {
    @type*: string <<discriminator>>
}

class urn:mef:lso:spec:service:ip-performance-monitoring-results:v0.0.1:all <<ResultPayload>> {
    protocol: Protocol[1]
    charsIn: integer [1]
    packetsIn: integer[1]
    packetsOut: integer[1]
    charsOut: integer[1]
    utilizationIn: Percentage[1]
    utilizationOut: Percentage[1]
    peakUtilizationIn: Percentage[1]
    peakUtilizationOut: Percentage[1]
}
ReportContent *-->"*" ResultPayload: measurementDataPoints
ResultPayload <|-- "urn:mef:lso:spec:service:ip-performance-monitoring-results:v0.0.1:all"


@enduml