@startuml

title Legato Service Inventory API Schemas Diagram

entity Addressable { 
    id: String
    href: URI
    name: String
}

entity Characteristic { 
    * name: String
    valueType: String
    value: OasAnyTypeNotMapped
}

entity Error { 
    * code: Integer
    * reason: String
    message: List<String>
    status: List<String>
    referenceError: List<String>
}

entity EventSubscription { 
    * id: String
}

entity EventSubscriptionInput { 
    * query: String
    * callback: String
}

entity Extensible { 
    * @type: String
    @baseType: String
    @schemaLocation: URI
}

entity MefServiceConfiguration { 
}

entity Note { 
    author: String
    date: Date
    system: String
    text: String
}

entity Place { 
    role: String
}

entity Referenceable { 
    * @referredType: String
}

entity RelatedPartyRef { 
    role: String
}

entity ResourceRef { 
    @type: String
}

entity Service { 
    endDate: Date
    hasStarted: Boolean
    isServiceEnabled: Boolean
    isStateful: Boolean
    serviceDate: String
    serviceOrder: List<ServiceOrderRef>
    startDate: Date
    startMode: String
}

entity ServiceCreate { 
    category: String
    description: String
    mefServiceConfiguration: MefServiceConfiguration
    note: List<Note>
    place: List<Place>
    relatedParty: List<RelatedPartyRef>
    serviceCharacteristic: List<Characteristic>
    serviceRelationship: List<ServiceRelationship>
    serviceSpecification: ServiceSpecificationRef
    serviceType: String
    state: ServiceStateType
    supportingResource: List<ResourceRef>
    supportingService: List<ServiceRef>
}

entity ServiceOrderRef { 
    @type: String
}

entity ServiceRef { 
    @type: String
}

entity ServiceRelationship { 
    * relationshipType: ServiceRelationshipType
    * service: ServiceRef
}

entity ServiceRelationshipType { 
}

entity ServiceSpecificationRef { 
    version: String
    targetServiceSchema: TargetServiceSchema
}

entity ServiceStateType { 
}

entity TargetServiceSchema { 
}

Extensible <|--- Addressable
Extensible <|--- Characteristic
EventSubscriptionInput <|--- EventSubscription
Extensible <|--- MefServiceConfiguration
Extensible <|--- Note
Addressable <|--- Place
Addressable <|--- Referenceable
Referenceable <|--- RelatedPartyRef
Referenceable <|--- ResourceRef
ServiceCreate <|--- Service
Extensible <|--- ServiceCreate
Referenceable <|--- ServiceOrderRef
Referenceable <|--- ServiceRef
Referenceable <|--- ServiceSpecificationRef
Extensible <|--- TargetServiceSchema

ServiceSpecificationRef -- TargetServiceSchema : targetServiceSchema
Service -- "0..*" ServiceOrderRef : serviceOrder
ServiceCreate -- MefServiceConfiguration : mefServiceConfiguration
ServiceCreate -- "0..*" Note : note
ServiceCreate -- "0..*" Place : place
ServiceCreate -- "0..*" RelatedPartyRef : relatedParty
ServiceCreate -- "0..*" Characteristic : serviceCharacteristic
ServiceCreate -- "0..*" ServiceRelationship : serviceRelationship
ServiceCreate -- ServiceSpecificationRef : serviceSpecification
ServiceCreate -- "0..*" ResourceRef : supportingResource
ServiceCreate -- "0..*" ServiceRef : supportingService
ServiceRelationship -- ServiceRef : service

@enduml