openapi: 3.0.3
info:
  title: Legato Service Catalog Notification API
  version: 4.0.0-RC
  description: >+
    The Service Catalog Notification API provides a standardized mechanism for 
    receiving Service Catalog notifications. The Service Orchestration Function 
    (SOF) posts the Notification events to the Business Application (BUS) 
    listeners that are registered using the Service Catalog Hub API.  

    - MEF Developer Guide Reference : MEF_W99 v1.0

    - TMF API Reference : TMF 633 v18.5.1

    Copyright © MEF 2020. All Rights Reserved

  
    This file includes content based on the TM Forum Service Catalog Management API
    (TMF633 v3.0.0) available at
    https://github.com/tmforum-apis/TMF633_ServiceCatalog, which is licensed
    by the TM Forum under the Apache License version 2.0. Such content has been
    modified by the MEF Forum and its contributors.
tags:
  - name: serviceSpecificationNotification
    description: |-
      Mechanism for SOF to publish *ServiceSpecification* notifications to BUS

servers:
  - url: https://{server}:{port}{basePath}
    variables:
      server:
        default: 'mef.net' 
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        default: /mefApi/legato/serviceCatalog/v4
  
paths:

  /listener/serviceSpecificationCreateNotification:
    post:
      tags:
        - serviceSpecificationNotification
      operationId: serviceSpecificationCreateNotification
      summary: Publish ServiceSpecification Create Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of 
        ServiceSpecification creation event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecificationCreateNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'

  /listener/serviceSpecificationDeleteNotification:
    post:
      tags:
        - serviceSpecificationNotification
      operationId: serviceSpecificationDeleteNotification
      summary: Publish ServiceSpecification Deletion Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of 
        ServiceSpecification deletion event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecificationDeleteNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'
  
  /listener/serviceSpecificationChangeNotification:
    post:
      tags:
        - serviceSpecificationNotification
      operationId: serviceSpecificationChangeNotification
      summary: Publish ServiceSpecification StateChange Notification
      description: |-
        Mechanism for SOF to notify registred BUS listeners of 
        ServiceSpecification state change event
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: 'serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecificationChangeNotification'
      responses:
        '204':
          description: Notification-Success
        '400':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/NotFound'
        '405':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed'
        '408':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout'
        '422':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/InternalServerError'
        '503':
          $ref: '../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable'
