@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetEvcEndPoint {
    identifier: String[1]
    role: String[]
    map: EvcEndPointMap[1]
    ingressCosMap: 
    colorMap: 
    egressMap: 
    ingressBwp: 
    cosIngressBwp: 
    egressBwp: 
    cosNameEgressBwp: 
    sourceMacAddressLimit:
    subscriberMegMip: 
}

class EvcEndPointMap {
    
}

MefServiceConfiguration <|-- CarrierEthernetEvcEndPoint
CarrierEthernetEvcEndPoint "1" *--> "1" EvcEndPointMap
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml