@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetSubscriberUni {
    identifier: String[1]
    instantiation: Instantiation[1]
    virtualFrameMap: VirtualFrameMap[0..1]
    listOfPhyLinks: SubscriberUniPhysicalLinks[0..*]
    linkAggregation: LinkAggregation[1]
    aggregationLinkMap: ConversationIdToAggegationLinkMap[*]
    serviceFrameFormat: EthernetFrameFormat[1]
    maxmimumServiceFrameSize: PositiveInteger[1]
    maximumNumberOfEvcEndPoints: PositiveInteger[1]
    maximumNumberOfCtagVlanIdsPerEvcEndPoint: PositiveInteger[1]
    tokenShare: EnabledDisabled[1]
    envelopes: Envelope[*]
    linkOam: EnabledDisabled[1]
    meg: EnabledDisabled[1]
    lagLinkMeg: EnabledDisabled[1]
    l2cpAddressSet: L2cpAddressSet[1]
    l2cpPeering: L2cpPeering[*]
}

enum Instantiation {
    PHYSICAL
    VIRTUAL
}

MefServiceConfiguration <|-- CarrierEthernetSubscriberUni
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml