@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class CarrierEthernetEvc {
    "...attributes are not shown"
}

class CarrierEthernetEvcEndPoint {
    "...attributes are not shown"
}

class CarrierEthernetSubscriberUni {
    "...attributes are not shown"
}

class CarrierEthernetOvc {
    "...attributes are not shown"
}

class CarrierEthernetOvcEndPoint {
    "...attributes are not shown"
}

class CarrierEthernetOperatorUni {
    "...attributes are not shown"
}

class CarrierEthernetEnniService {
    "...attributes are not shown"
}

class CarrierEthernetEnni {
    "...attributes are not shown"
}

class CarrierEthernetVuni {
    "...attributes are not shown"
}

CarrierEthernetEvc "1" *-->"2..*" CarrierEthernetEvcEndPoint
CarrierEthernetSubscriberUni "1" o-->"*" CarrierEthernetEvcEndPoint
CarrierEthernetOvc "1" *-->"*" CarrierEthernetOvcEndPoint
CarrierEthernetOperatorUni "0..1" o-->"*" CarrierEthernetOvcEndPoint
CarrierEthernetEnni "0..1" o-->"*" CarrierEthernetOvcEndPoint
CarrierEthernetVuni "0..1" o-->"*" CarrierEthernetOvcEndPoint
CarrierEthernetEnni "1" *-->"1..*" CarrierEthernetEnniService

@enduml