@startuml cancelTestJobModel

class CancelTestJob {

    cancellationDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}
CancelTestJob_Common <|-- CancelTestJob



class CancelTestJob_Common {

    cancellationReason: string
}

CancelTestJob_Common *-->"1" TestJobRef : testJob


enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml