@startuml cancelTestJobStates

' skinparam Linetype polyline
' skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

'''decisions'''
state request_validated <<choice>> 
 note left of request_validated : Request validation passed?

''' diagram'''
[*] -d-> acknowledged

acknowledged -d-> request_validated

request_validated -d-> accepted: Yes

request_validated -r-> rejected: No

rejected -d-> [*]

accepted -d-> [*]


@enduml