@startuml cancelTestJobModel

class CancelTestJob {

    cancellationDeniedReason: string
    creationDate: date-time
    href: string
    id*: string
    state*: TestJobProcessStateType
}
CancelTestJob_Common <|-- CancelTestJob



class CancelTestJob_Common {

    cancellationReason: string
}

CancelTestJob_Common *-->"1" TestJobRef : testJob

class CancelTestJob_Find {
    creationDate: date-time
    id*: string
    state*: TestJobProcessStateType
}
CancelTestJob_Find *-->"1" TestJobRef : testJob


class CancelTestJob_Create {

}
CancelTestJob_Common <|-- CancelTestJob_Create

enum TestJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
    rejected
}

@enduml