@startuml extensionPattern
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecificTestProfileConfiguration>> FireBrick
    ClassBorderColor<<ServiceSpecificTestJobConfiguration>> FireBrick
    ClassBorderColor<<ServiceSpecificTestResultConfiguration>> FireBrick
}
set namespaceSeparator none

class TestProfile {

    id: string
    href: string
    <<... attributes are skipped ...>>
}


class ServiceSpecificTestProfileConfiguration {
    @type*: string <<discriminator>>
}


TestProfile *-->"0..1" ServiceSpecificTestProfileConfiguration : serviceSpecificTestProfileConfiguration

class urn:mef:lso:spec:legato:ip-ping-test-profile:v0.0.1:all <<serviceSpecificTestProfileConfiguration>> {

    <<... attributes are skipped ...>>
}
ServiceSpecificTestProfileConfiguration <|-- "urn:mef:lso:spec:legato:ip-ping-test-profile:v0.0.1:all"



class TestJob {

    id: string 
    href: string 
    <<... attributes are skipped ...>>
}

class ServiceSpecificTestJobConfiguration {
    @type*: string <<discriminator>>
}

TestJob *-->"0..1" ServiceSpecificTestJobConfiguration : serviceSpecificTestJobConfiguration

class urn:mef:lso:spec:legato:ping-configuration:v0.0.1:all <<serviceSpecificTestJobConfiguration>> {

    <<... attributes are skipped ...>>
}
ServiceSpecificTestJobConfiguration <|-- "urn:mef:lso:spec:legato:ping-configuration:v0.0.1:all"



class TestResult {

    id: string 
    href: string 
    <<... attributes are skipped ...>>
}

class ServiceSpecificTestResultConfiguration {
    @type*: string <<discriminator>>
}

TestResult *-->"0..1" ServiceSpecificTestResultConfiguration : serviceSpecificTestResultConfiguration

class urn:mef:lso:spec:legato:ping-report:v0.0.1:all <<serviceSpecificTestResultConfiguration>> {

    <<... attributes are skipped ...>>
}
ServiceSpecificTestResultConfiguration <|-- "urn:mef:lso:spec:legato:ping-report:v0.0.1:all"
@enduml