@startuml modifyTestJobModel


class ModifyTestJob {

    modificationDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}
ModifyTestJob_Common <|-- ModifyTestJob



class ModifyTestJob_Common {

    modificationReason: string
    name: string
    description: string
    startDateTime: date-time
    endDateTime: date-time
}

ModifyTestJob_Common *-->"1" TestJobRef : testJob
ModifyTestJob_Common *--> TestProfileRefOrValue : testProfile
ModifyTestJob_Common *--> ServiceRef : relatedServiceFrom
ModifyTestJob_Common *--> ServiceRef : relatedServiceTo
ModifyTestJob_Common *--> ServiceSpecificTestJobConfiguraton : serviceSpecificTestJobConfiguraton


enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml