@startuml resumeTestJobModel

class ResumeTestJob {

    resumptionDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}
ResumeTestJob_Common <|-- ResumeTestJob



class ResumeTestJob_Common {

    resumptionReason: string
}

ResumeTestJob_Common *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml