@startuml serviceFunctionTestNotificationModel

class Event {

    eventId*: string
    eventTime*: date-time
}



class TestJobEvent {

    eventType*: TestJobEventType
}
Event <|-- TestJobEvent

TestJobEvent *-->"1" TestJobEventPayload : event


class TestJobEventPayload {

    href: string
    id*: string
    ' state: string
}



class TestJobProcessEvent {

    eventType*: TestJobProcessEventType
}
Event <|-- TestJobProcessEvent

TestJobProcessEvent *-->"1" TestJobProcessEventPayload : event


class TestJobProcessEventPayload {

    href: string
    id*: string
}



class TestProfileEvent {

    eventType*: TestProfileEventType
}
Event <|-- TestProfileEvent

TestProfileEvent *-->"1" TestProfileEventPayload : event


class TestProfileEventPayload {

    href: string
    id*: string
}


enum TestJobProcessEventType {

    cancelTestJobStateChangeEvent
    modifyTestJobStateChangeEvent
    resumeTestJobStateChangeEvent
    suspendTestJobStateChangeEvent
}

enum TestProfileEventType {

    testProfileCreateEvent
    testProfileStateChangeEvent
    testProfileDeleteEvent
    testProfileAttributeValueChangeEvent
}

enum TestJobEventType {

    testJobCreateEvent
    testJobStateChangeEvent
    testJobAttributeValueChangeEvent
}

@enduml