@startuml sftNotificationUsecases

left to right direction

actor "Buyer/Client" as B
actor "Seller/Server" as S

rectangle {
Usecase UC21 as "21. Retrieve Test Result List"
Usecase UC22 as "22. Retrieve Test Result by Result Identifier"
Usecase UC23 as "23. Register for Event Notifications"
Usecase UC24 as "24. Send Event Notification"
Usecase UC25 as "25. Un-Register for Event Notifications"
}

B --> UC21
B --> UC22
B --> UC23
UC24 <-- S
B --> UC25

@enduml