@startuml suspendTestJobModel

class SuspendTestJob {

    creationDate: date-time
    href: string
    id*: string
    state*: TestJobProcessStateType
    suspensionDeniedReason: string
}
SuspendTestJob_Common <|-- SuspendTestJob



class SuspendTestJob_Common {

    suspensionReason: string
}

SuspendTestJob_Common *-->"1" TestJobRef : testJob


class SuspendTestJob_Create {

}
SuspendTestJob_Common <|-- SuspendTestJob_Create

class SuspendTestJob_Find {
    creationDate: date-time
    id*: string
    state*: TestJobProcessStateType
}
SuspendTestJob_Find *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
    rejected
}

@enduml