@startuml suspendTestJobModel

class SuspendTestJob {

    suspensionDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}
SuspendTestJob_Common <|-- SuspendTestJob



class SuspendTestJob_Common {

    suspensionReason: string
}

SuspendTestJob_Common *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml