@startuml testJobModel


class TestJob_Common {

    name*: string
    description: string
    startDateTime: date-time
    endDateTime*: date-time
    validFor*: date-time
}

class TestJob {

    actualStartDateTime: date-time
    actualEndDateTime: date-time
    creationDate*: date-time
    href*: uri
    id*: string
    lastModifiedDate*: date-time
    state*: TestJobStateType
}
TestJob_Common <|-- TestJob

enum TestJobStateType {

    acknowledged
    assessing_cancelation
    assessing_modification
    cancelled
    completed
    in_progress
    rejected
    scheduled
    suspended
}


TestJob_Common *--> Duration : recurrencePeriod
TestJob_Common *-->"1" TestProfileRefOrValue : testProfile
TestJob_Common *-->"1" ServiceRef : relatedServiceFrom
TestJob_Common *-->"1" ServiceRef : relatedServiceTo
TestJob_Common *-->"1" ServiceSpecificTestJobConfiguraton : serviceSpecificTestJobConfiguraton

class ServiceSpecificTestJobConfiguraton {
    @type*: string
}

class TestProfileRef {

    href: string
    id*: string
}
TestProfileRefOrValue <|-- TestProfileRef

class Duration {

    amount*: integer
    units*: TimeUnit
}

class TestProfileRefOrValue {

    @type*: string
}

TestProfileRefOrValue <|-- TestProfileValue

TestProfileValue *--> ServiceSpecificTestProfileConfiguraton : serviceSpecificTestProfileConfiguraton
TestProfileValue *--> ServiceSpecificationRef : relatedServiceSpecification
TestProfileValue *-->"*" RelatedContact : relatedContact

class ServiceSpecificTestProfileConfiguraton {
    @type*: string <<discriminator>>
}
class ServiceSpecificationRef {
        ServiceSpecificationRef: string
}

class RelatedContact {
    <<... attributes are skipped ...>>
}

class ServiceRef {

    href: string
    id*: string
}


@enduml