@startuml testJobModel


class TestJob_Common {
    name: string
    description: string
    startDateTime: date-time
    endDateTime: date-time
    recurencePeriod: RecurencePeriodType
    validFor: date-time
}
TestJob_Common <|-- TestJob

class TestJob {
    id: string
    actualStartDateTime: date-time
    actualEndDateTime: date-time
    state: TestJobStateType
}



enum RecurencePeriodType {
    none
    hourly
    daily
    weekly
    monthly
}

enum TestJobStateType{
    acknowledged
    canceled
    completed
    in_progress
    pending
    rejected
    resource_unavailable
    scheduled
    suspended
}


class TestJob_Create {

}
TestJob_Common <|-- TestJob_Create
TestJob_Common *-->"1" ServiceRef : relatedService
TestJob_Common *-->"1" TestProfileRefOrValue : testProfile
TestJob_Common *-->"1" TestMeasureAttributes : testMeasureAttributes

class TestMeasureAttributes {
    @type*: string
}

class TestProfileRefOrValue {
    @type*: string
}

class TestProfileRef {

    href: string
    id*: string
}
TestProfileRefOrValue <|-- TestProfileRef




class ServiceRef {
    id*: string
    name: string
}


@enduml