@startuml testJobStates

'skinparam Linetype polyline
'skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

'''decisions'''
state validation_successful <<choice>> 
 note left of validation_successful : Request Passes\nValidation?

state testScheduled <<choice>> 
 note top of testScheduled : Test Job\nScheduled?

state cancellationRequested <<choice>> 
  note right of cancellationRequested : Cancel Test\nJob Accepted?

state suspensionRequested <<choice>> 
  note right of suspensionRequested : Suspend Test\nJob Accepted?

state resumptionRequested <<choice>> 
  note right of resumptionRequested : Resume Test\nJob Accepted?

state cancellationScheduledRequested <<choice>> 
  note right of cancellationScheduledRequested : Cancel Test\nJob Accepted?



''' diagram'''
[*] -d-> acknowledged

acknowledged -d-> validation_successful

validation_successful --> rejected: No
validation_successful -r-> testScheduled: Yes

testScheduled -r-> scheduled: Yes
testScheduled --> in_progress: No

in_progress --> completed: Test Job\nCompletes
scheduled -r-> cancellationScheduledRequested: Cancel Test\nJob Received
cancellationScheduledRequested --> cancelled: Yes
cancellationScheduledRequested --> scheduled: No

scheduled -r-> assesingModification: Modify Test\nJob Received
assesingModification -l-> scheduled: Modify Test\nJob Completes


in_progress -r-> suspensionRequested: Suspend Test\nJob Received
suspensionRequested -d-> suspend: Yes
suspensionRequested --> in_progress: No

scheduled --> in_progress: Scheduled Test\nJob Started

in_progress --> scheduled: Scheduled Test\nJob Completes

suspend --> assesingModification: Modify Test\nJob Received
assesingModification --> suspend: Modify Test\nJob Completes

in_progress --> cancellationRequested: Cancel Test\nJob Received
cancellationRequested --> cancelled: Yes
cancellationRequested --> in_progress: No

suspend --> resumptionRequested: Resume Test\nJob Received
resumptionRequested --> in_progress: Yes
resumptionRequested --> suspend: No



rejected -d-> [*]
completed -d-> [*]
cancelled -d-> [*]
' resource_unavailable -d-> [*]

@enduml