@startuml testProfileRefOrValue



class TestProfileRef {

    href: string
    id*: string
}
TestProfileRefOrValue <|-- TestProfileRef



class TestProfileRefOrValue {

    @type*: string
}

TestProfileRefOrValue <|-- TestProfileValue

TestProfileValue *--> ServiceSpecificTestProfileConfiguraton : serviceSpecificTestProfileConfiguraton
TestProfileValue *--> ServiceSpecificationRef : relatedServiceSpecification
TestProfileValue *-->"*" RelatedContact : relatedContact


class TestProfileValue {

}

class ServiceSpecificTestProfileConfiguraton {

    @type*: string
}

class ServiceSpecificationRef {

    href: uri
    id*: string
}

class RelatedContact {

    emailAddress: string
    name: string
    organization: string
    phoneNumber: string
    phoneNumberExtension: string
    postalAddress: string
}


class TestJob {}

class TestJob_Common {}

TestJob_Common <|-- TestJob

TestJob_Common *-->"1" TestProfileRefOrValue : testProfile

@enduml