@startuml TestJobClass
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServicePayloadSpecificAttributes>> FireBrick
    ClassBorderColor<<ResultPayload>> FireBrick
}
set namespaceSeparator none


class TestJob_Common {

    name*: string
    description: string
    startDateTime: date-time
    endDateTime*: date-time
    validFor*: date-time
}

TestJob_Common *--> Duration : recurrencePeriod
TestJob_Common *-->"1" TestProfileRefOrValue : testProfile
TestJob_Common *-->"1" ServiceRef : relatedServiceFrom
TestJob_Common *-->"1" ServiceRef : relatedServiceTo
TestJob_Common *-->"1" ServiceSpecificTestJobConfiguraton : serviceSpecificTestJobConfiguraton


class TestJob {

    actualStartDateTime: date-time
    actualEndDateTime: date-time
    creationDate*: date-time
    href*: uri
    id*: string
    lastModifiedDate*: date-time
    state*: TestJobStateType
}

TestJob_Common <|-- TestJob

enum TestJobStateType {

    acknowledged
    assessing_cancelation
    assessing_modification
    cancelled
    completed
    in_progress
    rejected
    scheduled
    suspended
}

class Duration {

<<... attributes are skipped ...>>
}

class TestProfileRefOrValue {

<<... attributes are skipped ...>>
}

class ServiceRef {

<<... attributes are skipped ...>>
}

class ServiceSpecificTestJobConfiguraton {
    <<... attributes are skipped ...>>
}