@startuml testJobDataModel
skinparam {
    scale 4096 width
}

class RelatedContact {

    emailAddress: string
    name: string
    organization: string
    phoneNumber: string
    phoneNumberExtension: string
    postalAddress: string
}

class ServiceRef {

    href: string
    id*: string
}



class ServiceSpecificTestJobConfiguration {

    @type*: string
}



class ServiceSpecificTestProfileConfiguration {

    @type*: string
}



class ServiceSpecificationRef {

    href: uri
    id*: string
}

class TestJob {

    actualStartDateTime: date-time
    actualEndDateTime: date-time
    creationDate*: date-time
    href*: uri
    id*: string
    lastModifiedDate*: date-time
    state*: TestJobStateType
}
TestJob_Common <|-- TestJob

TestJob *-->"*" TerminationError : terminationError


class TestJob_Common {

    name*: string
    description: string
    startDateTime: date-time
    endDateTime*: date-time
    validFor*: date-time
}

TestJob_Common *--> Duration : recurrencePeriod
TestJob_Common *-->"1" TestProfileRefOrValue : testProfile
TestJob_Common *-->"1" ServiceRef : relatedServiceFrom
TestJob_Common *-->"1" ServiceRef : relatedServiceTo
TestJob_Common *-->"1" ServiceSpecificTestJobConfiguration : serviceSpecificTestJobConfiguration


class TestJob_Find {

    endDateTime*: string
    id: string
    name*: string
    startDateTime*: string
}

TestJob_Find *-->"1" ServiceRef : relatedServiceFrom
TestJob_Find *-->"1" ServiceRef : relatedServiceTo
TestJob_Find *-->"1" TestProfileRefOrValue : testProfile


class TestProfileRef {

    href: string
    id*: string
}
TestProfileRefOrValue <|-- TestProfileRef



class TestProfileRefOrValue {

    @type*: string
}



class TestProfileValue {

}
TestProfileRefOrValue <|-- TestProfileValue

TestProfileValue *--> ServiceSpecificTestProfileConfiguration : serviceSpecificTestProfileConfiguration
TestProfileValue *--> ServiceSpecificationRef : relatedServiceSpecification
TestProfileValue *-->"*" RelatedContact : relatedContact

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

enum TestJobStateType {

    acknowledged
    assessingCancellation
    assessingModification
    cancelled
    completed
    inProgress
    rejected
    scheduled
    suspended
}

enum TimeUnit {

    seconds
    minutes
    businessHours
    calendarHours
    businessDays
    calendarDays
    months
    years
}
@enduml
