@startuml testJobStates

'skinparam Linetype polyline
'skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

'''decisions'''
state validation_successful <<choice>> 
 note right of validation_successful : Request Passes\nValidation?

state testScheduled <<choice>> 
 note top of testScheduled : Test Job\nScheduled?

' state suspensionRequested <<choice>> 
'   note right of suspensionRequested : Suspend Test\nJob Accepted?

' state resumptionRequested <<choice>> 
'   note right of resumptionRequested : Resume Test\nJob Accepted?

' state cancellationFailed <<choice>> 
'   note left of cancellationFailed : Scheduled Test\nJob?

' state cancellationFailed_2 <<choice>> 
'   note left of cancellationFailed_2 : Suspended Test\nJob?


''' diagram'''
[*] -d-> acknowledged

acknowledged --> validation_successful

validation_successful --> rejected: No
validation_successful --> testScheduled: Yes

testScheduled --> scheduled: Yes
testScheduled --> inProgress: No

inProgress --> completed: Test Job\nCompletes
inProgress --> assesingCancelation: Cancel Test\nJob Received
scheduled --> assesingCancelation: Cancel Test\nJob Received
suspend --> assesingCancelation: Cancel Test\nJob Received
assesingCancelation --> cancelled: Cancelation Successful
assesingCancelation --> suspend: Cancelation Failed
assesingCancelation --> scheduled: Cancelation Failed
assesingCancelation --> inProgress: Cancelation Failed


scheduled -r-> assesingModification: Modify Test\nJob Received
assesingModification -l-> scheduled: Modify Test\nJob Completes


scheduled --> inProgress: Scheduled Test\nJob Started
inProgress --> scheduled: Scheduled Test\nJob Completes

inProgress -r-> suspend: Suspend Test\nJob Received
suspend --> inProgress: Resume Test\nJob Received

suspend --> assesingModification: Modify Test\nJob Received
assesingModification --> suspend: Modify Test\nJob Completes

rejected -d-> [*]
completed -d-> [*]
cancelled -d-> [*]

@enduml