@startuml testJobWithoutTestProfileModel

class TestJob_Common {

    name*: string
    description: string
    startDateTime: date-time
    endDateTime*: date-time
    validFor*: date-time
}

class TestJob {

    actualStartDateTime: date-time
    actualEndDateTime: date-time
    creationDate*: date-time
    href*: uri
    id*: string
    lastModifiedDate*: date-time
    state*: TestJobStateType
}
TestJob_Common <|-- TestJob

enum TestJobStateType {

    acknowledged
    assessingCancellation
    assessingModification
    cancelled
    completed
    inProgress
    rejected
    scheduled
    suspended
}


TestJob_Common *--> Duration : recurrencePeriod
TestJob_Common *-->"1" TestProfileRefOrValue : testProfile
TestJob_Common *-->"1" ServiceRef : relatedServiceFrom
TestJob_Common *-->"1" ServiceRef : relatedServiceTo
TestJob_Common *-->"1" ServiceSpecificTestJobConfiguration : serviceSpecificTestJobConfiguration

class ServiceSpecificTestJobConfiguration {
    <<... attributes are skipped ...>>
}

class Duration {

    <<... attributes are skipped ...>>
}

class TestProfileRefOrValue {

    @type*: string
}

TestProfileRefOrValue <|-- TestProfileValue

TestProfileValue *--> ServiceSpecificTestProfileConfiguration : serviceSpecificTestProfileConfiguration
TestProfileValue *--> ServiceSpecificationRef : relatedServiceSpecification
TestProfileValue *-->"*" RelatedContact : relatedContact

class ServiceSpecificTestProfileConfiguration {
    @type*: string
}
class ServiceSpecificationRef {
    href: uri
    id*: string
}

class RelatedContact {
    emailAddress: string
    name: string
    organization: string
    phoneNumber: string
    phoneNumberExtension: string
    postalAddress: string
}

class ServiceRef {

<<... attributes are skipped ...>>
}
@enduml