@startuml useCase13Polling
hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S


B -> S : POST {{baseUrl}}/cancelTestJob (CancelTestJob_Common)
S -> S : basic validation

alt succesful inquiry
  S --> B : 201 CancelTestJob with {{id}}, `acknowledged` state
  
  ...

  loop periodically until CancelTestJob in accepted state
      B -> S :   GET {{baseUrl}}/cancelTestJob/{{id}}
      return 200 CancelTestJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end


@enduml