@startuml useCase2Model

class TestProfile_Common {

    description: string
    isBundled*: boolean
    lifecycleStatus*: TestProfileLifecycleStatusType
    name*: string
    validFor*: date-time
}

TestProfile_Common *-->"*" TestProfileRelationship : testProfileRelationship
TestProfile_Common *--> ServiceSpecificTestProfileConfiguraton : serviceSpecificTestProfileConfiguraton
TestProfile_Common *-->"1" ServiceSpecificationRef : relatedServiceSpecification
TestProfile_Common *-->"*" RelatedContact : relatedContact


class TestProfile {

    id: string 
    creationDateTime: date-time
    lifecycleState TestProfileLifecycleStateType
    lastUpdate: date-time
}
TestProfile_Common <|-- TestProfile

enum TestProfileLifecycleStateType {

    assigned
    available
}
enum TestProfileLifecycleStatusType {

    experimental
    pending
    approved
    deprecated
}

class TestProfileRelationship {

    <<... attributes are skipped ...>>
}

class ServiceSpecificTestProfileConfiguraton {

    <<... attributes are skipped ...>>
}

class ServiceSpecificationRef {

    <<... attributes are skipped ...>>
}

class RelatedContact {

    <<... attributes are skipped ...>>
}

@enduml