@startuml useCase4PatchModel

class TestProfile_Modify {
    
    description: string
    isBundled: boolean
    lifecycleStatus: TestProfileLifecycleStatusType
    name: string
    relatedTestProfile: TestProfileRef
    serviceSpecificTestProfileAttributes: ServiceSpecificTestProfileAttributes
    relatedServiceSpecification: ServiceSpecificationRef
    relatedContact: RelatedContact
}

enum TestProfileLifecycleStatusType {
    experimantal
    pending
    approved
    deprecated
}

class ServiceSpecificTestProfileAttributes {
    @type*: string <<discriminator>>
}

class RelatedContactRef {
    <<... attributes are skipped ...>>
}

class TestProfileRef {
    relatedTestProfileId: string
}

class ServiceSpecificationRef {
        relatedServiceSpecificationId: string
}

TestProfile_Modify *-->"0..1" ServiceSpecificTestProfileAttributes : serviceSpecificTestProfileAttributes
TestProfile_Modify *-->"0..*" TestProfileRef : relatedTestProfile
TestProfile_Modify *-->"0..*" ServiceSpecificationRef : relatedServiceSpecification
TestProfile_Modify *-->"0..*" RelatedContactRef : relatedContact

@enduml