@startuml useCase5DeleteFlow

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S
activate S

autonumber
B -> S : DELETE /testProfile/{{id}}

S -> S: find Test Profile by id
S -> S: check Profile lifecycleState
alt lifecycleState != 'assigned'
    S -> S: delete Test Profile
    S -> B: 204 Deleted
    S -> B: POST testProfileDeleteEvent
else
    S -> B: 400 Bad Request
end

@enduml