@startuml useCase17Model

class SuspendTestJob {

    suspensionDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}

SuspendTestJob *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml