@startuml useCase11Model

class ModifyTestJob {

    modificationDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}

ModifyTestJob *-->"1" TestJobRef : testJob


enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml