@startuml useCase20Model

class ResumeTestJob {

    resumptionDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}

ResumeTestJob *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml