@startuml useCase7Notification

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

B -> S: POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
...
B -> S: POST {{baseUrl}}/testJob (TestJob_Common)
S -> S: basic validation

alt succesful inquiry
  S --> B: 201 TestJob with {{id}}, `acknowledged` state 
  S -> B: {{callbackUrl}}/listener/testJobCreateEvent ({{id}})
  B --> S: 204 confirmation

  ...

  group loop [until Test Job in in completed, canceled or rejected state]
      S -> B: {{callbackUrl}}/listener/testJobStateChangeEvent ({{id}})
      B --> S: 204 confirmation
      B -> S:   GET {{baseUrl}}/testJob/{{id}}
      return 200 TestJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end 

...

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S --> B : 204 confirmation

@enduml