@startuml useCase14Model

class CancelTestJob {

    cancellationDeniedReason: string
    creationDate*: date-time
    href*: string
    id*: string
    state*: TestJobProcessStateType
}

CancelTestJob *-->"1" TestJobRef : testJob

enum TestJobProcessStateType {

    accepted
    acknowledged
    rejected
}

@enduml