@startuml cancelFaultManagementJobModel

class CancelFaultManagementJob {
    creationDateTime*: date-time
    href: string
    id*: string
    state*: FaultManagementJobProcessStateType
}
CancelFaultManagementJob_Create <|-- CancelFaultManagementJob

class CancelFaultManagementJob_Create {

}

CancelFaultManagementJob_Create *-->"1" FaultManagementJobRef : faultManagementJob

class FaultManagementJobRef {
    faultManagementJobHref: string
    faultManagementJobId*: string
    @type*: string
}

enum FaultManagementJobProcessStateType {
    acknowledged
    completed
    inProgress
    rejected
}

@enduml