@startuml cancelFaultManagementJobModel

class CancelFaultManagementJob {

    creationDate*: date-time
    href: string
    id*: string
    state*: FaultManagementJobProcessStateType
}
CancelFaultManagementJob_Create <|-- CancelFaultManagementJob



class CancelFaultManagementJob_Create {

}

CancelFaultManagementJob_Create *-->"1" FaultManagementJobRef : faultManagementJob


enum FaultManagementJobProcessStateType {
    acknowledged
    completed
    inProgress
    rejected
}

@enduml