@startuml faultManagementDataModelPart4

class FaultManagementReport {
    creationDateTime*: date-time
    description: string
    href: uri
    id*: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    state*: FaultManagementReportStateType
    terminationError: TerminationError
}

FaultManagementReport *-->"1" FaultManagementJobRef : faultManagementJob
FaultManagementReport *-u->"1" TimeDuration : granularity
FaultManagementReport *-->"1" MonitoredObjectRef : monitoredObject
FaultManagementReport *-l->"*" ReportContentItem : reportContent
FaultManagementReport *-u->"1" ReportingTimeframe : reportingTimeframe
FaultManagementReport *--> AttachmentURL : reportUrl
FaultManagementReport *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class FaultManagementJobRef {
    faultManagementJobHref: string
    faultManagementJobId*: string
    @type*: string    
}

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"1..*" ServiceSpecificResult : measurementData

class ReportingTimeframe {
    reportingStartDate: date-time
    reportingEndDate: date-time
}

class MeasurementTime {
    measurementStartDate*: date-time
    measurementEndDate: date-time
    measurementInterval: TimeDuration
}

class AttachmentURL {
    retentionPeriod: date-time
    url*: uri
}

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {
    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class ServiceSpecificConfiguration {
    @type*: string
}

class ServiceSpecificResult {
    @type*: string
}

enum FaultManagementReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}

@enduml
