@startuml faultManagementDataModel

class FaultManagementJob {
    creationDateTime*: date-time
    href: uri
    id*: string
    lastTimeModified: date-time
    state*: FaultManagementJobStateType
}
FaultManagementJob *-->"*" TerminationError: terminationError

FaultManagementJob_Create <|-- FaultManagementJob

class FaultManagementJob_Create {
    description: string
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

FaultManagementJob_Create *-->"1" TimeDuration : granularity
FaultManagementJob_Create *-->"1" MonitoredObjectRef : monitoredObject
FaultManagementJob_Create *-->"1" TimeDuration : reportingPeriod
FaultManagementJob_Create *-->"1" ScheduleDefinition : scheduleDefinition
FaultManagementJob_Create *-u->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class TerminationError {
    code: Error422Code
    propertyPath: string
    value: string
}

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {

    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class ScheduleDefinition {
    scheduleDefinitionStartTime: date-time
    scheduleDefinitionEndTime: date-time
}

ScheduleDefinition *--> RecurringSchedule : recurringSchedule
ScheduleDefinition *--> TimeDuration : executionDuration

class RecurringSchedule {
    second: string
    minute: string
    hour: string
    dayOfMonth: string
    month: string
    dayOfWeek: string
}

class TimeDuration {
    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}

enum JobType {
    proactive
    on-demand
    passive
}

enum OutputFormat {
    json
    xml
    avro
    csv
}

enum ResultFormat {
    attachment
    payload
}

class ServiceSpecificConfiguration {
    @type*: string
}

enum TimeDurationUnits {
    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}

enum FaultManagementJobStateType {
    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

@enduml
