@startuml faultManagementJobStates

'skinparam Linetype polyline
'skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

'''decisions'''
state validation_successful <<choice>> 
 note top of validation_successful : Validation successful?

state immediate <<choice>> 
 note left of immediate : Immediate start time?

state modification <<choice>> 
 note top of modification : Modification successful?

state resources <<choice>> 
 note right of resources : Resources available?

state recurring <<choice>> 
 note left of recurring : Recurring job?

state "inProgress" as inProgress
state "resourcesUnavailable" as resourcesUnavailable

''' diagram'''
[*] -d-> acknowledged

acknowledged -d-> validation_successful

validation_successful -d-> rejected: No

validation_successful -r-> immediate: Yes

immediate -r-> scheduled: No
scheduled -d-> pendingCancel: Cancel
scheduled -d-> resources: schedule start time
resources -d-> resourcesUnavailable: No
resources -l-> inProgress: Yes

immediate -d-> resources: Yes
inProgress -d-> recurring
recurring -d-> completed: No
recurring -u-> immediate: Yes

inProgress -d-> pendingCancel: Cancel
inProgress -u-> suspended: Suspend
suspended -r-> inProgress: Resume
suspended -r-> pendingCancel: Cancel

pendingCancel -> cancelled

suspended -u-> modification: Modify
modification -d-> suspended: No

scheduled -u-> modification: Modify
modification -d-> scheduled: No


modification -r-> pending: Yes

pending -d-> immediate

rejected -d-> [*]
completed -d-> [*]
cancelled -d-> [*]
resourcesUnavailable -d-> [*]

@enduml