@startuml faultManagementReportModel

class FaultManagementReport {
    creationDateTime*: date-time
    description: string
    granularity*: TimeDuration
    href: uri
    id*: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    state*: FaultManagementReportStateType
    terminationError: TerminationError
}

FaultManagementReport *-l->"1" FaultManagementJobRef : faultManagementJob
FaultManagementReport *-r->"1" MonitoredObjectRef : monitoredObject
FaultManagementReport *-->"0..*" ReportContentItem : reportContent
FaultManagementReport *-->"1" ReportingTimeframe : reportingTimeframe
FaultManagementReport *-u->"0..1" AttachmentURL : reportUrl
FaultManagementReport *-u->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

enum FaultManagementReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"0..*" ServiceSpecificResult : measurementData

class ServiceSpecificResult {
    @type*: string
}

class ReportingTimeframe {
    reportingStartDate: date-time
    reportingEndDate: date-time
}

class MeasurementTime {
    measurementStartDate*: date-time
    measurementEndDate: date-time
    measurementInterval: TimeDuration
}

class AttachmentURL {
    retentionPeriod: date-time
    url*: uri
}

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {
    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

@enduml