@startuml faultManagementReportComplexQueryModel

class FaultManagementReportComplexQuery_Create {

    creationDate.gt: date-time
    creationDate.lt: date-time
    outputFormat: OutputFormat
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: FaultManagementReportStateType
}

FaultManagementReportComplexQuery_Create *--> FaultManagementJobRef : faultManagementJob
FaultManagementReportComplexQuery_Create *--> TimeDuration : granularity
FaultManagementReportComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
FaultManagementReportComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration


@enduml