@startuml faultManagementJobComplexQueryModel

class FaultManagementJobComplexQuery_Create {
    creationDateTime.gt: date-time
    creationDateTime.lt: date-time
    jobPriority: integer
    jobType: JobType
    outputFormat: OutputFormat
    resultFormat: ResultFormat
    state: FaultManagementJobStateType
}

FaultManagementJobComplexQuery_Create *--> TimeDuration : granularity
FaultManagementJobComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
FaultManagementJobComplexQuery_Create *--> TimeDuration : reportingPeriod
FaultManagementJobComplexQuery_Create *--> ScheduleDefinition : scheduleDefinition
FaultManagementJobComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceFromToRef {
    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class TimeDuration {
    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}

enum TimeDurationUnits {
    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}

enum JobType {
    proactive
    on-demand
    passive
}

enum OutputFormat {
    json
    xml
    avro
    csv
}

enum ResultFormat {
    attachment
    payload
}

enum FaultManagementJobStateType {
    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

@enduml