@startuml faultManagementJobModel

class FaultManagementJob {

    creationDate*: date-time
    href: uri
    id*: string
    lastModifiedDate: date-time
    rejectionReason: string
    state*: FaultManagementJobStateType
}
FaultManagementJob_Create <|-d- FaultManagementJob



enum FaultManagementJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

class FaultManagementJob_Create {

    description: string
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

FaultManagementJob_Create *-u->"1" TimeDuration : granularity
FaultManagementJob_Create *-r->"1" MonitoredObjectRef : monitoredObject
FaultManagementJob_Create *-u->"1" TimeDuration : reportingPeriod
FaultManagementJob_Create *-l->"1" ScheduleDefinition : scheduleDefinition
FaultManagementJob_Create *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class ServiceSpecificConfiguration {

    @type*: string
}

@enduml