@startuml faultManagementReportComplexQueryModel

class FaultManagementReportComplexQuery {

    creationDate*: date-time
    description: string
    lastModifiedDate: date-time
    state*: FaultManagementReportStateType
}

FaultManagementReportComplexQuery *-->"1" FaultManagementJobRef : faultManagementJob
FaultManagementReportComplexQuery *-->"1" FaultManagementReportRef : faultManagementReport
FaultManagementReportComplexQuery *-->"1" ReportingTimeframe : reportingTimeframe



class FaultManagementReportComplexQuery_Create {

    creationDate.gt: date-time
    creationDate.lt: date-time
    faultManagementJobId: string
    granularity: Interval
    lastModifiedDate.gt: date-time
    lastModifiedDate.lt: date-time
    outputFormat: OutputFormat
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: FaultManagementReportStateType
}

FaultManagementReportComplexQuery_Create *-->"0..1" ServiceId : serviceId
FaultManagementReportComplexQuery_Create *-->"0..1" ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes

@enduml