@startuml faultManagementJobComplexQueryModel

class FaultManagementJobComplexQuery_Create {

    creationDate.gt: date-time
    creationDate.lt: date-time
    jobPriority: integer
    jobType: JobType
    lastModifiedDate.gt: date-time
    lastModifiedDate.lt: date-time
    outputFormat: OutputFormat
    resultFormat: ResultFormat
    state: FaultManagementJobStateType
}

FaultManagementJobComplexQuery_Create *--> TimeDuration : granularity
FaultManagementJobComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
FaultManagementJobComplexQuery_Create *--> TimeDuration : reportingPeriod
FaultManagementJobComplexQuery_Create *--> ScheduleDefinition : scheduleDefinition
FaultManagementJobComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

enum FaultManagementJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

class TimeDuration {

    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}



enum TimeDurationUnits {

    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}

enum JobType {

    proactive
    on-demand
    passive
}

enum OutputFormat {
    json
    xml
    avro
    csv
}

enum ResultFormat {
    attachment
    payload
}

@enduml