@startuml fmEntities
autonumber

actor "Buyer/Client" as B

entity FaultManagementJob as FJ
entity FaultManagementReport as FMR

B -> FJ: POST /faultManagementJob request
activate FJ
FJ --> B: Created

note right of FJ: On scheduled date

FJ -> FJ: state: inProgress

FJ --> FMR: (causes report creation)

activate FMR

FMR -> FMR: state: inProgress

FJ -> FMR: collect data

FMR -> FMR: state: completed

FMR --> FJ: (report completed)

note right of FJ: non-recurring Job
FJ -> FJ: state: completed

B -> FMR: GET /faultManagementReport
FMR --> B: Fault Management Report content

@enduml