@startuml fmProvisioning
autonumber

actor "Buyer/Client" as B
box "Seller/Server"
collections "SOF:FaultManagement" as SOF

entity Hub 

opt
B -> Hub : POST {{baseUrl}}/hub with {{callbackUrl}} 
end

B -> SOF: POST {{baseUrl}}/faultManagementJob request

create entity FaultManagementJob as FMJ
SOF -> FMJ: <<create>>
activate FMJ
SOF --> B: FaultManagementJob with {{id}}

opt
FMJ -> Hub: createEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementJobCreateEvent
end

note right of FMJ: On scheduled date
FMJ -> FMJ: state: inProgress

opt
FMJ -> Hub: stateChangeEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementJobStateChangeEvent
end

create entity FaultManagementReport as FMR
FMJ -> FMR: <<create>>

activate FMR

opt
FMR -> Hub: createEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementReportCreateEvent
end

FMR -> FMR: state: inProgress

opt
FMR -> Hub: stateChangeEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementReportStateChangeEvent
end

FMJ -> FMR: collectData

note right of FMJ: reportingPeriod elapses


FMR -> FMR: state: completed

opt
FMR -> Hub: stateChangeEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementReportStateChangeEvent
end

FMR --> FMJ: (report completed)

opt
FMJ -> Hub: reportReadyEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementJobReportReadyEvent
end

note right of FMJ: Schedule elapses

FMJ -> FMJ: state: completed|scheduled

opt
FMJ -> Hub: stateChangeEvent
Hub -> B: POST {{callbackUrl}}/listener/faultManagementJobStateChangeEvent
end

B -> SOF: GET {{baseUrl}}/faultManagementReport/{{id}} request
SOF -> FMR: <<retrieve>>
SOF --> B: FaultManagementReport with {{id}}

entity Hub

end box

@enduml