@startuml fmProvisioning
autonumber

actor BUS as B
collections "SOF:FaultManagement" as SOF

entity Hub 

opt
B -> Hub: registerListener (FaultManagementJobNotification)
B -> Hub: registerListener (FaultManagementReportNotification)
end

B -> SOF: createFaultManagementJob

create entity FaultManagementJob as FMJ
SOF -> FMJ: <<create>>

SOF --> B: Response (FaultManagementJob)

activate FMJ

opt
FMJ -> Hub: createEvent
Hub -> B: notifyListeners (faultManagementJobCreateEvent)
end

note right of FMJ: On scheduled date
FMJ -> FMJ: state: inProgress

opt
FMJ -> Hub: stateChangeEvent
Hub -> B: notifyListeners (faultManagementJobStateChangeEvent)
end

create entity FaultManagementReport as FMR
FMJ -> FMR: <<create>>

activate FMR

opt
FMR -> Hub: createEvent
Hub -> B: notifyListeners (faultManagementReportCreateEvent)
end

FMR -> FMR: state: inProgress

opt
FMR -> Hub: stateChangeEvent
Hub -> B: notifyListeners (faultManagementReportStateChangeEvent)
end

FMJ -> FMR: collectData

note right of FMJ: reportingPeriod elapses


FMR -> FMR: state: completed

opt
FMR -> Hub: stateChangeEvent
Hub -> B: notifyListeners (faultManagementReportStateChangeEvent)
end

FMR --> FMJ: (report completed)

opt
FMJ -> Hub: reportReadyEvent
Hub -> B: notifyListeners (faultManagementJobReportReadyEvent)
end

note right of FMJ: Schedule elapses

FMJ -> FMJ: state: completed|scheduled

opt
FMJ -> Hub: stateChangeEvent
Hub -> B: notifyListeners (faultManagementJobStateChangeEvent)
end

B -> SOF: getReport
SOF -> FMR: <<retrieve>>
SOF --> B: Response (FaultManagementReport)

entity Hub

@enduml