@startuml modifyFaultManagementJobModel

class ModifyFaultManagementJob {

    creationDate*: date-time
    href: string
    id*: string
    state*: FaultManagementJobProcessStateType
}
ModifyFaultManagementJob_Create <|-- ModifyFaultManagementJob



class ModifyFaultManagementJob_Create {

    description: string
    jobPriority: integer
    outputFormat: OutputFormat
    resultFormat: ResultFormat
}

ModifyFaultManagementJob_Create *-l->"1" FaultManagementJobRef : faultManagementJob
ModifyFaultManagementJob_Create *--> TimeDuration : granularity
ModifyFaultManagementJob_Create *--> TimeDuration : reportingPeriod
ModifyFaultManagementJob_Create *--> ScheduleDefinition : scheduleDefinition
ModifyFaultManagementJob_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

enum FaultManagementJobProcessStateType {
    acknowledged
    completed
    inProgress
    rejected
}

@enduml

