@startuml trackingRecordModel

class FmTrackingRecord {
    creationDateTime*: date-time
    description: string
    id*: string
    request: string
    source: string
}

FmTrackingRecord *-->"1" RelatedObjectRef : relatedObjectId

class RelatedObjectRef {

}

class FaultManagementJobRef {
    faultManagementJobHref: string
    faultManagementJobId*: string
    @type*: string    
}

class FaultManagementReportRef {
    faultManagementReportHref: string
    faultManagementReportId*: string
    @type*: string
}

RelatedObjectRef <|-- FaultManagementJobRef
RelatedObjectRef <|-- FaultManagementReportRef

@enduml