@startuml useCase5Model

class ModifyFaultManagementJob_Find {

    creationDate*: date-time
    id*: string
    state*: FaultManagementJobProcessStateType
}

ModifyFaultManagementJob_Find *-->"1" FaultManagementJobRef : faultManagementJob

enum FaultManagementJobProcessStateType {

    acknowledged
    completed
    inProgress
    rejected
}

@enduml