@startuml useCase4Notification

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

B -> S: POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
...
B -> S: POST {{baseUrl}}/modifyFaultManagementJob (ModifyFaultManagementJob_Create)
S -> S: basic validation

alt successful inquiry
  S --> B: 201 ModifyFaultManagementJob with {{id}}, `acknowledged` state 
  ...

  group loop [until ModifyFaultManagementJob in terminal state]
      S -> B: {{callbackUrl}}/listener/modifyFaultManagementJobStateChangeEvent ({{id}})
      B --> S: 204 confirmation
      B -> S:   GET {{baseUrl}}/modifyFaultManagementJob/{{id}}
      return 200 ModifyFaultManagementJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end 

...

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S --> B : 204 confirmation

@enduml