@startuml useCase2Model

class FaultManagementJob_Find {

    creationDate*: date-time
    description: string
    granularity*: Interval
    id*: string
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    reportingPeriod*: Interval
    state*: FaultManagementJobStateType
}

FaultManagementJob_Find *-->"1" ScheduleDefinition : scheduleDefinition
FaultManagementJob_Find *-->"1" ServiceId : serviceId

enum FaultManagementJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

@enduml