@startuml useCase4Polling

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S


B -> S : POST {{baseUrl}}/modifyFaultManagementJob (ModifyFaultManagementJob_Create)
S -> S : basic validation

alt successful inquiry
  S --> B : 201 ModifyFaultManagementJob with {{id}}, `acknowledged` state
  
  ...

  loop periodically until ModifyFaultManagementJob in terminal state
      B -> S :   GET {{baseUrl}}/modifyFaultManagementJob/{{id}}
      return 200 ModifyFaultManagementJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end


@enduml