@startuml
hide footbox

participant Buyer
participant Seller

Buyer -> Buyer : createL1Payload(<List>uni,<Listvc,<List>vcep)
Buyer -> Buyer: createL1Uni()

Buyer -> Seller : POST {{baseUrl}}/serviceOrder (ServiceOrder_Create)
Seller -> Seller : basic validation

alt succesful inquiry
  Seller --> Buyer : 201 ServiceOrder with {{id}}, `acknowledged` state
  
  ...

  loop periodically until serviceOrder in completion state
      Buyer -> Seller :   GET {{baseUrl}}/serviceOrder/{{id}}
      return 200 ServiceOrder in current state
  end

else validation or internal problem
  Seller --> Buyer : 4xx or 5xx error response
end


@enduml