@startuml

title SD-WAN Service Schema - Test API Schemas Diagram

entity AdministrativeState { 
}

entity ApplicationFlow { 
    appName: String
    applicationFlowCriteria: ApplicationFlowCriteria
}

entity ApplicationFlowCriteria { 
    ethertype: List<Integer>
    cVlans: List<Integer>
    ipv4SourceAddress: List<Ipv4Prefix>
    ipv4DestinationAddress: List<Ipv4Prefix>
    ipv4SourceOrDestinationAddress: List<Ipv4Prefix>
    ipv4ProtocolList: List<Integer>
    ipv6SourceAddress: List<Ipv6Prefix>
    ipv6DestinationAddress: List<Ipv6Prefix>
    ipv6SourceOrDestinationAddress: List<Ipv6Prefix>
    nextHeadV6: List<Integer>
    tcpUdpSourcePortList: List<Integer>
    tcpUdpDestinationPortList: List<Integer>
    tcpUdpSourceOrDestinationPortList: List<Integer>
    any: Boolean
    applicationIdentifier: List<ApplicationIdentifier>
}

entity ApplicationFlowGroup { 
    name: String
    applicationFlows: List<ApplicationFlow>
}

entity ApplicationIdentifier { 
    appId: String
}

entity Backup { 
}

entity BandwidthPolicyCriterion { 
    commit: List<Integer>
    max: List<Integer>
}

entity BillingMethod { 
}

entity Encryption { 
}

entity InternetBreakout { 
}

entity Ipv4ConnectionAddressing { 
    ipv4AddressType: String
    ipv4PrimarySubnet: List<Ipv4Subnet>
    ipv4SecondarySubnetList: List<Ipv4Subnet>
}

entity Ipv4Prefix { 
    ipv4Address: String
    prefixLength: Integer
}

entity Ipv4Subnet { 
    ipv4Prefix: Ipv4Prefix
    serviceProviderIpv4Addresses: List<String>
}

entity Ipv6ConnectionAddressing { 
    ipv6AddressType: String
    ipv6SubnetList: List<Ipv6Subnet>
}

entity Ipv6Prefix { 
    ipv6Address: String
    prefixLength: Integer
}

entity Ipv6Subnet { 
    ipv6Prefix: Ipv6Prefix
    serviceProviderIpv6Addresses: List<String>
}

entity L2Interface { 
    l2InterfaceType: String
    vlanId: List<Integer>
}

entity OperationalState { 
}

entity Period { 
    value: Integer
    units: TimeUnits
}

entity Policy { 
    polName: String
    policyCriteria: PolicyCriteria
    serviceProviderPolicyCriterion: List<ServiceProviderPolicyCriterion>
}

entity PolicyCriteria { 
    internetBreakout: List<InternetBreakout>
    encyrption: List<Encryption>
    publicPrivate: List<PublicPrivate>
    billingMethod: List<BillingMethod>
    backUp: List<Backup>
    bandwidthPolicyCriterion: List<BandwidthPolicyCriterion>
}

entity PolicyMap { 
    applicationFlow: List<ApplicationFlow>
    applicationFlowGroup: List<ApplicationFlowGroup>
    policy: Policy
}

entity PublicPrivate { 
}

entity SdWanUni { 
    administrativeState: AdministrativeState
    operationalState: OperationalState
    uniIdentifier: String
    l2Interface: L2Interface
    maxL2FrameSize: Integer
    ipv4ConnectionAddressing: Ipv4ConnectionAddressing
    ipv6ConnectionAddressing: Ipv6ConnectionAddressing
    swVcEndPoint: List<SwVcEndPointRef>
}

entity SdWanUniRef { 
    href: URI
    id: UUID
}

entity SdWanVc { 
    administrativeState: AdministrativeState
    operationalState: OperationalState
    swVcIdentifier: String
    swVcEndPointList: List<SwVcEndPoint>
    serviceUptimeObjective: ServiceUptimeObjective
    ipv4ReservedPrefixes: List<Ipv4Prefix>
    ipv6ReservedPrefixes: List<Ipv6Prefix>
    listOfPolicies: List<Policy>
    listOfApplicationFlows: List<ApplicationFlow>
    listOfApplicationFlowGroups: List<ApplicationFlowGroup>
}

entity ServiceProviderPolicyCriterion { 
    policyCriteria: List<String>
}

entity ServiceUptimeObjective { 
    startTime: TimeAndDate
    period: Period
    uptimeObjective: Integer
}

entity SwVcEndPoint { 
    administrativeState: AdministrativeState
    operationalState: OperationalState
    endPointIdentifier: String
    policyMap: List<PolicyMap>
    swvc: SwVcRef
    sdWanUni: SdWanUniRef
}

entity SwVcEndPointRef { 
    swvcref: SwVcRef
    id: UUID
}

entity SwVcRef { 
    href: URI
    id: UUID
}

entity TimeAndDate { 
    day: Integer
    hour: Integer
    minute: Integer
    month: Integer
    second: Integer
    year: Integer
}

entity TimeUnits { 
}


Policy -- PolicyCriteria : policyCriteria
Policy -- "0..*" ServiceProviderPolicyCriterion : serviceProviderPolicyCriterion
PolicyCriteria -- "0..*" BandwidthPolicyCriterion : bandwidthPolicyCriterion
SdWanVc -- "0..*" SwVcEndPoint : swVcEndPointList
SdWanVc -- ServiceUptimeObjective : serviceUptimeObjective
SdWanVc -- "0..*" Ipv4Prefix : ipv4ReservedPrefixes
SdWanVc -- "0..*" Ipv6Prefix : ipv6ReservedPrefixes
SdWanVc -- "0..*" Policy : listOfPolicies
SdWanVc -- "0..*" ApplicationFlow : listOfApplicationFlows
SdWanVc -- "0..*" ApplicationFlowGroup : listOfApplicationFlowGroups
SwVcEndPointRef -- SwVcRef : swvcref
ApplicationFlow -- ApplicationFlowCriteria : applicationFlowCriteria
SdWanUni -- L2Interface : l2Interface
SdWanUni -- Ipv4ConnectionAddressing : ipv4ConnectionAddressing
SdWanUni -- Ipv6ConnectionAddressing : ipv6ConnectionAddressing
SdWanUni -- "0..*" SwVcEndPointRef : swVcEndPoint
SwVcEndPoint -- "0..*" PolicyMap : policyMap
SwVcEndPoint -- SwVcRef : swvc
SwVcEndPoint -- SdWanUniRef : sdWanUni
ApplicationFlowCriteria -- "0..*" Ipv4Prefix : ipv4SourceAddress
ApplicationFlowCriteria -- "0..*" Ipv4Prefix : ipv4DestinationAddress
ApplicationFlowCriteria -- "0..*" Ipv4Prefix : ipv4SourceOrDestinationAddress
ApplicationFlowCriteria -- "0..*" Ipv6Prefix : ipv6SourceAddress
ApplicationFlowCriteria -- "0..*" Ipv6Prefix : ipv6DestinationAddress
ApplicationFlowCriteria -- "0..*" Ipv6Prefix : ipv6SourceOrDestinationAddress
ApplicationFlowCriteria -- "0..*" ApplicationIdentifier : applicationIdentifier
PolicyMap -- "0..*" ApplicationFlow : applicationFlow
PolicyMap -- "0..*" ApplicationFlowGroup : applicationFlowGroup
PolicyMap -- Policy : policy
ServiceUptimeObjective -- TimeAndDate : startTime
ServiceUptimeObjective -- Period : period
ApplicationFlowGroup -- "0..*" ApplicationFlow : applicationFlows
Ipv4ConnectionAddressing -- "0..*" Ipv4Subnet : ipv4PrimarySubnet
Ipv4ConnectionAddressing -- "0..*" Ipv4Subnet : ipv4SecondarySubnetList
Ipv4Subnet -- Ipv4Prefix : ipv4Prefix
Ipv6ConnectionAddressing -- "0..*" Ipv6Subnet : ipv6SubnetList
Ipv6Subnet -- Ipv6Prefix : ipv6Prefix

@enduml