@startuml
title MEF Carrier Cantata Ethernet Product Order Flow

entity CAC_Listener
participant SP_BA

participant P_BA
entity P_BA_Hub

== Sonata Product Order Provisioning ==

activate SP_BA#LightGray
activate P_BA #LightGray
SP_BA -> CAC_Listener: <<listenerCreate>> ()
SP_BA -> P_BA: POST /hub (listener, filterQuery)
P_BA -> P_BA_Hub: <<hubCreate>> (listener, filterQuery)

== Requests ==


group Envelope
    SP_BA->SP_BA: <<ProductOrderCreate>>
        group Set ProductOrderCreate Attributes
            SP_BA->SP_BA: <<poc attributes: description,note,projectId,relatedContactInformation,etc.>>
        end
    SP_BA->SP_BA: <<MEFProductOrderItemCreate>>
    SP_BA->SP_BA: <<MEFProductActionType.ADD>>
end

group Payload
    SP_BA->SP_BA: <<OperatorUNIOrderV100>>
    SP_BA->SP_BA: <<operatorUNI attribute: ingressBwp,egressBwp,etc.>>

end 

SP_BA->SP_BA: <<MEFProductRefOrValueForOrder>>
SP_BA->SP_BA: <<setProductConfiguration(OperUNIOrderV100)>>
SP_BA->SP_BA: <<addProductOrderItemItem(OperUNIOrderV100)>>


SP_BA -> P_BA: POST /productOrder ()
P_BA -> SP_BA: 200 OK
P_BA -> P_BA_Hub: <<eventUpdate:productOrderActivation>>
P_BA_Hub -> CAC_Listener: POST /listener/productOrderCreated


deactivate SP_BA #LightGray
deactivate P_BA #LightGray

@enduml