@startuml
title Hub Subscription & Notification Flow
entity Listener
actor BUS
participant SOF
entity Hub
entity Service as "ServiceSpecification | ServiceOrder | Service"

activate BUS #LightGray
create Listener
BUS -> Listener : <<configure>>
BUS -> SOF: hubCreate (listener, filterQuery)

activate SOF #LightCyan
alt success
    create Hub
    SOF -> Hub: <<create>>
    SOF --> BUS: 204 : CompletedResponse
else invalidRequest
    SOF --> BUS: 40x/50x : ErrorResponse
end
deactivate BUS
deactivate SOF

Service --> Service : internalProcessing
activate Service #LightSkyBlue
Service -> Hub : create|delete|change Event
activate Hub #LightSeaGreen
Hub -> Listener : callbackListener (Notification.event)
activate Listener #LightSeaGreen
note over SOF
**event**: ServiceSpecificationCreate
           ServiceSpecificationDelete
           ServiceSpecificationChange
           ServiceOrderCreate
           ServiceOrderAttributeValueChange
           ServiceOrderStateChange
           ServiceOrderItemStateChange
           ServiceCreate
           ServiceDelete
           ServiceAttributeValueChange
           ServiceStateChange 
end note
return acknowledge(listener.id)

@enduml