@startuml

hide empty description

state Designed : Resources have been identified/allocated 
state Reserved : Resources have been reserved/blocked
state Inactive : Resources have been provisioned\nbut Service is not yet ready
state Active : Resources have been activated and\nService is ready for use
state Terminated : Service is shut down

note "initialState = FeasibilityChecked" as n1
[*] --> Designed : designService
[*] --> Reserved : reserveService
[*] --> Inactive : provisionService
[*] --> Active : activateService

Designed -> Reserved : reserveService
Designed --> Inactive : provisionService
Designed --> Active : activateService

Reserved -> Designed : designService
Reserved --> Inactive : provisionService
Reserved --> Active : activateService

Inactive -right-> Active : activateService
Inactive --> Terminated : terminateService

Active -left-> Inactive : deactivateService
Active --> Terminated : terminateService


Terminated --> [*] : retireService
Designed --> [*] : cancelService
Reserved --> [*] : cancelService

@enduml