@startuml
title Service Termination & Cancellation Flow
actor BUS
participant SOF
entity ServiceOrder
entity Service
entity Hub

BUS -> SOF: serviceOrderCreate
activate BUS #LightGray
activate SOF #LightSlateGray
SOF -> SOF : validateRequest
alt orderAccepted
    create ServiceOrder
    SOF -> ServiceOrder: <<create>>
    SOF --> BUS: 201 : CompletedResponse
else invalidRequest
    SOF --> BUS: 40x/50x : ErrorResponse
end
deactivate BUS
deactivate SOF

SOF -> SOF : onSchedule
activate SOF #LightCyan
SOF ->> ServiceOrder : processOrder
activate ServiceOrder #LightBlue
deactivate SOF

loop OrderItems 
    ServiceOrder ->> ServiceOrder : processOrderItem
    activate ServiceOrder #LightSeaGreen
    note over ServiceOrder #LightSeaGreen : OrderItem
    opt Action.modify
        ServiceOrder -> Service : configure (state, properties)
        note right
            **state**: Terminate
        end note
        activate Service #LightSkyBlue
        Service ->>] : deprovisionResources
        Service -> Service : updateState
        Service -> Hub : changeEvent
        deactivate Service
    activate Hub #aqua
    end
    
    Hub -> BUS : notifyListeners (ServiceChange)
    deactivate Hub

    opt Action.delete
        ServiceOrder -> Service : retire|cancel
        activate Service #LightCoral
        Service -> Hub : deleteEvent
        destroy Service
        activate Hub #aqua
    end
    Hub -> BUS : notifyListeners (ServiceDelete)
    deactivate Hub

    ServiceOrder -> ServiceOrder : updateState
    ServiceOrder -> Hub : changeEvent
    deactivate ServiceOrder
    activate Hub #aqua
end

Hub -> BUS : notifyListeners (ServiceOrderItemStateChange)
deactivate Hub

ServiceOrder -> ServiceOrder : updateState
ServiceOrder -> Hub : changeEvent
deactivate ServiceOrder

activate Hub #aqua
Hub -> BUS : notifyListeners (ServiceOrderStateChange)
deactivate Hub

@enduml