@startuml

actor BUS

rectangle SOF:NotificationHub {
    usecase subscribeForEvents
    usecase notifyListeners
}

rectangle SOF:ServiceConfiguration {
    left to right direction
    usecase designService
    usecase reserveService
    usecase provisionService
    usecase activateService
    usecase deactivateService
    usecase amendService
}

rectangle SOF:ServiceTermination {
    left to right direction
    usecase terminateService
    usecase retireService
    usecase cancelService
}

rectangle SOF:InventoryQuery {
    usecase queryServiceInventory
    usecase queryServiceCatalog
    usecase queryServiceOrdering
}

BUS <-up- notifyListeners
BUS -up-> subscribeForEvents
BUS -up-> queryServiceInventory
BUS -up-> queryServiceCatalog
BUS -up-> queryServiceOrdering

BUS -down-> designService
BUS -down-> reserveService
BUS -down-> provisionService
BUS -down-> activateService
BUS -down-> deactivateService
BUS -down-> amendService
BUS -down-> terminateService
BUS -down-> retireService
BUS -down-> cancelService

@enduml