@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class CarrierEthernetExternalInterface {
    administrativeState: AdminState[1]
    operationalState: OperationalState[1]
    externalInterfaceFrameFormat: EthernetFrameFormat[1]
    linkOam: EnabledDisabled[1]
    l2cpPeering: L2cpPeering[*]
    lagLinkMeg: EnabledDisabled[1]
    aggregationLinkMap: ConversationIdToAggegationLinkMap[*]
    maxmimumFrameSize: PositiveInteger[1]
    linkAggregation: LinkAggregation[1]
    meg: EnabledDisabled[1]
}

abstract class CarrierEthernetUni {
    maximumNumberOfEndPoints: PositiveInteger[1]
    maximumNumberOfCtagVlanIdsPerEndPoint: PositiveInteger[1]
    tokenShare: EnabledDisabled[1]
    envelopes: Envelope[*]
    l2cpAddressSet: L2cpAddressSet[1]
}

class CarrierEthernetSubscriberUni {
    "...attributes are not shown"
}

class CarrierEthernetOperatorUni {
    "...attributes are not shown"
}

class CarrierEthernetEnni {
    "...attributes are not shown"
}

CarrierEthernetExternalInterface <|-- CarrierEthernetUni
CarrierEthernetExternalInterface <|-- CarrierEthernetEnni
CarrierEthernetUni <|-- CarrierEthernetSubscriberUni
CarrierEthernetUni <|-- CarrierEthernetOperatorUni

@enduml