@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetEvcEndPoint {
    identifier: String[1]
    role: Role[1]
    map: EvcEndPointMap[0..*]
    ingressCosMap: CosMap[0..*]
    colorMap: ColorIdentifier[0..*]
    egressMap: EvcEpEgressMap[0..1]
    ingressBwp: IngressBwpFlow[0..1]
    cosIngressBwp: IngressBandwidthProfilePerClassOfServiceName[0..*]
    egressBwp: EgressBwpFlow[0..1]
    cosEgressBwp: EgressBandwidthProfilePerClassOfServiceName[0..*]
    sourceMacAddressLimit: SourceMacAddressLimit[0..1]
    subscriberMegMip: MegLevel[0..1]
}

enum Role {
    ROOT
    LEAF
}

MefServiceConfiguration <|-- CarrierEthernetEvcEndPoint
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml