@startjson
{
  "timeInterval" : {
    "number" : 1,
    "unit" : "month"
  },
  "startTime" : {
    "offset" : {
      "totalSeconds" : 0,
      "id" : "Z",
      "rules" : {
        "fixedOffset" : true,
        "transitions" : [ ],
        "transitionRules" : [ ]
      }
    },
    "year" : 2017,
    "monthValue" : 2,
    "dayOfMonth" : 3,
    "hour" : 12,
    "minute" : 30,
    "second" : 30,
    "nano" : 0,
    "dayOfWeek" : "FRIDAY",
    "dayOfYear" : 34,
    "month" : "FEBRUARY"
  },
  "slsCosNameEntry" : [ {
    "cosName" : "Gold",
    "deltaT" : 10,
    "consecutiveIntervalN" : 5,
    "oneWayFrameDelayPmMetric" : [ {
      "orderedPairList" : [ {
        "toUni" : "b",
        "fromUni" : "a"
      }, {
        "toUni" : "b",
        "fromUni" : "a"
      } ]
    }, {
      "orderedPairList" : [ {
        "toUni" : "c",
        "fromUni" : "a"
      }, {
        "toUni" : "a",
        "fromUni" : "c"
      }, {
        "toUni" : "c",
        "fromUni" : "b"
      }, {
        "toUni" : "a",
        "fromUni" : "c"
      } ],
      "oneWayFdPercentile" : 95,
      "oneWayFdObjective" : {
        "number" : 40,
        "unit" : "milliSeconds"
      }
    } ],
    "oneWayInterFrameDelayVariationPmMetric" : null,
    "oneWayMeanFrameDelayPmMetric" : null,
    "oneWayFrameLossRatioPmMetric" : null,
    "oneWayMeanFrameDelayRangePmMetric" : null,
    "oneWayAvailabilityPmMetric" : null,
    "oneWayHighLossIntervalPmMetric" : null,
    "oneWayConsecutiveHighLossIntervalsPmMetric" : null,
    "oneWayCompositePmMetric" : null,
    "oneWayGroupAvailabilityPmMetric" : null
  }, {
    "cosName" : "Silver",
    "deltaT" : 1,
    "consecutiveIntervalN" : 1,
    "oneWayFrameDelayPmMetric" : null,
    "oneWayInterFrameDelayVariationPmMetric" : null,
    "oneWayMeanFrameDelayPmMetric" : null,
    "oneWayFrameLossRatioPmMetric" : null,
    "oneWayMeanFrameDelayRangePmMetric" : null,
    "oneWayAvailabilityPmMetric" : null,
    "oneWayHighLossIntervalPmMetric" : null,
    "oneWayConsecutiveHighLossIntervalsPmMetric" : null,
    "oneWayCompositePmMetric" : null,
    "oneWayGroupAvailabilityPmMetric" : null
  } ]
}
@endjson