@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class CarrierEthernetSls {
    "...attributes are not shown"
}

class SlsCosNameEntry {
    "...attributes are not shown"
}

class OneWayFrameDelayPmMetric {
    "...attributes are not shown"
}

class OneWayFrameDelayRangePmMetric {
    "...attributes are not shown"
}

class OneWayFrameLossRatioPmMetric {
    "...attributes are not shown"
}

class OneWayHighLossIntervalsPmMetric {
    "...attributes are not shown"
}

class OneWayCompositePmMetric {
    "...attributes are not shown"
}

class OneWayMeanFrameDelayPmMetric {
    "...attributes are not shown"
}

class OneWayInterFrameDelayVariationPmMetric {
    "...attributes are not shown"
}

class OneWayAvailabilityPmMetric {
    "...attributes are not shown"
}

class OneWayConsecutiveHighLossIntervalsPmMetric {
    "...attributes are not shown"
}

class OrderedPair {
    "...attributes are not shown"
}

class SetOfOrderedPairs {
    "...attributes are not shown"
}

class OneWayGroupAvailabilityPmMetric {
    "...attributes are not shown"
}

class CarrierEthernetServiceEndPoint {
    "...attributes are not shown"
}

CarrierEthernetSls "1" *-->"1..*" SlsCosNameEntry
SlsCosNameEntry "1" *-->"*" OneWayFrameDelayPmMetric
SlsCosNameEntry "1" *-->"*" OneWayFrameDelayRangePmMetric
SlsCosNameEntry "1" *-->"*" OneWayFrameLossRatioPmMetric
SlsCosNameEntry "1" *-->"*" OneWayHighLossIntervalsPmMetric
SlsCosNameEntry "1" *-->"*" OneWayCompositePmMetric
SlsCosNameEntry "1" *-->"*" OneWayMeanFrameDelayPmMetric
SlsCosNameEntry "1" *-->"*" OneWayInterFrameDelayVariationPmMetric
SlsCosNameEntry "1" *-->"*" OneWayAvailabilityPmMetric
SlsCosNameEntry "1" *-->"*" OneWayConsecutiveHighLossIntervalsPmMetric
SlsCosNameEntry "1" *-->"*" OneWayGroupAvailabilityPmMetric

OneWayFrameDelayPmMetric "1" *-->"1..*" OrderedPair
OneWayFrameDelayRangePmMetric "1" *-->"1..*" OrderedPair
OneWayFrameLossRatioPmMetric "1" *-->"1..*" OrderedPair
OneWayHighLossIntervalsPmMetric "1" *-->"1..*" OrderedPair
OneWayCompositePmMetric "1" *-->"1..*" OrderedPair
OneWayMeanFrameDelayPmMetric "1" *-->"1..*" OrderedPair
OneWayInterFrameDelayVariationPmMetric "1" *-->"1..*" OrderedPair
OneWayAvailabilityPmMetric "1" *-->"1..*" OrderedPair
OneWayHighLossIntervalsPmMetric "1" *-->"1..*" OrderedPair

OneWayGroupAvailabilityPmMetric "1" *-->"1..*" SetOfOrderedPairs
SetOfOrderedPairs "1" *-->"1..*" OrderedPair
OrderedPair "*" -->"1..*" CarrierEthernetServiceEndPoint
OrderedPair "*" -->"1..*" CarrierEthernetServiceEndPoint

@enduml