@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetVirtualUni {
    identifier: String[1]
    sVlanId: VlanId[1]
    defaultEnniCeVlanId: VlanId[1]
    maximumNumberOfOvcEndPoints: Integer[1]
    maximumNumberOfEnniCeVlanIdsPerOvcEndPoint: Integer[1]
    ingressBandwidthProfile: IngressBwpFlow[0..1]
    egressBandwidthProfile: EgressBwpFlow[0..1]
    l2cpAddressSet: L2cpAddressSet[0..1]
    l2cpPeering: L2cpPeering[0..*]
    mepList: MepLevelAndDirection[0..*]
}


MefServiceConfiguration <|-- CarrierEthernetVirtualUni
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml