@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetOvcEndPoint {
    identifier: String[1]
    epType: String[1]
    role: String[1]
    endPointMap: OvcEndPointMapi[1]
    classOfServiceIdentifier: CosMap[1]
    colorIdentifier: ColorIdentifier[1]
    egressMap: OvcEpEgressMap[0..*]
    equivalenceClassIdentifier: EecMap[1]
    ingressBwp: IngressBwpFlow[0..1]
    egressBwp: EgressBwpFlow[0..1]
    cosIngressBwp: IngressBandwidthProfilePerClassOfServiceName[0..*]
    egressBwpPerEec: BandwidthProfilePerEquivalenceClassName[0..*]
    aggregationLinkDepth: AggLinkDepth[1]
    sourceMacAddressLimit: SourceMacAddressLimit[0..1]
    mip: EnabledDisabled[1]
    maintenanceEndPointList: MepLevelAndDirection[1]
}


MefServiceConfiguration <|-- CarrierEthernetOvcEndPoint
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml