@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetEnni {
    peeringIdentifier: String[1]
    physicalLayer: CarrierEthernetPhysicalLayer[1..*]
    frameFormat: EthernetFrameFormat[1]
    numberOfLinks: Integer[1]
    linkAggregation: LinkAggregation[1]
    aggregationLinkMap: ConversationToAggregationLinkMap[0..*]
    meg: EnabledDisabled[1]
    lagLinkMeg: EnabledDisabled[1]
    linkOam: EnabledDisabled[1]
    l2cpPeering: L2cpPeering[0..*]
    taggegdL2cpFrameProcessing: TaggedL2cpProcessing[0..1]
    enniMaximumFrameSize: Integer[1]
    enniService: CarrierEthernetEnniService[1..*]
}

class CarrierEthernetEnniService {
    operatorEnniIdentifier: String[1]
    svlanIdControl: SvlanIdControl[1]
    maximumNumberOfOvcs: Integer[1]
    maximumNumberOfOvcEndPointsPerOvc: Integer[1]
    tokenShare: EnabledDisabled[1]
    envelopes: Envelope[0..*]
}

MefServiceConfiguration <|-- CarrierEthernetEnni
CarrierEthernetEnni "1" *--> "1..*" CarrierEthernetEnniService
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml