@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class CarrierEthernetEvc {
    identifier: String[1]
    evcType: ConnectionType[1]
    frameDisposition: FrameDisposition[1]
    cTagPcpPreservation: EnabledDisabled[1]
    cTagDeiPreservation: EnabledDisabled[1]
    listOfCosNames: String[1..*]
    carrierEthernetServiceLevelSpecification: CarrierEthernetServiceLevelSpecification[0..*]
    groupMembership: GroupMembership[0..1]
    maximumFrameSize: Integer[1]
    availableMegLevel: MegLevel[1]
}

enum ConnectionType {
    POINT_TO_POINT
    MULTIPOINT
    ROOTED_MULTIPOINT
}

MefServiceConfiguration <|-- CarrierEthernetEvc
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml