@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
set namespaceSeparator none

class MefServiceRefOrValueOrder{

    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationshipWithGrouping
   
}


class MefServiceConfiguration {
    @type*: string <<discriminator>>
}


MefServiceRefOrValueOrder *-->"0..1" MefServiceConfiguration : serviceConfiguration

class urn:mef:lso:spec:service:carrier-ethernet-operator-uni:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-operator-uni:v0.0.4:order"


class urn:mef:lso:spec:service:carrier-ethernet-ovc:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-ovc:v0.0.4:order"

class urn:mef:lso:spec:service:carrier-ethernet-ovc-end-point:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-ovc-end-point:v0.0.4:order"

class urn:mef:lso:spec:service:carrier-ethernet-enni:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-enni:v0.0.4:order"

class urn:mef:lso:spec:service:carrier-ethernet-enni-service:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-enni-service:0.0.4:order"

class urn:mef:lso:spec:service:carrier-ethernet-virtual-uni:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-virtual-uni:v0.0.4:order"


@enduml