@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
set namespaceSeparator none

class ServiceValue{
    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationshipWithGrouping
    <<...attributes are skipped...>>
}


class MefServiceConfiguration {
    @type*: string <<discriminator>>
}


ServiceValue "1"*-->"0..1" MefServiceConfiguration : serviceConfiguration

class urn:mef:lso:spec:service:carrier-ethernet-subscriber-uni:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-subscriber-uni:v0.0.4:order"



class urn:mef:lso:spec:service:carrier-ethernet-evc:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-evc:v0.0.4:order"

class urn:mef:lso:spec:service:carrier-ethernet-evc-end-point:v0.0.4:order <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
}
MefServiceConfiguration <|-- "urn:mef:lso:spec:service:carrier-ethernet-evc-end-point:v0.0.4:order"

@enduml
