@startuml cancelPerformanceJobModel

class CancelPerformanceJob {

    creationDate*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
CancelPerformanceJob_Create <|-- CancelPerformanceJob



class CancelPerformanceJob_Create {

}

CancelPerformanceJob_Create *-->"1" PerformanceJobRef : performanceJob


enum PerformanceJobProcessStateType {

    acknowledged
    completed
    inProgress
    rejected
}

@enduml