@startuml cancelPerformanceJobModel

class CancelPerformanceJob {

    cancellationDeniedReason: string
    creationDate*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
CancelPerformanceJob_Common <|-- CancelPerformanceJob



class CancelPerformanceJob_Common {

    cancellationReason: string
}

CancelPerformanceJob *-->"1" PerformanceJobRef : performanceJob


class CancelPerformanceJob_Create {
    performanceJobId*: string
}
CancelPerformanceJob_Common <|-- CancelPerformanceJob_Create

enum PerformanceJobProcessStateType {

    acknowledged
    completed
    inProgress
    rejected
}

@enduml