@startuml extensionPattern
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecificConfiguration>> FireBrick
    ClassBorderColor<<ServiceSpecificResult>> FireBrick
}
set namespaceSeparator none

class PerformanceJob {

    id: string 
    href: string 
    jobType: JobType
    reportingPeriod: ReportingPeriod
    scheduleDefinition: ScheduleDefinition
    <<... attributes are skipped ...>>
}


class ServiceSpecificConfiguration {
    @type*: string <<discriminator>>
}


PerformanceJob *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class urn:mef:lso:spec:legato:ip-performance-monitoring-configuration:v0.0.1:all <<ServiceSpecificConfiguration>> {

    <<... attributes are skipped ...>>
}
ServiceSpecificConfiguration <|-- "urn:mef:lso:spec:legato:ip-performance-monitoring-configuration:v0.0.1:all"



class PerformanceReport {

    id: string 
    href: string 
    <<... attributes are skipped ...>>
}

class ReportContentPerMonitoredObject { 
    monitoredObject: MonitoredObjectRef
}

class ReportContentItem {

}
class ServiceSpecificResult {
    @type*: string <<discriminator>>
}

PerformanceReport *-->"*" ReportContentPerMonitoredObject : reportContent
ReportContentPerMonitoredObject *-->"*" ReportContentItem : reportContentItem
ReportContentItem -->"*" ServiceSpecificResult : measurementDataPoints

class urn:mef:lso:spec:legato:ip-performance-monitoring-results:v0.0.1:all <<ServiceSpecificResult>> {

    <<... attributes are skipped ...>>
}
ServiceSpecificResult <|-- "urn:mef:lso:spec:legato:ip-performance-monitoring-results:v0.0.1:all"


@enduml