@startuml modifyPerformanceJobModel

class ModifyPerformanceJob {

    creationDate*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
ModifyPerformanceJob_Create <|-- ModifyPerformanceJob

class ModifyPerformanceJob_Create {

    buyerJobId: string
    consumingApplicationId: string
    description: string
    producingApplicationId: string
}

ModifyPerformanceJob_Create *-l->"1" PerformanceJobRef : performanceJob
ModifyPerformanceJob_Create *--> PerformanceProfileValue_Modify : performanceProfile
ModifyPerformanceJob_Create *--> ScheduleDefinition : scheduleDefinition

class PerformanceProfileValue_Modify {

    jobPriority: integer
    outputFormat: OutputFormat
    resultFormat: ResultFormat
}

PerformanceProfileValue_Modify *--> TimeDuration : granularity
PerformanceProfileValue_Modify *--> TimeDuration : reportingPeriod
PerformanceProfileValue_Modify *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

enum PerformanceJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
}

@enduml