@startuml modifyPerformanceJobModel

class ModifyPerformanceJob {

    creationDate*: date-time
    href: string
    id*: string
    modificationDeniedReason: string
    state*: PerformanceJobProcessStateType
}
ModifyPerformanceJob_Common <|-- ModifyPerformanceJob

class ModifyPerformanceJob_Common {

    buyerJobId: string
    consumingApplicationId: string
    description: string
    modificationReason: string
    producingApplicationId: string
}

ModifyPerformanceJob_Common *-->"0..1" ModifyPerformanceJob_PerformanceProfileValue : performanceProfile
ModifyPerformanceJob_Common *-u->"0..1" ScheduleDefinition : scheduleDefinition
ModifyPerformanceJob_Common *-u->"0..1" ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes

ModifyPerformanceJob *-d->"1" PerformanceJobRef : performanceJob

class ModifyPerformanceJob_Create {
    performanceJobId*: string

}
ModifyPerformanceJob_Common <|-l- ModifyPerformanceJob_Create

class ModifyPerformanceJob_PerformanceProfileValue {

    granularity: Interval
    jobPriority: integer
    outputFormat: OutputFormat
    reportingPeriod: Interval
    resultFormat: ResultFormat
}

enum PerformanceJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
}

@enduml