@startuml performanceMonitoringDataModelPart3
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class PerformanceProfile {

    creationDate*: date-time
    href: uri
    id*: string
    isAssigned*: boolean
    lastModifiedDate: date-time
}
PerformanceProfile_Create <|-- PerformanceProfile

class PerformanceProfileRef {

    performanceProfileHref: string
    performanceProfileId*: string
    @type*: string
}



class PerformanceProfileRefOrValue {

}



class PerformanceProfileRefOrValue_Query {

}



class PerformanceProfileValue {

    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    @type*: string
}

PerformanceProfileValue *-->"1" TimeDuration : granularity
PerformanceProfileValue *-->"1" TimeDuration : reportingPeriod
PerformanceProfileValue *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration




class PerformanceProfileValue_Query {

    jobPriority: integer
    jobType: JobType
    outputFormat: OutputFormat
    resultFormat: ResultFormat
    @type*: string
}

PerformanceProfileValue_Query *--> TimeDuration : granularity
PerformanceProfileValue_Query *--> TimeDuration : reportingPeriod
PerformanceProfileValue_Query *--> ServiceSpecificConfiguration : serviceSpecificConfiguration


class PerformanceProfile_Create {

    description: string
    jobPriority: integer
    jobType*: JobType
    lifecycleStatus*: PerformanceProfileLifecycleStatusType
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

PerformanceProfile_Create *-->"1" TimeDuration : granularity
PerformanceProfile_Create *-u->"1" TimeDuration : reportingPeriod
PerformanceProfile_Create *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration


class PerformanceProfile_Update {

    description: string
    jobPriority: integer
    lifecycleStatus: PerformanceProfileLifecycleStatusType
    outputFormat: OutputFormat
    resultFormat: ResultFormat
}

PerformanceProfile_Update *--> TimeDuration : granularity
PerformanceProfile_Update *--> TimeDuration : reportingPeriod
PerformanceProfile_Update *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

enum PerformanceProfileLifecycleStatusType {

    approved
    deprecated
    experimental
    pending
}



@enduml