@startuml performanceReportModel

class PerformanceReport {

    creationDate*: date-time
    failureReason: string
    href: uri
    id*: string
    lastModifiedDate: date-time
    state*: PerformanceReportStateType
}
PerformanceReport_Create <|-- PerformanceReport

PerformanceReport *--> PerformanceJobRef : performanceJob
PerformanceReport *-->"*" ReportContentPerMonitoredObject : reportContent
PerformanceReport *-u-> AttachmentURL : reportUrl

class PerformanceReport_Create {

    description: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

PerformanceReport_Create *-u->"1" TimeDuration : granularity
PerformanceReport_Create *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Create *-->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Create *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class ReportContentPerMonitoredObject {

}

ReportContentPerMonitoredObject *-->"1" MonitoredObjectRef : monitoredObject
ReportContentPerMonitoredObject *-->"0..*" ReportContentItem : reportContentItem

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"1..*" ResultPayload : measurementDataPoints

class ResultPayload {

    @type*: string
}

enum PerformanceReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}


@enduml