@startuml performanceJobComplexQueryModel


class PerformanceJobComplexQuery_Create {

    buyerJobId: string
    consumingApplicationId: string
    creationDate.gt: date-time
    creationDate.lt: date-time
    producingApplicationId: string
    state: PerformanceJobStateType
}

PerformanceJobComplexQuery_Create *-l-> "0..1" MonitoredObjectRef : monitoredObject
PerformanceJobComplexQuery_Create *--> "0..1" PerformanceProfileRefOrValue_Query : performanceProfile
PerformanceJobComplexQuery_Create *-u-> "0..1" ScheduleDefinition : scheduleDefinition

class PerformanceProfileRefOrValue_Query {

}

class PerformanceProfileValue_Query {

    granularity: TimeDuration
    jobPriority: integer
    jobType: JobType
    outputFormat: OutputFormat
    reportingPeriod: TimeDuration
    resultFormat: ResultFormat
    serviceSpecificConfiguration: ServiceSpecificConfiguration
    @type*: string
}

class PerformanceProfileRef {

    performanceProfileHref: string
    performanceProfileId*: string
    @type*: string
}

PerformanceProfileRefOrValue_Query <|-- PerformanceProfileRef
PerformanceProfileRefOrValue_Query <|-- PerformanceProfileValue_Query

enum PerformanceJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

class MonitoredObjectRef {

}

class EntityRef {

    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceFromToRef {

    serviceFrom*: object
    serviceTo*: object
    @type*: string
}



class ServiceRef {

    serviceHref: string
    serviceId*: string
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

@enduml