@startuml performanceProfileModel

class PerformanceProfile {

    creationDate*: date-time
    href: uri
    id*: string
    lastModifiedDate: date-time
    state*: PerformanceProfileStateType
}

PerformanceProfile_Common <|-- PerformanceProfile


enum PerformanceProfileStateType {
    active
    deleted
}
class PerformanceProfile_Common {
    description: string
    granularity*: Interval
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    reportingPeriod*: Interval
    resultFormat*: ResultFormat
}


class PerformanceProfile_Create {

}

PerformanceProfile_Common <|-- PerformanceProfile_Create

@enduml