@startuml performanceMonitoringDataModelPart1a
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class PerformanceJob {

    creationDate*: date-time
    href: uri
    id*: string
    lastModifiedDate: date-time
    rejectionReason: string
    state*: PerformanceJobStateType
}
PerformanceJob_Create <|-- PerformanceJob




enum PerformanceJobStateType {
    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

class PerformanceJob_Create {

    buyerJobId: string
    consumingApplicationId: string
    description: string
    producingApplicationId: string
}

PerformanceJob_Create *-->"1" MonitoredObjectRef : monitoredObject
PerformanceJob_Create *-->"1" PerformanceProfileRefOrValue : performanceProfile
PerformanceJob_Create *-->"1" ScheduleDefinition : scheduleDefinition


@enduml