@startuml performanceProfileStates

'skinparam Linetype polyline
'skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

''' diagram'''
[*] -d-> active

active -d-> active: Modify

active --> deleted: Delete

deleted -d-> [*]

@enduml