@startuml performanceMonitoringDataModelPart4
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class PerformanceReport {

    creationDate*: date-time
    failureReason: string
    href: uri
    id*: string
    lastModifiedDate: date-time
    state*: PerformanceReportStateType
}
PerformanceReport_Create <|-- PerformanceReport

PerformanceReport *--> PerformanceJobRef : performanceJob
PerformanceReport *-->"*" ReportContentPerMonitoredObject : reportContent
PerformanceReport *--> AttachmentURL : reportUrl

class PerformanceJobRef {

    performanceJobHref: string
    performanceJobId*: string
}

class PerformanceReportComplexQuery_Create {

    creationDate.gt: date-time
    creationDate.lt: date-time
    outputFormat: OutputFormat
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: PerformanceReportStateType
}

PerformanceReportComplexQuery_Create *--> TimeDuration : granularity
PerformanceReportComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
PerformanceReportComplexQuery_Create *--> PerformanceJobRef : performanceJob
PerformanceReportComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration


enum PerformanceReportStateType {

    acknowledged
    completed
    failed
    inProgress
    rejected
}
class PerformanceReport_Create {

    description: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

PerformanceReport_Create *-->"1" TimeDuration : granularity
PerformanceReport_Create *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Create *-->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Create *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration


class PerformanceReport_Find {

    creationDate*: date-time
    description: string
    id*: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    state*: PerformanceReportStateType
}

PerformanceReport_Find *-->"1" TimeDuration : granularity
PerformanceReport_Find *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Find *-->"1" PerformanceJobRef : performanceJob
PerformanceReport_Find *-->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Find *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"1..*" ServiceSpecificResult : measurementDataPoint


class ReportContentPerMonitoredObject {

}

ReportContentPerMonitoredObject *-->"1" MonitoredObjectRef : monitoredObject
ReportContentPerMonitoredObject *-->"1..*" ReportContentItem : reportContentItem


class ReportingTimeframe {

    reportingStartDate: date-time
    reportingEndDate: date-time
}


class MeasurementTime {

    measurementStartDate*: date-time
    measurementEndDate: date-time
}

MeasurementTime *--> TimeDuration : measurementInterval


@enduml