@startuml performanceMonitoringDataModelPart2

class PerformanceJob {
    creationDateTime*: date-time
    href: uri
    id*: string
    lastTimeModified: date-time
    state*: PerformanceJobStateType
}
PerformanceJob *-->"*" TerminationError: terminationError

PerformanceJob_Create <|-- PerformanceJob

class PerformanceJob_Create {
    buyerJobId: string
    consumingApplicationId: string
    description: string
    producingApplicationId: string
}

PerformanceJob_Create *-->"1" MonitoredObjectRef : monitoredObject
PerformanceJob_Create *-u->"1" PerformanceProfileRefOrValue : performanceProfile
PerformanceJob_Create *-u->"1" ScheduleDefinition : scheduleDefinition

class TerminationError {
    code: Error422Code
    propertyPath: string
    value: string
}

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {

    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class PerformanceProfileRefOrValue {

}

class PerformanceProfileRef {
    performanceProfileHref: string
    performanceProfileId*: string
    @type*: string
}

class PerformanceProfileValue {
    granularity*: TimeDuration
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    reportingPeriod*: TimeDuration 
    resultFormat*: ResultFormat
    serviceSpecificConfiguration*: ServiceSpecificConfiguration
    @type*: string
}

PerformanceProfileRefOrValue <|-- PerformanceProfileRef
PerformanceProfileRefOrValue <|-- PerformanceProfileValue

class ScheduleDefinition {
    scheduleDefinitionStartTime: date-time
    scheduleDefinitionEndTime: date-time
}

ScheduleDefinition *--> RecurringSchedule : recurringSchedule
ScheduleDefinition *--> TimeDuration : executionDuration

class RecurringSchedule {
    second: string
    minute: string
    hour: string
    dayOfMonth: string
    month: string
    dayOfWeek: string
}

class TimeDuration {
    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}

enum PerformanceJobStateType {
    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

@enduml