@startuml performanceReportModel

class PerformanceReport {

    creationDate*: date-time
    failureReason: string
    href: uri
    id*: string
    lastModifiedDate: date-time
    state*: PerformanceReportStateType
}
PerformanceReport_Common <|-- PerformanceReport


PerformanceReport *-->"0..*" ReportContentItem : reportContent
PerformanceReport *-->"0..1" AttachmentURL : reportUrl

class PerformanceReport_Common {

    description: string
}

PerformanceReport_Common *-->"1" PerformanceJobRefOrValue : performanceJob
PerformanceReport_Common *-->"1" ReportingTimeframe : reportingTimeframe

class PerformanceReport_Create {

}

PerformanceReport_Common <|-- PerformanceReport_Create


enum PerformanceReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"1..*" ResultPayload : measurementDataPoints

class ResultPayload {

    @type*: string
}


@enduml