@startuml performanceReportComplexQueryModel

class PerformanceReportComplexQuery {

    creationDate*: date-time
    description: string
    lastModifiedDate: date-time
    state*: PerformanceReportStateType
}

PerformanceReportComplexQuery *-->"1" PerformanceJobRefOrValue : performanceJob
PerformanceReportComplexQuery *-->"1" PerformanceReportRef : performanceReport
PerformanceReportComplexQuery *-->"1" ReportingTimeframe : reportingTimeframe



class PerformanceReportComplexQuery_Create {

    consumingApplicationId: string
    creationDate.gt: date-time
    creationDate.lt: date-time
    description: string
    granularity: Interval
    lastModifiedDate.gt: date-time
    lastModifiedDate.lt: date-time
    outputFormat: OutputFormat
    performanceJobId: string
    producingApplicationId: string
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: PerformanceReportStateType
}

PerformanceReportComplexQuery_Create *-->"0..1" MonitoredObjectId : monitoredObjectId
PerformanceReportComplexQuery_Create *-->"0..1" ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes


@enduml