@startuml performanceProfileRefOrValue



class PerformanceProfileRefOrValue {

    @type*: string
}



class PerformanceProfileRef {

    href: string
    id*: string
}
PerformanceProfileRefOrValue <|-- PerformanceProfileRef



class PerformanceProfileValue {

    granularity: Interval
    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    reportingPeriod: Interval
    resultFormat*: ResultFormat
}

PerformanceProfileRefOrValue <|-- PerformanceProfileValue

class PerformanceJob {}

class PerformanceJob_Common {}

class PerformanceJob_Find {}

class PerformanceJob_Create {}
PerformanceJob_Common <|-- PerformanceJob_Create

PerformanceJob_Common <|-- PerformanceJob

PerformanceJob_Common *-->"1" PerformanceProfileRefOrValue : performanceProfile

PerformanceJob_Find *-->"1" PerformanceProfileRefOrValue : performanceProfile

@enduml