@startuml performanceMonitoringDataModelPart5

class PerformanceReport {
    creationDateTime*: date-time
    href: uri
    id*: string
    state*: PerformanceReportStateType
    terminationError: TerminationError
}
PerformanceReport_Create <|-- PerformanceReport

PerformanceReport *--> PerformanceJobRef : performanceJob
PerformanceReport *-->"*" ReportContentPerMonitoredObject : reportContent
PerformanceReport *--> AttachmentURL : reportUrl

class PerformanceJobRef {
    performanceJobHref: string
    performanceJobId*: string
    @type*: string
}

class PerformanceReport_Create {
    description: string
    granularity: TimeDuration
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
}

PerformanceReport_Create *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Create *-->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Create *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class ReportContentItem {

}

ReportContentItem *-->"1" MeasurementTime : measurementTime
ReportContentItem *-->"1..*" ServiceSpecificResult : measurementData

class ReportContentPerMonitoredObject {

}

ReportContentPerMonitoredObject *-->"1" MonitoredObjectRef : monitoredObject
ReportContentPerMonitoredObject *-->"1..*" ReportContentItem : reportContentItem

class ReportingTimeframe {
    reportingStartDate: date-time
    reportingEndDate: date-time
}

class MeasurementTime {
    measurementStartDate*: date-time
    measurementEndDate: date-time
    measurementInterval: TimeDuration
}

class AttachmentURL {
    retentionPeriod: date-time
    url*: uri
}

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {
    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class ServiceSpecificConfiguration {
    @type*: string
}

class ServiceSpecificResult {
    @type*: string
}

enum PerformanceReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}

@enduml