@startuml performanceMonitoringDataModelPart4

class CancelPerformanceJob {
    creationDateTime*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
CancelPerformanceJob_Create <|-- CancelPerformanceJob

class CancelPerformanceJob_Create {

}

CancelPerformanceJob_Create *-->"1" PerformanceJobRef : performanceJob

class ModifyPerformanceJob {
    creationDateTime*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
ModifyPerformanceJob_Create <|-- ModifyPerformanceJob

class ModifyPerformanceJob_Create {
    buyerJobId: string
    consumingApplicationId: string
    description: string
    producingApplicationId: string
}

ModifyPerformanceJob_Create *-->"1" PerformanceJobRef : performanceJob
ModifyPerformanceJob_Create *--> PerformanceProfileValue_Modify : performanceProfile
ModifyPerformanceJob_Create *--> ScheduleDefinition : scheduleDefinition

class PerformanceProfileValue_Modify {
    jobPriority: integer
    outputFormat: OutputFormat
    resultFormat: ResultFormat
}

PerformanceProfileValue_Modify *--> TimeDuration : granularity
PerformanceProfileValue_Modify *--> TimeDuration : reportingPeriod
PerformanceProfileValue_Modify *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

class PerformanceJobRef {
    performanceJobHref: string
    performanceJobId*: string
    @type*: string
}

enum PerformanceJobProcessStateType {
    acknowledged
    completed
    inProgress
    rejected
}

@enduml
