@startuml performanceMonitoringDataModelPart1b
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class PerformanceJobComplexQuery_Create {

    buyerJobId: string
    consumingApplicationId: string
    creationDate.gt: date-time
    creationDate.lt: date-time
    producingApplicationId: string
    state: PerformanceJobStateType
}

PerformanceJobComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
PerformanceJobComplexQuery_Create *--> PerformanceProfileRefOrValue_Query : performanceProfile
PerformanceJobComplexQuery_Create *--> ScheduleDefinition : scheduleDefinition


@enduml