@startuml performanceMonitoringDataModelPart5
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class AttachmentURL {

    retentionPeriod: date-time
    url*: uri
}




class EntityRef {

    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class HourRange {

    start*: string
    end*: string
}



enum JobType {

    proactive
    on-demand
    passive
}




class MonitoredObjectRef {

}



enum OutputFormat {

    json
    xml
    avro
    csv
}









class RecurringSchedule {

    second: string
    minute: string
    hour: string
    dayOfMonth: string
    month: string
    dayOfWeek: string
}

RecurringSchedule *-->"*" HourRange : hourRange





enum ResultFormat {

    attachment
    payload
}
class ScheduleDefinition {

    scheduleDefinitionStartTime: date-time
    scheduleDefinitionEndTime: date-time
}

ScheduleDefinition *--> RecurringSchedule : recurringSchedule
ScheduleDefinition *--> TimeDuration : executionDuration


class ServiceFromToRef {

    serviceFrom*: object
    serviceTo*: object
    @type*: string
}



class ServiceRef {

    serviceHref: string
    serviceId*: string
    @type*: string
}



class ServiceSpecificConfiguration {

    @type*: string
}



class ServiceSpecificResult {

    @type*: string
}



class TimeDuration {

    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}



enum TimeDurationUnits {

    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}
class TrackingRecord {

    creationDate*: date-time
    description: string
    id*: string
    relatedObjectId*: string
    request: string
    system: string
    user: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

@enduml