@startuml performanceMonitoringDataModelPart2
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class CancelPerformanceJob {
    cancellationDeniedReason: string
    creationDate*: date-time
    href: string
    id*: string
    state*: PerformanceJobProcessStateType
}
CancelPerformanceJob_Common <|-- CancelPerformanceJob

CancelPerformanceJob *-->"1" PerformanceJobRef : performanceJob

class CancelPerformanceJob_Common {
    cancellationReason: string
}

class CancelPerformanceJob_Create {
    performanceJobId*: string
}
CancelPerformanceJob_Common <|-- CancelPerformanceJob_Create

class CancelPerformanceJob_Find {
    creationDate*: date-time
    id*: string
    state*: PerformanceJobProcessStateType
}

CancelPerformanceJob_Find *-->"1" PerformanceJobRef : performanceJob

class ModifyPerformanceJob {
    creationDate*: date-time
    href: string
    id*: string
    modificationDeniedReason: string
    state*: PerformanceJobProcessStateType
}
ModifyPerformanceJob_Common <|-- ModifyPerformanceJob

ModifyPerformanceJob *-->"1" PerformanceJobRef : performanceJob

class ModifyPerformanceJob_Common {
    buyerJobId: string
    consumingApplicationId: string
    description: string
    modificationReason: string
    producingApplicationId: string
}

ModifyPerformanceJob_Common *--> ModifyPerformanceJob_PerformanceProfileValue : performanceProfile
ModifyPerformanceJob_Common *-u-> ScheduleDefinition : scheduleDefinition
ModifyPerformanceJob_Common *-u-> ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes

class ModifyPerformanceJob_Create {
    performanceJobId: string
}
ModifyPerformanceJob_Common <|-r- ModifyPerformanceJob_Create

class ModifyPerformanceJob_Find {
    creationDate*: date-time
    id*: string
    state*: PerformanceJobProcessStateType
}

ModifyPerformanceJob_Find *-->"1" PerformanceJobRef : performanceJob

class ModifyPerformanceJob_PerformanceProfileValue {
    granularity: Interval
    jobPriority: integer
    outputFormat: OutputFormat
    reportingPeriod: Interval
    resultFormat: ResultFormat
}


@enduml
