@startuml performanceMonitoringDataModelPart6
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Error {
    message: string
    reason*: string
    referenceError: uri
}

class Error400 {
    code*: Error400Code
}
Error <|-l- Error400

enum Error400Code {
    missingQueryParameter
    missingQueryValue
    invalidQuery
    invalidBody
}

class Error401 {
    code*: Error401Code
}
Error <|-l- Error401

enum Error401Code {
    missingCredentials
    invalidCredentials
}

class Error403 {
    code*: Error403Code
}
Error <|-r- Error403

enum Error403Code {
    accessDenied
    forbiddenRequester
    tooManyUsers
}

class Error404 {
    code*: string
}
Error <|-r- Error404

class Error409 {
    code*: string
}
Error <|-u- Error409

class Error422 {
    code*: Error422Code
    propertyPath: string
}
Error <|-u- Error422

enum Error422Code {
    missingProperty
    invalidValue
    invalidFormat
    referenceNotFound
    unexpectedProperty
    tooLargeDataset
    tooManyRecords
    tooManyRequests
    performanceProfileInUse
    otherIssue
}
class Error500 {

    code*: string
}
Error <|-- Error500

class Error501 {
    code*: string
}
Error <|-- Error501

class EventSubscription {
    callback*: string
    id*: string
    query: string
}

class EventSubscriptionInput {
    callback*: string
    query: string
}

@enduml
