@startuml performanceProfileModel

class PerformanceProfile {

    creationDate*: date-time
    href: uri
    id*: string
    isAssigned*: boolean
    lastModifiedDate: date-time
}

PerformanceProfile_Create <|-- PerformanceProfile

class PerformanceProfile_Create {

    description: string
    granularity*: TimeDuration
    jobPriority: integer
    jobType*: JobType
    lifecycleStatus*: PerformanceProfileLifecycleStatusType
    outputFormat*: OutputFormat
    reportingPeriod*: TimeDuration
    resultFormat*: ResultFormat
    serviceSpecificConfiguration*: ServiceSpecificConfiguration
}

enum PerformanceProfileLifecycleStatusType {

    approved
    deprecated
    experimental
    pending
}

@enduml