@startuml performanceJobRefOrValue

class PerformanceJobRefOrValue {
    @type*: string
}

class PerformanceJobRef {

    performanceJobHref: string
    performanceJobId*: string
}
PerformanceJobRefOrValue <|-- PerformanceJobRef

class PerformanceJobValue {

    consumingApplicationId: string
    granularity*: Interval
    outputFormat*: OutputFormat
    producingApplicationId: string
    resultFormat*: ResultFormat
}
PerformanceJobRefOrValue <|-- PerformanceJobValue

PerformanceJobValue *-->"1" MonitoredObjectId : monitoredObjectId
PerformanceJobValue *-->"1" ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes

@enduml