@startuml performanceJobModel

class PerformanceJob {

    creationDate*: date-time
    href: uri
    id*: string
    lastModifiedDate: date-time
    rejectionReason: string
    state*: PerformanceJobStateType
}
PerformanceJob_Create <|-- PerformanceJob

enum PerformanceJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

class PerformanceJob_Create {

    buyerJobId: string
    consumingApplicationId: string
    description: string
    producingApplicationId: string
}

PerformanceJob_Create *-u->"1" MonitoredObjectRef : monitoredObject
PerformanceJob_Create *-->"1" PerformanceProfileRefOrValue : performanceProfile
PerformanceJob_Create *-u->"1" ScheduleDefinition : scheduleDefinition

class PerformanceProfileRefOrValue {

}

class PerformanceProfileRef {

    performanceProfileHref: string
    performanceProfileId*: string
    @type*: string
}

class PerformanceProfileValue {

    jobPriority: integer
    jobType*: JobType
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    @type*: string
}

PerformanceProfileValue *-->"1" TimeDuration : granularity
PerformanceProfileValue *-->"1" TimeDuration : reportingPeriod
PerformanceProfileValue *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

PerformanceProfileRefOrValue <|-- PerformanceProfileRef
PerformanceProfileRefOrValue <|-- PerformanceProfileValue

@enduml