@startuml performanceMonitoringDataModelPart6

class PerformanceReportComplexQuery_Create {
    creationDateTime.gt: date-time
    creationDateTime.lt: date-time
    granularity: TimeDuration
    outputFormat: OutputFormat
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: PerformanceReportStateType
}

PerformanceReportComplexQuery_Create *--> "*" MonitoredObjectRef : monitoredObject
PerformanceReportComplexQuery_Create *--> PerformanceJobRef : performanceJob
PerformanceReportComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

enum PerformanceReportStateType {
    acknowledged
    completed
    failed
    inProgress
    rejected
}

class PerformanceReport_Find {
    creationDateTime*: date-time
    description: string
    granularity*: TimeDuration
    id*: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    state*: PerformanceReportStateType
}

PerformanceReport_Find *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Find *-->"1" PerformanceJobRef : performanceJob
PerformanceReport_Find *-->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Find *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

class MonitoredObjectRef {

}

class EntityRef {
    @referredType*: string
    entityHref: string
    entityId*: string
    @type*: string
}

class ServiceRef {
    serviceHref: string
    serviceId*: string
    @type*: string
}

class ServiceFromToRef {
    serviceFrom*: object
    serviceTo*: object
    @type*: string
}

MonitoredObjectRef <|-- EntityRef
MonitoredObjectRef <|-- ServiceFromToRef
MonitoredObjectRef <|-- ServiceRef

class PerformanceJobRef {
    performanceJobHref: string
    performanceJobId*: string
    @type*: string
}

class ServiceSpecificConfiguration {
    @type*: string
}

class ReportingTimeframe {
    reportingStartDate: date-time
    reportingEndDate: date-time
}

@enduml