@startuml performanceReportComplexQueryModel

class PerformanceReportComplexQuery_Create {

    creationDate.gt: date-time
    creationDate.lt: date-time
    outputFormat: OutputFormat
    reportingTimeframe.startDate.gt: date-time
    reportingTimeframe.startDate.lt: date-time
    reportingTimeframe.endDate.gt: date-time
    reportingTimeframe.endDate.lt: date-time
    resultFormat: ResultFormat
    state: PerformanceReportStateType
}

PerformanceReportComplexQuery_Create *--> TimeDuration : granularity
PerformanceReportComplexQuery_Create *--> MonitoredObjectRef : monitoredObject
PerformanceReportComplexQuery_Create *--> PerformanceJobRef : performanceJob
PerformanceReportComplexQuery_Create *--> ServiceSpecificConfiguration : serviceSpecificConfiguration


@enduml