@startuml pmEntities
autonumber

actor "Buyer/Client" as B

entity PerformanceProfile as PP

entity PerformanceJob as PJ
entity PerformanceReport as PR


B -> PP: POST /performanceProfile request
activate PP
note right of PP: Performance Profile is created 
PP --> B: Created

B -> PP: GET /performanceProfile request
PP --> B: List Performance Profiles

B -> PP: PATCH /performanceProfile/{id} request
note right of PP: Performance Profile is updated
PP --> B: Updated

note over B: Buyer/Client is getting list of Performance Profiles
B -> PP: GET /performanceProfile request

PP --> B: List Performance Profiles

note over B: Buyer/Client is creating \na Performance Job based on \nPerformance Profile
B -> PJ: POST /performanceJob request
activate PJ
PJ --> B: Created

note right of PJ: On scheduled date

PJ -> PJ: state: inProgress

PJ --> PR: (causes report creation)

activate PR

PR -> PR: state: inProgress

PJ -> PR: collect data

PR -> PR: state: completed

PR --> PJ: (report completed)

opt
    PJ -> B: POST /performanceJobReportReadyEvent
end

note right of PJ: non-recurring Job
PJ -> PJ: state: completed

B -> PR: GET /performanceReport
PR --> B: Performance Report content

@enduml