@startuml pmUsecases

left to right direction

actor "Administrator" as A
actor "Buyer/Client" as B
actor "Seller/Server" as S

rectangle {
Usecase UC1 as "1. Create Performance Monitoring Profile"
Usecase UC2 as "2. Retrieve Performance Monitoring Profile List"
Usecase UC3 as "3. Retrieve Performance Monitoring Profile by Profile Identifier"
Usecase UC4 as "4. Modify Performance Monitoring Profile"
Usecase UC5 as "5. Delete Performance Monitoring Profile"
Usecase UC6 as "6. Create Performance Monitoring Job"
Usecase UC7 as "7. Retrieve Performance Monitoring Job List"
Usecase UC8 as "8. Retrieve Performance Monitoring Job by Job Identifier"
Usecase UC9 as "9. Modify Performance Monitoring Job"
Usecase UC10 as "10. Retrieve Modify Performance Monitoring Job List"
Usecase UC11 as "11. Retrieve Modify Performance Monitoring Job List by Identifier"
Usecase UC12 as "12. Cancel Performance Monitoring Job"
Usecase UC13 as "13. Retrieve Cancel Performance Monitoring Job List"
Usecase UC14 as "14. Retrieve Cancel Performance Monitoring Job List by Identifier"
Usecase UC15 as "15. Suspend Performance Monitoring Job"
Usecase UC16 as "16. Retrieve Suspend Performance Monitoring Job List"
Usecase UC17 as "17. Retrieve Suspend Performance Monitoring Job List by Identifier"
Usecase UC18 as "18. Resume Performance Monitoring Job"
Usecase UC19 as "19. Retrieve Resume Performance Monitoring Job List"
Usecase UC20 as "20. Retrieve Resume Performance Monitoring Job List by Identifier"
Usecase UC21 as "21. Create Performance Monitoring Job Complex Query"
Usecase UC22 as "22. Create Performance Measurement Report"
Usecase UC23 as "23. Retrieve Performance Measurement Report List"
Usecase UC24 as "24. Retrieve Performance Measurement Report by Report Identifier"
Usecase UC25 as "25. Create Performance Measurement Report Complex Query"
Usecase UC26 as "26. Retrieve Tracking Record List"
Usecase UC27 as "27. Retrieve Tracking Record List by Identifier"
Usecase UC28 as "28. Register for Event Notifications"
Usecase UC29 as "29. Send Event Notification"
}

A --> UC1
A --> UC2
B --> UC2
A --> UC3
B --> UC3
A --> UC4
A --> UC5
B --> UC6
B --> UC7
B --> UC8
B --> UC9
B --> UC10
B --> UC11
B --> UC12
B --> UC13
B --> UC14
B --> UC15
B --> UC16
B --> UC17
B --> UC18
B --> UC19
B --> UC20
B --> UC21
B --> UC22
B --> UC23
B --> UC24
B --> UC25
B --> UC26
B --> UC27
A --> UC28
B --> UC28
S --> UC29

@enduml