@startuml resumePerformanceJobModel

class ResumePerformanceJob {

    creationDate: date-time
    href: string
    id*: string
    resumptionDeniedReason: string
    state*: PerformanceJobProcessStateType
}
ResumePerformanceJob_Common <|-- ResumePerformanceJob



class ResumePerformanceJob_Common {

    resumptionReason: string
}

ResumePerformanceJob_Common *-->"1" PerformanceJobRef : performanceJob


class ResumePerformanceJob_Create {

}
ResumePerformanceJob_Common <|-- ResumePerformanceJob_Create

enum PerformanceJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
}

@enduml