@startuml trackingRecordModel

class TrackingRecord {

    creationDate*: date-time
    description: string
    id*: string
    relatedObjectId*: string
    request: string
    system: string
    user: string
}

@enduml