@startuml trackingRecordModel

class PmTrackingRecord {
    creationDateTime*: date-time
    description: string
    id*: string
    request: string
    source: string
}

PmTrackingRecord *-->"1" RelatedObjectRef : relatedObjectId

class RelatedObjectRef {

}

class PerformanceProfileRef {
    performanceProfileHref: string
    performanceProfileId*: string
    @type*: string
}

class PerformanceJobRef {
    performanceJobHref: string
    performanceJobId*: string
    @type*: string    
}

class PerformanceReportRef {
    performanceReportHref: string
    performanceReportId*: string
    @type*: string
}

RelatedObjectRef <|-- PerformanceProfileRef
RelatedObjectRef <|-- PerformanceJobRef
RelatedObjectRef <|-- PerformanceReportRef

@enduml