@startuml useCase19Model

class PerformanceReport_Find {

    creationDate*: date-time
    description: string
    id*: string
    outputFormat*: OutputFormat
    resultFormat*: ResultFormat
    state*: PerformanceReportStateType
}

PerformanceReport_Find *-u->"1" TimeDuration : granularity
PerformanceReport_Find *-->"1..*" MonitoredObjectRef : monitoredObject
PerformanceReport_Find *-->"0..1" PerformanceJobRef : performanceJob
PerformanceReport_Find *-u->"1" ReportingTimeframe : reportingTimeframe
PerformanceReport_Find *-->"1" ServiceSpecificConfiguration : serviceSpecificConfiguration

enum PerformanceReportStateType {

    acknowledged
    completed
    failed
    inProgress
    rejected
}

class PerformanceJobRef {

    performanceJobHref: string
    performanceJobId*: string
}

@enduml