@startuml useCase6Polling
hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S


B -> S : POST {{baseUrl}}/performanceJob (PerformanceJob_Create)
S -> S : basic validation

alt succesful inquiry
  S --> B : 201 PerformanceJob with {{id}}, `acknowledged` state
  
  ...

  loop periodically until PerformanceJob in active state
      B -> S :   GET {{baseUrl}}/performanceJob/{{id}}
      return 200 PerformanceJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end


@enduml