@startuml useCase13Model

class CancelPerformanceJob_Find {

    creationDate*: date-time
    id*: string
    state*: PerformanceJobProcessStateType
}

CancelPerformanceJob_Find *-->"1" PerformanceJobRef : performanceJob

enum PerformanceJobProcessStateType {

    acknowledged
    completed
    inProgress
    rejected
}

@enduml