@startuml useCase1Notification

hide footbox

participant Administrator as A
participant SOF

A -> SOF : POST {{baseUrl}}/hub with {{callbackUrl}} details
SOF --> A: 201 confirmation with {{id}}
...
A -> SOF : POST {{baseUrl}}/performanceProfile (PerformanceProfile_Create)
SOF -> SOF : basic validation

alt succesful inquiry
  SOF --> A : 201 PerformanceProfile with {{id}}, `acknowledged` state 
  SOF -> A: {{callbackUrl}}/listener/performanceProfileCreateEvent ({{id}})
  A --> SOF : 204 confirmation

  ...

  group loop [until Performance Profile in terminal state]
      SOF -> A: {{callbackUrl}}/listener/performanceProfileStateChangeEvent ({{id}})
      A --> SOF : 204 confirmation
      A -> SOF :   GET {{baseUrl}}/performanceProfile/{{id}}
      return 200 PerformanceProfile in current state
  end

else validation or internal problem
  SOF --> A : 4xx or 5xx error response
end 

...

A -> SOF : DELETE {{baseUrl}}/hub/{{id}} 
SOF -->  A : 204 confirmation

@enduml