@startuml useCase7Model

class PerformanceJob_Find {

    buyerJobId: string
    consumingApplicationId: string
    creationDate*: date-time
    description: string
    id*: string
    producingApplicationId: string
    state*: PerformanceJobStateType
}

PerformanceJob_Find *-->"1" MonitoredObjectId : monitoredObjectId
PerformanceJob_Find *-->"1" PerformanceProfileRefOrValue : performanceProfile
PerformanceJob_Find *-->"1" ScheduleDefinition : scheduleDefinition

enum PerformanceJobStateType {

    acknowledged
    cancelled
    completed
    inProgress
    pending
    pendingCancel
    rejected
    resourcesUnavailable
    scheduled
    suspended
}

@enduml