@startuml useCase2Model

class PerformanceProfile_Find {

    creationDate*: date-time
    description: string
    granularity*: Interval
    id*: string
    jobPriority: integer
    jobType*: JobType
    reportingPeriod*: Interval
    state*: PerformanceProfileStateType
}

enum Interval {

    10 milliseconds
    100 milliseconds
    1 second
    10 seconds
    1 minute
    5 minutes
    15 minutes
    30 minutes
    1 hour
    24 hours
    1 month
    1 year
}

enum JobType {

    proactive
    on-demand
    passive
}

enum PerformanceProfileStateType {

    active
    deleted
}

@enduml