@startuml useCase19Model

class ResumePerformanceJob_Find {

    creationDate: date-time
    id*: string
    state*: PerformanceJobProcessStateType
}

ResumePerformanceJob_Find *-->"1" PerformanceJobRef : performanceJob

enum PerformanceJobProcessStateType {

    accepted
    acknowledged
    completed
    declined
}

@enduml