@startuml useCase19Model

class PerformanceReport_Find {
    creationDate*: date-time
    description: string
    id*: string
    state*: PerformanceReportStateType
}

PerformanceReport_Find *--> "1" PerformanceJobRefOrValue : performanceJob
PerformanceReport_Find *--> "1" ReportingTimeframe : reportingTimeframe

enum PerformanceReportStateType {

    acknowledged
    completed
    failed
    inProgress
    rejected
}

class PerformanceJobRefOrValue {
    @type*: string
}

class PerformanceJobRef {

    performanceJobHref: string
    performanceJobId*: string
}
PerformanceJobRefOrValue <|-- PerformanceJobRef

class PerformanceJobValue {

    consumingApplicationId: string
    granularity*: Interval
    outputFormat*: OutputFormat
    producingApplicationId: string
    resultFormat*: ResultFormat
}
PerformanceJobRefOrValue <|-- PerformanceJobValue

PerformanceJobValue *-->"1" MonitoredObjectId : monitoredObjectId
PerformanceJobValue *-->"1" ServicePayloadSpecificAttributes : servicePayloadSpecificAttributes


@enduml