@startuml useCase15Notification

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

B -> S: POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
...
B -> S: POST {{baseUrl}}/suspendPerformanceJob (SuspendPerformanceJob_Create)
S -> S: basic validation

alt succesful inquiry
  S --> B: 201 SuspendPerformanceJob with {{id}}, `acknowledged` state 
  ...

  group loop [until Suspend Performance Job in terminal state]
      S -> B: {{callbackUrl}}/listener/suspendPerformanceJobStateChangeEvent ({{id}})
      B --> S: 204 confirmation
      B -> S:   GET {{baseUrl}}/suspendPerformanceJob/{{id}}
      return 200 SuspendPerformanceJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end 

...

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S --> B : 204 confirmation

@enduml