@startuml useCase15


hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

entity "PerformanceJob" as PJ
activate PJ

note over PJ: PerformanceJob in `inProgress`

B -> S : POST {{baseUrl}}/performanceJob/{{id}}/suspend request

S -> S : find PerformanceJob by id
S -> S : check PerformanceJob status
S -> PJ : (causes status change)
PJ -> PJ: status: suspended 

B <-- S : 204 Suspended

opt
    PJ -> B: POST performanceJobStateChangeEvent
end

@enduml