@startuml useCase18


hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

alt Report generated internally by PM Job
  note over S
    The Performance Monitoring Job starts 
    collecting data on a scheduled date.
  end note
  S -> S : collect data
  note over S
    The Performance Monitoring Job 
    internally creates a Performance Report.
  end note
  S -> S : create PerformanceReport
else Report triggered by the request from Buyer/Client
  B -> S : POST {{baseUrl}}/performanceReport (PerformanceReport_Create)
end
S -> S : basic validation
S -> S : assign id
S -> S : state: acknowledged
...
opt Report triggered externally
  alt successful inquiry
    B <-- S : 201 PerformanceReport with {{id}}
  else validation or internal problem
    B <-- S: 4xx/5xx : error response
  end
end

@enduml