@startuml useCase18Polling
hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

alt Report generated internally by PM Job
  S -> S : internal report processing
  B -> S : GET {{baseUrl}}/performanceReport, filter on PerformanceJob id
  S -> B : 200 list of PerformanceReport
else Report triggered externally
  B -> S : POST {{baseUrl}}/performanceReport (PerformanceReport_Create)
  S -> S : internal report processing
  S --> B : 201 PerformanceReport with {{id}}, `acknowledged` state
end

...

loop periodically until PerformanceReport in terminal state
  B -> S :   GET {{baseUrl}}/performanceReport/{{id}}
  return 200 PerformanceReport in current state
end

@enduml