@startuml useCase4PatchModel

class PerformanceProfile_Update {

    description: string
    jobPriority: integer
    lifecycleStatus: PerformanceProfileLifecycleStatusType
    outputFormat: OutputFormat
    resultFormat: ResultFormat
}

PerformanceProfile_Update *--> TimeDuration : granularity
PerformanceProfile_Update *--> TimeDuration : reportingPeriod
PerformanceProfile_Update *--> ServiceSpecificConfiguration : serviceSpecificConfiguration

class TimeDuration {

    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}

enum TimeDurationUnits {

    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}

enum OutputFormat {

    json
    xml
    avro
    csv
}

enum ResultFormat {

    attachment
    payload
}

enum PerformanceProfileLifecycleStatusType {

    approved
    deprecated
    experimental
    pending
}

@enduml