@startuml useCase18Notification

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

B -> S: POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
...

alt Report generated internally by PM Job
  S -> S : internal report processing
else Report triggered externally
  B -> S : POST {{baseUrl}}/performanceReport (PerformanceReport_Create)
  S -> S : internal report processing
  S --> B : 201 PerformanceReport with {{id}}, `acknowledged` state
end

...
S -> B: {{callbackUrl}}/listener/performanceReportCreateEvent ({{id}})
B --> S: 204 confirmation
B -> S:   GET {{baseUrl}}/performanceReport/{{id}}
return 200 PerformanceReport in current state

...

group loop [until Performance Report in terminal state]
    S -> B: {{callbackUrl}}/listener/performanceReportStateChangeEvent ({{id}})
    B --> S: 204 confirmation
    B -> S:   GET {{baseUrl}}/performanceReport/{{id}}
    return 200 PerformanceReport in current state
end

...

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S --> B : 204 confirmation

@enduml