@startuml

title Envelope and Payload UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

rectangle Payload {

        class SwVc {
            <<... attributes are skipped ...>>
        }

        class SwVcEndPoint_A {
            <<... attributes are skipped ...>>
        }

        SwVc "1" *-->"2..*" SwVcEndPoint_A

        class SwVcEndPoint_Z {
            <<... attributes are skipped ...>>
        }

        SwVc "1" *-->"2..*" SwVcEndPoint_Z

    class SdWanUni_A {
        <<... attributes are skipped ...>>
    }

    SwVcEndPoint_A "*" <--o "1" SdWanUni_A

    class SdWanUni_Z {
        <<... attributes are skipped ...>>
    }

    SwVcEndPoint_Z "*" <--o "1" SdWanUni_Z

}
rectangle Envelope {
    class ServiceOrder  {
        <<... attributes are skipped ...>>
    }

    class ServiceOrderItem_A  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_A

    class ServiceOrderItem_B  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_B

    class ServiceOrderItem_C  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_C

}

ServiceOrderItem_A <-->  SwVc
ServiceOrderItem_B <--> SdWanUni_A
ServiceOrderItem_C <--> SdWanUni_Z

@enduml