@startuml

title SD-WAN UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

class MefServiceConfiguration {
    @type*: string <<discriminator>>
}

class MefServiceRefOrValue {
    id: string 
    href: string
    place: RelatedPlaceRefOrValue 
    serviceOffering: ServiceOfferingRef
    serviceSpecification: ServiceSpecificationRef
}

MefServiceRefOrValue *-->"0..1" MefServiceConfiguration : serviceConfiguration


  class SdWanUniServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- SdWanUniServiceOrder

  class SwVcServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- SwVcServiceOrder

@enduml