@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class L1Enni {
    peeringIdentifier: String[1]
    listOfPhysicalLayer: L1NniPhysicalLayer[1..*]
    protection: NniProtection[1]
}

MefServiceConfiguration <|-- L1Enni
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml