@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class L1SubscriberVc {
    "...attributes are not shown"
}

class L1SubscriberVcEndPoint {
    "...attributes are not shown"
}

class L1SubscriberUni {
    "...attributes are not shown"
}



L1SubscriberVc "1" *-->"2*" L1SubscriberVcEndPoint
L1SubscriberUni "1" o-->"0..1" L1SubscriberVcEndPoint

@enduml