@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
!define datatype(x) class x << (D,#FF7700) DataType>>


datatype(Bgp) {

    subscriberAsNumber: integer
    peerAsNumber: integer
    connectionAddressFamily: AddressFamilyIpv4Ipv6
    administrativeDistance: integer
    asOverride: EnabledDisabled
    holdTime: integer
    authentication: string
}

Bgp *-->"*" BgpCommunity : bgpCommunityList
Bgp *-->"*" BgpExtendedCommunity : bgpExtendedCommunityList
Bgp *--> Damping : damping
Bgp *--> PeeringAddress : peeringAddresses

datatype(BgpCommunity) {

    autonomousSystemDefined: integer
    autonomousSystemNumber: integer
}



datatype(BgpExtendedCommunity) {

    regularValue*: integer
    extendedType*: integer
    extendedValue*: integer
    regularType*: integer
}


datatype(Damping) {

    decayHalfLifeWhileReachable: integer
    reuseListMemoryReuseListMax: integer
    maxHoldDownTime: integer
    reuseListTimeGranularity: integer
    timeGranularity: integer
    decayHalfLifeWhileUnReachable: integer
    decayMemoryLimit: integer
    reuseThreshold: integer
    cutoffThreshold: integer
    numberOfReuseLists: integer
    reuseIndexArraySize: integer
}



datatype(PeeringAddress) {

    peeringAddressType: PeeringAddressType
}

PeeringAddress *-->"*" SubscriberAndSpLoopbackAddresses : subscriberAndSpLoopbackAddresses


datatype(SubscriberAndSpLoopbackAddresses) {

}

datatype(Ipv4OrIpv6Address) {

}

SubscriberAndSpLoopbackAddresses *--> Ipv4OrIpv6Address : subscriberLoopbackAddress
SubscriberAndSpLoopbackAddresses *--> Ipv4OrIpv6Address : spLoopbackAddress

@enduml