@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}
!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(Ipv6ConnectionAddressing) {
    ipv6AddressType: Ipv6AddressingType [1]
    subscriberIpv6Address: Ipv6Address [1]
    ipv6Subnet: Ipv6Subnet [0..*]
}

datatype(Ipv6Address) {
    String/ipv6: format ipv6
}

enum Ipv6AddressingType {
    - DHCP 
    - SLAAC
    - STATIC 
    - LL_ONLY
    }
    
datatype(Ipv6Prefix) {
    ipv6Address: Ipv6Address
    prefixLength: Integer
}

Ipv6Prefix *--> Ipv6Address: ipv6Address

datatype(Ipv6Subnet) {
    ipv6Prefix: Ipv6Prefix
    serviceProviderIpv6Address: Ipv6Address [1..*]
    reservedPrefixes: Ipv6Prefix [0..*]
}


Ipv6Subnet *--> Ipv6Prefix: ipv6Prefix
Ipv6Subnet *--> "1..*" Ipv6Address: serviceProviderIpv6Addresses
Ipv6Subnet *--> "0..*" Ipv6Prefix: reservedPrefixes

Ipv6ConnectionAddressing *--> Ipv6AddressingType
Ipv6ConnectionAddressing *--> Ipv6Address: subscriberIpv6Address
Ipv6ConnectionAddressing *--> Ipv6Subnet: ipv6Subnet


@enduml