@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class PolicyMap {
    zone: Zone [1]
    application: Application [1]
    ingressPolicy: IngressPolicy [0..1]
    egressPolicy: EgressPolicy [0..1]
}

PolicyMap "1" *--> "1" Zone
PolicyMap "1" *--> "0..1" Application
PolicyMap "1" *-->"0..1" IngressPolicy
PolicyMap "1" *--> "0..1" EgressPolicy

class Application {
    applicationFlowSpecificationGroup: ApplicationFlowSpecificationGroup [0..1]
    applicationFlowSpecification: ApplicationFlowSpecification [0..1]
}

Application "1" *--> "0..1" ApplicationFlowSpecification
Application "1" *--> "0..1" ApplicationFlowSpecificationGroup
ApplicationFlowSpecificationGroup <--> ApplicationFlowSpecification

class IngressPolicy {

    policyName: String [1]
    encryption: Encryption [1]
    internetBreakout: EnabledDisabled [1]
    publicPrivate: PublicPrivate [1]
    backUp: EnabledDisabled [1]
    virtualTopology: String [1]
    allowedDestinationZones:
    billingMethod:
    performance:
    bandwidth:
    afSecurityIngress:
}

class EgressPolicy {

    policyName: String [1]
    blockSource:
    afSecurityEgress: 
    
}

class Zone {

    zonePrefixes: Ipv4Ipv6Prefixes [1..*]
    zoneName: String [1]
    zoneIngressPolicy: ZoneIngressPolicy [*]
    
}

class ApplicationFlowSpecification {

    name: String [1]
    applicationFlowCriteria: ApplicationFlowCriteria [1]
    applicationFlowSpecificationGroup: ApplicationFlowSpecificationGroup [1]
    
}

class ApplicationFlowSpecificationGroup {

    name: String [1]
    applicationFlowSpecification: ApplicationFlowSpecification [*]
    
}

class ApplicationFlowCriteria {

    sav4: Ipv4Prefix [*]
    dav4: Ipv4Prefix [*]
    protv4: 
    sav6: Ipv6Prefix [*]
    dav6: Ipv6Prefix [*]
    nextheadv6:
    dscp:
    sport:
    dport:
    appid:
    
}

ApplicationFlowSpecification *--> "1" ApplicationFlowCriteria