@startuml

left to right direction

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

    class SdWanUni {
         administrativeState: AdminState[1]
         operationalState: OperationalState[1]
         uniIdentifier: Identifier45[1]
         l2Interface: L2Interface[1]
         maxL2FrameSize: Integer[1]
         ipv4ConnectionAddressing: Ipv4ConnectionAddressing[0..1]
         ipv6ConnectionAddressing: Ipv6ConnectionAddressing[0..1]
         routingProtocols: RoutingProtocols[*]
         swvcEndPoint: SwVcEndPoint[0..1]
         availabilityObjective: AvailabilityObjective[1]
         meanTimeToRepairObjective: MeanTimeToRepairObjective[1]
        }

    class SwVcEndPoint {
        administrativeState: AdminState[1]
        operationalState: OperationalState[1]
        endPointIdentifier: Identifier45[1]
        policyMap: PolicyMap[*]
        sdWanUni: SdWanUni[1]
        ucsEndPointList: UcsEndPoint[1..*]
        networkAddressTranslation: NetworkAddressTranslation[0..1]
        }

    class SwVc {
    administrativeState: AdminState [1]
    operationalState: OperationalState [1]
    identifier: String [1]
    endPointList: SwVcEndPoint [2..*]
    ucsList: Ucs [1..*]
    reservedPrefixes: Ipv4OrIpv6Prefix [*]
    zoneList: Zone [1..*]
    virtualTopologyList: VirtualTopology [*]
    performanceTimeIntervals: PerformanceTimeIntervals [0..1]
    performanceObjectivesReportingPeriods: ServicePerformanceObjectivesReportingPeriods [0..1]
    rateLimiterList: RateLimiter [*]
    securityPolicyList: SecurityPolicy [*]
    applicationFlowBusinessImportanceLevels: ApplicationFlowBusinessImportanceLevels [*]
    policyList: PolicyMap[*]
    applicationFlowSpecificationGroup: ApplicationFlowSpecificationGroup [*]
    applicationFlowSpecificationList: ApplicationFlowSpecification [0..1]
        }

    SwVcEndPoint "2..*" <--* "1" SwVc
    SdWanUni "1" o--> "0..1" SwVcEndPoint


@enduml