@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(SecurityPolicy) {
    policyIdentifier: SecurityPolicyIdentifier[1]
    securityEventNotification: SecurityEventNotification[1]
    middleBoxFunction: MbfOrNone[1]
    ipPortProtocolFiltering: IppfOrNone[1]
    dnsProtocolFiltering: DpfOrNone[1]
    domainNameFiltering: DnfOrNone[1]
    urlFiltering: UrlfOrNone[1]
    malwareDetectionRemoval: MdR_OrNone[1]
}

SecurityPolicy *--> "1" SecurityEventNotification: securityEventNotification
SecurityPolicy *--> "1" MbfOrNone: middleBoxFunction
SecurityPolicy *--> "1" IppfOrNone: ipPortProtocolFiltering
SecurityPolicy *--> "1" DpfOrNone: dnsProtocolFiltering
SecurityPolicy *--> "1" DnfOrNone: domainNameFiltering
SecurityPolicy *--> "1" UrlfOrNone: urlFiltering
SecurityPolicy *--> "1" MdR_OrNone: malwareDetectionRemoval

datatype(SecurityEventNotification) {
    <<skipped>>
}

datatype(MbfOrNone) {
    <<skipped>>
}

datatype(IppfOrNone) {
    <<skipped>>
}

datatype(DpfOrNone) {
    <<skipped>>
}

datatype(DnfOrNone) {
    <<skipped>>
}

datatype(UrlfOrNone) {
    <<skipped>>
}

datatype(MdR_OrNone) {
    <<skipped>>
}

@enduml