@startuml

skinparam {
    FontName Times
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

!define datatype(x) class x << (D,#FF7700) DataType>>

datatype(SwVc) {
    swVcIdentifier: SwVcIdentifier [1]
    ucsList: Ucs [1..*]
    reservedPrefixes: Ipv4OrIpv6Prefix [1]
    zoneList: Zone [1..*]
    virtualTopologiesList: VirtualTopology [1..*]
    performanceTimeIntervals: PerformanceTimeIntervals [1]
    performanceObjectivesReportingPeriods: ServicePerformanceObjectivesReportingPeriods [1]
    rateLimiterList: RateLimiter [*]
    securityPolicyList: SecurityPolicy [*]
    applicationFlowBusinessImportanceLevels: ApplicationFlowBusinessImportanceLevels [*]
    policyList: Policy [*]
    applicationFlowSpecificationGroupList: ApplicationFlowSpecificationGroup [*]
    applicationFlowSpecificationList: ApplicationFlowSpecification [*]
}

SwVc *-->"1..*" Ucs: ucsList
SwVc *--> "1..*" Zone : zoneList
SwVc *--> "*" VirtualTopology: virtualTopologiesList

SwVc *--> "*" SecurityPolicy: securityPolicyList
SwVc *--> "0..1" PerformanceTimeIntervals: performanceTimeIntervals
SwVc *--> "*" Policy: policyList

SwVc *--> "*" ApplicationFlowSpecificationGroup: applicationFlowSpecificationGroupList
SwVc *--> "*" ApplicationFlowSpecification: applicationFlowSpecificationList

datatype(Policy) {
    <<skipped>>
}

datatype(Ucs) {
    <<skipped>>
}

datatype(Zone) {
    <<skipped>>
}

datatype(SecurityPolicy) {
    <<skipped>>
}

datatype(VirtualTopology) {
    <<skipped>>
}

datatype(PerformanceTimeIntervals) {
    <<skipped>>
}

datatype(ApplicationFlowSpecificationGroup) {
    <<skipped>>
}

datatype(ApplicationFlowSpecification) {
    <<skipped>>
}

@enduml