@startuml

title Carrier Ethernet UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}

class MefProductConfiguration {
    @type*: string <<discriminator>>
}

class MefProductRefOrValue {
    id: string 
    href: string
    place: RelatedPlaceRefOrValue 
    productOffering: ProductOfferingRef
    productSpecification: ProductSpecificationRef
}

MefProductRefOrValue *-->"0..1" MefProductConfiguration : productConfiguration


  class SubscriberUniProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- SubscriberUniProductOrder

  class EvcProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- EvcProductOrder

    class OperatorUniProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- OperatorUniProductOrder

  class EnniProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- EnniProductOrder

  class VuniProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- VuniProductOrder

  class OvcProductOrder <<ProductSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefProductConfiguration <|-- OvcProductOrder

@enduml