@startuml

title Envelope and Payload UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

rectangle Payload {

        class CarrierEthernetOvc {
            <<... attributes are skipped ...>>
        }

        class CarrierEthernetOvcEndPoint_A {
            <<... attributes are skipped ...>>
        }

        CarrierEthernetOvc "1" *-->"2..*" CarrierEthernetOvcEndPoint_A

        class CarrierEthernetOvcEndPoint_Z {
            <<... attributes are skipped ...>>
        }

        CarrierEthernetOvc "1" *-->"2..*" CarrierEthernetOvcEndPoint_Z



    class CarrierEthernetOperatorUni {
        <<... attributes are skipped ...>>
    }

    CarrierEthernetOvcEndPoint_A "*" <--o "1" CarrierEthernetOperatorUni

    class CarrierEthernetEnni  {
        <<... attributes are skipped ...>>
    }

    CarrierEthernetOvcEndPoint_Z "*" <--o "1" CarrierEthernetEnni
}
rectangle Envelope {
    class ServiceOrder  {
        <<... attributes are skipped ...>>
    }

    class ServiceOrderItem_A  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_A

    class ServiceOrderItem_B  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_B

    class ServiceOrderItem_C  {
        <<... attributes are skipped ...>>
    }

    ServiceOrder "1" *--> "*" ServiceOrderItem_C
}

ServiceOrderItem_A <-->  CarrierEthernetOvc
ServiceOrderItem_B <--> CarrierEthernetOperatorUni
ServiceOrderItem_C <--> CarrierEthernetEnni

@enduml