@startuml

title Envelope and Payload UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

rectangle Payload {

        class AccessElineOvcOrderV100 {
            <<... attributes are skipped ...>>
        }

        class AccessElineOvcEndPoint_A {
            <<... attributes are skipped ...>>
        }

        AccessElineOvcOrderV100 "1" *-->"2..*" AccessElineOvcEndPoint_A

        class AccessElineOvcEndPoint_Z {
            <<... attributes are skipped ...>>
        }

        AccessElineOvcOrderV100 "1" *-->"2..*" AccessElineOvcEndPoint_Z

    class Enni {
        <<... attributes are skipped ...>>
    }

        AccessElineOvcEndPoint_Z "*" <--o "1" Enni

    class OperatorUNIOrderV100 {
        <<... attributes are skipped ...>>
    }

    AccessElineOvcEndPoint_A "*" <--o "1" OperatorUNIOrderV100

}
rectangle Envelope {
    class ProductOrder  {
        <<... attributes are skipped ...>>
    }

    class ProductOrderItem_A  {
        <<... attributes are skipped ...>>
    }

    ProductOrder "1" *--> "*" ProductOrderItem_A

    class ProductOrderItem_B  {
        <<... attributes are skipped ...>>
    }

    ProductOrder "1" *--> "*" ProductOrderItem_B

}

ProductOrderItem_A <-->  AccessElineOvcOrderV100
ProductOrderItem_B <--> OperatorUNIOrderV100

@enduml