@startuml

title Subscriber Ethernet E-LAN UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

class AlternateServiceOfferingProposal {
}

AlternateServiceOfferingProposal *-->"1" MefAlternateService : alternateService

class MefAlternateService {
    serviceOffering * : string
    serviceSpecification: string
}

class MefServiceConfiguration {
    @type*: string <<discriminator>>
}

MefAlternateService *-->"1" MefServiceConfiguration : serviceConfiguration


class MefServiceRefOrValue {

    @type*: string <<discriminator>>
    href: string 
    id: string 
    serviceOffering: string
    serviceSpecification: string
}

MefServiceRefOrValue *-->"0..1" MefServiceConfiguration : serviceConfiguration

rectangle EPLAN {
  class EplanSubscriberUniServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EplanSubscriberUniServiceOrder

  class EplanEvcServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EplanEvcServiceOrder

}

rectangle EVPLAN {
  class EvplanSubscriberUniServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }


  MefServiceConfiguration <|-- EvplanSubscriberUniServiceOrder

  class EvplanEvcServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EvplanEvcServiceOrder
}
@enduml