@startuml

title Subscriber Ethernet E-Tree UML Diagram

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ServiceSpecification>> FireBrick
}

class AlternateServiceOfferingProposal {
}

AlternateServiceOfferingProposal *-->"1" MefAlternateService : alternateService

class MefAlternateService {
    serviceOffering * : string
    serviceSpecification: string
}

class MefServiceConfiguration {
    @type*: string <<discriminator>>
}

MefAlternateService *-->"1" MefServiceConfiguration : serviceConfiguration


class MefServiceRefOrValue {

    @type*: string <<discriminator>>
    href: string 
    id: string 
    serviceOffering: string
    serviceSpecification: string
}

MefServiceRefOrValue *-->"0..1" MefServiceConfiguration : serviceConfiguration

rectangle EPTREE {
  class EpTreeSubscriberUniServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EpTreeSubscriberUniServiceOrder

  class EpTreeEvcServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EpTreeEvcServiceOrder

}

rectangle EVPTREE {
  class EvpTreeSubscriberUniServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }


  MefServiceConfiguration <|-- EvpTreeSubscriberUniServiceOrder

  class EvpTreeEvcServiceOrder <<ServiceSpecification>> {

    <<... attributes are skipped ...>>
  }
  MefServiceConfiguration <|-- EvpTreeEvcServiceOrder
}
@enduml