@startuml

ServiceOrderItem_Common -u[hidden]-> ServiceOrder
class Duration {

    amount*: integer
    units*: TimeUnit
}



class MefServiceConfiguration {

    @type*: string
}



class Note_BusSof {

    author*: string
    date*: date-time
    id*: string
    source*: BusSofType
    text*: string
}



class OrderCoordinatedAction {

    coordinationDependency*: OrderItemCoordinationDependencyType
    orderId*: string
}

OrderCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class OrderItemCoordinatedAction {

    coordinationDependency*: OrderItemCoordinationDependencyType
    itemId*: string
}

OrderItemCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


class RelatedPlaceRefOrQuery {
    contact: ContactInformation
    place*: PlaceRefOrQuery
    role*: string
}

class ServiceOrder {

    href: uri
    id*: string
    completionDate: date-time
    expectedCompletionDate: date-time
    startDate: date-time
    state*: ServiceOrderStateType
    orderDate*: date-time
}
ServiceOrder_Common <|-- ServiceOrder

ServiceOrder *-->"1..*" ServiceOrderItem : serviceOrderItem


class ServiceOrderItem {

    state*: ServiceOrderItemStateType
}
ServiceOrderItem_Common <|-- ServiceOrderItem

ServiceOrderItem *-->"*" TerminationError : terminationError


class ServiceOrderItemRef {

    itemId*: string
    serviceOrderHref: string
    serviceOrderId: string
}



class ServiceOrderItemRelationship {

    relationshipType*: string
}

ServiceOrderItemRelationship *-->"1" ServiceOrderItemRef : orderItem


class ServiceOrderItem_Common {

    id*: string
    action*: ServiceActionType
}

ServiceOrderItem_Common *-->"*" OrderItemCoordinatedAction : coordinatedAction
ServiceOrderItem_Common *-->"*" Note_BusSof : note
ServiceOrderItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
ServiceOrderItem_Common *-->"1" ServiceValue : service
ServiceOrderItem_Common *-->"*" ServiceOrderItemRelationship : serviceOrderItemRelationship


class ServiceOrderItem_Create {

}
ServiceOrderItem_Common <|-- ServiceOrderItem_Create



class ServiceOrderRef {

    href: string
    id*: string
}



class ServiceOrderRelationship {

    relationshipType*: string
}

ServiceOrderRelationship *-->"1" ServiceOrderRef : serviceOrder

class ServiceOrder_Common {

    description: string
    externalId: string
    requestedCompletionDate*: date-time
    requestedStartDate*: date-time
}

ServiceOrder_Common *-->"*" OrderCoordinatedAction : coordinatedAction
ServiceOrder_Common *-->"*" Note_BusSof : note
ServiceOrder_Common *-->"*" ServiceOrderRelationship : orderRelationship
ServiceOrder_Common *-->"*" RelatedContactInformation : relatedContactInformation


class ServiceOrder_Create {

}
ServiceOrder_Common <|-- ServiceOrder_Create

ServiceOrder_Create *-->"1..*" ServiceOrderItem_Create : serviceOrderItem


class ServiceRef {

    href: string
    id*: string
}



class ServiceRelationship {

    relationshipType*: string
}

ServiceRelationship *-->"1" ServiceRef : service

class ServiceValue {

    href: string
    id: string
    description: string
    externalId: string
    startDate: date-time
    endDate: date-time
    state: ServiceStateType
    serviceType: string
    name: string
}

ServiceValue *-->"*" Note_BusSof : note
ServiceValue *-->"*" ServiceRelationship : serviceRelationship
ServiceValue *-->"*" RelatedContactInformation : relatedContactInformation
ServiceValue *-->"*" RelatedPlaceRefOrQuery : place
ServiceValue *--> MefServiceConfiguration : serviceConfiguration
ServiceValue *-->"*" ServiceOrderItemRef : serviceOrderItem


class TerminationError {

    code: Error422Code
    propertyPath: string
    value: string
}


@enduml
