@startuml

state feasibilityChecked : Resources have been checked\nfor availability
state designed : Resources have been identified/allocated 
state reserved : Resources have been reserved/blocked
state inactive : Resources have been provisioned\nbut Service is not yet ready
state active : Resources have been activated and\nService is ready for use
state terminated : Service is shut down


[*] --> feasibilityChecked : checkFeasibility
[*] --> inactive : provisionService
[*] --> designed : designService
[*] --> reserved : reserveService
[*] --> active : activateService

feasibilityChecked --> designed : designService
feasibilityChecked --> reserved : reserveService
feasibilityChecked --> inactive : provisionService
feasibilityChecked -down-> active : activateService
feasibilityChecked --> feasibilityChecked

designed -right-> reserved : reserveService
designed --> inactive : provisionService
designed --> active : activateService
designed --> designed

reserved -d-> designed : designService
reserved --> inactive : provisionService
reserved --> active : activateService
reserved --> reserved 

inactive -d-> active : activateService
inactive --> terminated : terminateService
inactive --> inactive 

active -left-> inactive : deactivateService
active --> terminated : terminateService
active --> active

feasibilityChecked --> terminated : terminateService
designed -down-> terminated : terminateService
reserved -down-> terminated : terminateService

terminated --> [*] : retireService

@enduml