@startuml

state feasibilityChecked : Resources have been checked\nfor availability
state designed : Resources have been identified/allocated 
state reserved : Resources have been reserved/blocked
state inactive : Resources have been provisioned\nbut Service is not yet ready
state active : Resources have been activated and\nService is ready for use
state terminated : Service is shut down


[*] --> feasibilityChecked : checkFeasibility\n(action=add)
[*] --> inactive : provisionService\n(action=add)
[*] --> designed : designService\n(action=add)
[*] --> reserved : reserveService\n(action=add)
[*] --> active : activateService\n(action=add)

feasibilityChecked --> designed : designService
feasibilityChecked --> reserved : reserveService
feasibilityChecked --> inactive : provisionService
feasibilityChecked --> active : activateService

designed -> reserved : reserveService
designed --> inactive : provisionService
designed --> active : activateService

reserved -> designed : designService
reserved --> inactive : provisionService
reserved --> active : activateService

inactive -right-> active : activateService
inactive --> terminated : terminateService

active -left-> inactive : deactivateService
active --> terminated : terminateService


terminated --> [*] : retireService\n(action=delete)

@enduml