@startuml


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class ServiceOrderEventPayload {

    id*: string
    href: string
}



class ServiceOrderCreateEvent {

    eventType*: string
}
Event <|-- ServiceOrderCreateEvent

ServiceOrderCreateEvent *-->"1" ServiceOrderEventPayload : event


class ServiceOrderItemStateChangeEvent {

    eventType*: string
}
Event <|-- ServiceOrderItemStateChangeEvent

ServiceOrderItemStateChangeEvent *-->"1" ServiceOrderItemStateChangeEventPayload : event


class ServiceOrderItemStateChangeEventPayload {

    id*: string
    orderItemId*: string
    href: string
    state*: ServiceOrderItemStateType
}



class ServiceOrderStateChangeEvent {

    eventType*: string
}
Event <|-- ServiceOrderStateChangeEvent

ServiceOrderStateChangeEvent *-->"1" ServiceOrderStateChangeEventPayload : event


class ServiceOrderStateChangeEventPayload {

    id*: string
    href: string
    state*: ServiceOrderStateType
}



class ServiceOrderInformationRequiredEvent {

    eventType*: string
}
Event <|-- ServiceOrderInformationRequiredEvent

ServiceOrderInformationRequiredEvent *-->"1" ServiceOrderEventPayload : event

@enduml
