@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class EthernetPhysicalLink << (D, Gray) >> {
    identifier: Identifer53 [1]
    physicalLayer: EthernetPhysicalLayer [1]
    gender: Gender [1]
    synchronousEthernet: SynchronousEthernet [1]
    connectorType: ConnectorType [1]
}

enum Gender {
    SOCKET
    PLUG
}

enum ConnectorType {
    RJ45
    SC 
    LC 
 }

enum SynchronousEthernet {
    DISABLED
    ESMC
    NO_ESMC
}

enum EthernetPhysicalLayer {
    10BASE_FB
    10BASE_FL
        :
    400GBASE_SR8
    <<... Not all enumerations are shown ...>>

}


EthernetPhysicalLink "1" *-->"1*" EthernetPhysicalLayer
EthernetPhysicalLink "1" *-->"1" Gender
EthernetPhysicalLink "1" *-->"1*" ConnectorType
EthernetPhysicalLink "1*" *--> "1" SynchronousEthernet


@enduml