@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class IpServicesExternalInterface{
    identifier: Identifer53 [1]
    administrativeState: AdminState [1]
    operationalState: OperationalState [1]
}

class IpServicesExternalInterfaceLink {
    identifier: Identifer53 [1]
    administrativeState: AdminState [1]
    operationalState: OperationalSate [1]
    bfd: AccessLinkBfd [1]
    l2Technology: L2Technology [1]
    mtu: Mtu [1]
}

class IpUniAccessLink {
    ConnectionType: connectionType
    UniIpv4ConnectionAddressing: ipv4ConnectionAddressing [0..1]
    UniIpv6ConnectionAddressing: ipv6ConnectionAddressing [0..1]
    DhcpRelay: dhcpRelay
    EnabledDisabled: prefixDelegation
    IpUniAccessLinkIngressBwpEnvelope: ingressBandwidthProfileEnvelope [0..1]
    IpUniAccessLinkEgressBwpEnvelope: egressBandwidthProfileEnvelope [0..1]
    Vrid: * reservedVrid
}

class IpUni {
    ipUniAccessLink: IpUniAccessLink [1..*]
    ipvcEndPoint: IpvcEndPoint [*]
    managementType: UniManagementType [1]
    ingressBandwidthProfileEnvelope: IpUniIngressBwpEnvelope [0..1]
    egressBandwidthProfileEnvelope: IpUniEgressBwpEnvelope [0..1]
    listOfControlProtocols: RoutingProtocols [0..1]
    reversePathForwarding: EnabledDisabled [1]
}


class IpEnniLink {
    EnniIpv4ConnectionAddressing: ipv4ConnectionAddressing
    EnniIpv6ConnectionAddressing: ipv6ConnectionAddressing
}

class IpEnni {
  enniType: EnniType [1]
  routingInformation: EnniRoutingInformation [1..*]
  ingressBandwidthProfileEnvelopes: IpEnniIngressBwpEnvelopePerEnniLink [1]
  egressBandwidthProfileEnvelopes: IpEnniEgressBwpEnvelopePerEnniLink [1] 
}

IpServicesExternalInterfaceLink  <|-- IpUniAccessLink
IpServicesExternalInterfaceLink <|-- IpEnniLink

IpServicesExternalInterface  <|-- IpUni
IpServicesExternalInterface <|-- IpEnni

@enduml