@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class IpServicesExternalInterfaceLink {
    identifier: Identifer53 [1]
    administrativeState: AdminState [1]
    operationalState: OperationalSate [1]
    bfd: AccessLinkBfd [1]
    l2Technology: L2Technology [1]
    mtu: Mtu [1]
}

class IpUniAccessLink {
    connectionType: ConnectionType [1]
    ipv4ConnectionAddressing: UniIpv4ConnectionAddressing [0..1]
    ipv6ConnectionAddressing: UniIpv6ConnectionAddressing [0..1]
    dhcpRelay: DhcpRelay [0..1]
    prefixDelegation: EnabledDisabled [1]
    ingressBandwidthProfileEnvelope: IpUniAccessLinkIngressBwpEnvelope [0..1]
    egressBandwidthProfileEnvelope: IpUniAccessLinkEgressBwpEnvelope [0..1]
    reservedVrid: Vrid [1]
}


class IpEnniLink {
    ipv4ConnectionAddressing: EnniIpv4ConnectionAddressing [0..1]
    ipv6ConnectionAddressing: EnniIpv6ConnectionAddressing [0..1]
}


IpServicesExternalInterfaceLink  <|-- IpUniAccessLink
IpServicesExternalInterfaceLink <|-- IpEnniLink


@enduml