@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Ipvc {
    administrativeState: AdminState [1]
    operationalState: OperationalState [1]
    ipvcIdentifier: Identifier53 [1]
    ipvcTopology: ServiceTopology [1]
    packetDelivery: PacketDelivery [1]
    maximumNumberOfIpv4Routes: Integer [0..1]
    maximumNumberOfIpv6Routes: Integer [0..1]
    dscpPreservation: EnabledDisabled [1]
    serviceLevelSpecification: IpSls [0..1]
    maximumTransferUnit: Integer [1]
    pathMtuDiscovery: EnabledDisabled [1]
    fragmentation: EnabledDisabled [1]
    cloud: IpvcCloud [0..1]
    reservedPrefixes: Ipv4Ipv6Prefixes [1]
    listOfClassOfServiceNames: String [1..*]

}


Ipvc "1" *--> "0..1" IpvcCloud : cloud


class IpvcCloud << (D, Gray) >> {
    type: CloudType
    ingressClassOfServiceMap: IngressClassOfServiceMap
    dataLimit: CloudDataLimit
    dns: CloudDns
    networkAddressTranslation: Ipv4Prefix
    subscriberPrefixList: Ipv4IpV6Prefixes
}


@enduml