@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class L2Technology << (D, Gray) >> {
    trunkId: String [1]
    demux: Demux [1]
}

class Demux << (D, Gray) >> {
    utpt: Boolean [1]
    vlanId: VlanId [0..*]
}

L2Technology "1" *-->"1" Demux

@enduml