@startuml

title Legato Service Ordering API Schemas Diagram

entity ActionType { 
}

entity Addressable { 
    id: String
    href: URI
    name: String
}

entity Characteristic { 
    * name: String
    valueType: String
    value: OasAnyTypeNotMapped
}

entity Error { 
    * code: Integer
    * reason: String
    message: List<String>
    status: List<String>
    referenceError: List<String>
}

entity EventSubscription { 
    * id: String
}

entity EventSubscriptionInput { 
    * query: String
    * callback: String
}

entity Extensible { 
    * @type: String
    @baseType: String
    @schemaLocation: URI
}

entity MefServiceConfiguration { 
}

entity Note { 
    author: String
    date: Date
    system: String
    text: String
}

entity OrderItemRelationshipType { 
}

entity OrderRelationshipType { 
}

entity Place { 
    role: String
}

entity Referenceable { 
    * @referredType: String
}

entity RelatedPartyRef { 
    role: String
}

entity ResourceRef { 
    @type: String
}

entity ServiceCreate { 
    category: String
    description: String
    mefServiceConfiguration: MefServiceConfiguration
    note: List<Note>
    place: List<Place>
    relatedParty: List<RelatedPartyRef>
    serviceCharacteristic: List<Characteristic>
    serviceRelationship: List<ServiceRelationship>
    serviceSpecification: ServiceSpecificationRef
    serviceType: String
    state: ServiceStateType
    supportingResource: List<ResourceRef>
    supportingService: List<ServiceRef>
}

entity ServiceOrder { 
    state: ServiceOrderStateType
    orderDate: Date
    startDate: Date
    expectedCompletionDate: Date
    completionDate: Date
}

entity ServiceOrderCreate { 
    externalId: String
    description: String
    category: String
    note: List<Note>
    notificationContact: String
    priority: Integer
    requestedStartDate: Date
    requestedCompletionDate: Date
    relatedParty: List<RelatedPartyRef>
    orderItem: List<ServiceOrderItem>
    orderRelationship: List<ServiceOrderRelationship>
}

entity ServiceOrderItem { 
    * id: String
    action: ActionType
    * service: ServiceCreate
    state: ServiceOrderStateType
    orderItemRelationship: List<ServiceOrderItemRelationship>
}

entity ServiceOrderItemRef { 
    @type: String
}

entity ServiceOrderItemRelationship { 
    * relationshipType: OrderItemRelationshipType
    * serviceOrder: ServiceOrderItemRef
}

entity ServiceOrderRef { 
    @type: String
}

entity ServiceOrderRelationship { 
    * relationshipType: OrderRelationshipType
    * serviceOrder: ServiceOrderRef
}

entity ServiceOrderStateType { 
}

entity ServiceRef { 
    @type: String
}

entity ServiceRelationship { 
    * relationshipType: ServiceRelationshipType
    * service: ServiceRef
}

entity ServiceRelationshipType { 
}

entity ServiceSpecificationRef { 
    version: String
    targetServiceSchema: TargetServiceSchema
}

entity ServiceStateType { 
}

entity TargetServiceSchema { 
}

Extensible <|--- Addressable
Extensible <|--- Characteristic
EventSubscriptionInput <|--- EventSubscription
Extensible <|--- MefServiceConfiguration
Extensible <|--- Note
Addressable <|--- Place
Addressable <|--- Referenceable
Referenceable <|--- RelatedPartyRef
Referenceable <|--- ResourceRef
Extensible <|--- ServiceCreate
ServiceOrderCreate <|--- ServiceOrder
Addressable <|--- ServiceOrderCreate
Extensible <|--- ServiceOrderItem
Referenceable <|--- ServiceOrderItemRef
Referenceable <|--- ServiceOrderRef
Referenceable <|--- ServiceRef
Referenceable <|--- ServiceSpecificationRef
Extensible <|--- TargetServiceSchema

ServiceOrderRelationship -- ServiceOrderRef : serviceOrder
ServiceSpecificationRef -- TargetServiceSchema : targetServiceSchema
ServiceOrderItem -- ServiceCreate : service
ServiceOrderItem -- "0..*" ServiceOrderItemRelationship : orderItemRelationship
ServiceOrderCreate -- "0..*" Note : note
ServiceOrderCreate -- "0..*" RelatedPartyRef : relatedParty
ServiceOrderCreate -- "0..*" ServiceOrderItem : orderItem
ServiceOrderCreate -- "0..*" ServiceOrderRelationship : orderRelationship
ServiceOrderItemRelationship -- ServiceOrderItemRef : serviceOrder
ServiceCreate -- MefServiceConfiguration : mefServiceConfiguration
ServiceCreate -- "0..*" Note : note
ServiceCreate -- "0..*" Place : place
ServiceCreate -- "0..*" RelatedPartyRef : relatedParty
ServiceCreate -- "0..*" Characteristic : serviceCharacteristic
ServiceCreate -- "0..*" ServiceRelationship : serviceRelationship
ServiceCreate -- ServiceSpecificationRef : serviceSpecification
ServiceCreate -- "0..*" ResourceRef : supportingResource
ServiceCreate -- "0..*" ServiceRef : supportingService
ServiceRelationship -- ServiceRef : service

@enduml