@startuml

title Carrier Ethernet Schema - Test API Schemas Diagram

entity AdminState { 
    state: String
}

entity AggLinkDepth { 
    linkDepth: Integer
    vlanId: VlanId
}

entity BandwidthProfilePerClassOfServiceName { 
    classOfServiceName: String
    bwpFlow: BwpFlow
}

entity BandwidthProfilePerEquivalenceClassName { 
    egressEquivalenceClassName: String
    bwpFlow: BwpFlow
}

entity BwpFlow { 
    cir: Integer
    cirMax: Integer
    cbs: Integer
    eir: Integer
    eirMax: Integer
    ebs: Integer
    couplingFlag: Boolean
    colorMode: ColorMode
    envelopeId: String
    envelopeRank: Integer
    tokenRequestOffset: Integer
}

entity CarrierEthernetEnni { 
}

entity CarrierEthernetEnniService { 
    operatorEnnIdentifier: String
    svlanIdControl: SvlanIdControl
    maximumNumberOfOvcs: Integer
    maximumNumberOfOvcEndPointsPerOvc: Integer
    tokenShare: String
    envelopes: List<Envelope>
    vuniList: List<CarrierEthernetVirtualUniRef>
    ovcEndPoint: List<CarrierEthernetOvcEndPointRef>
}

entity CarrierEthernetEnniServiceRef { 
    href: URI
    id: UUID
}

entity CarrierEthernetEvc { 
}

entity CarrierEthernetEvcEndPoint { 
}

entity CarrierEthernetEvcEndPointRef { 
    evcRef: CarrierEthernetEvcRef
    id: UUID
}

entity CarrierEthernetEvcRef { 
    href: URI
    id: UUID
}

entity CarrierEthernetExternalInterface { 
    admininstrativeState: AdminState
    operationalState: OperationalState
    externalInterfaceframeFormat: EthernetFrameFormat
    linkOam: EnabledDisabled
    l2cpPeering: List<L2cpPeering>
    lagLinkMeg: EnabledDisabled
    meg: EnabledDisabled
    aggregationLinkMap: List<ConversationIdToAggregationLinkMap>
    maximumFrameSize: Integer
    linkAggregation: LinkAggregation
}

entity CarrierEthernetOperatorUni { 
}

entity CarrierEthernetOperatorUniRef { 
    href: URI
    id: UUID
}

entity CarrierEthernetOvc { 
}

entity CarrierEthernetOvcEndPoint { 
}

entity CarrierEthernetOvcEndPointRef { 
    ovcRef: CarrierEthernetOvcRef
    id: UUID
}

entity CarrierEthernetOvcRef { 
    href: URI
    id: UUID
}

entity CarrierEthernetService { 
    administrativeState: AdminState
    operationalState: OperationalState
    cTagPcpPreservation: EnabledDisabled
    cTagDeiPreservation: EnabledDisabled
    connectionType: ConnectionType
    frameDisposition: FrameDisposition
    listOfCosNames: List<String>
    maximumFrameSize: Integer
    availableMegLevel: List<MegLevel>
    carrierEthernetSls: List<CarrierEthernetSls>
}

entity CarrierEthernetServiceEndPoint { 
    administrativeState: AdminState
    operationalState: OperationalState
    ingressClassOfServiceMap: CosMap
    colorMap: ColorIdentifier
    ingressBandwidthProfilePerEndPoint: List<BwpFlow>
    ingressBandwidthProfilePerCosName: List<BandwidthProfilePerClassOfServiceName>
    sourceMacAddressLimit: List<SourceMacAddressLimit>
}

entity CarrierEthernetSls { 
    timeInterval: TimeIntervalT
    startTime: TimeAndDate
    slsCosNameEntry: List<SlsCosNameEntry>
}

entity CarrierEthernetSubscriberUni { 
}

entity CarrierEthernetSubscriberUniRef { 
    href: URI
    id: UUID
}

entity CarrierEthernetUni { 
}

entity CarrierEthernetVirtualUni { 
    adminState: AdminState
    operationalState: OperationalState
    identifier: String
    sVlanId: VlanId
    defaultEnniCeVlanId: VlanId
    maximumNumberOfOvcEndPoints: Integer
    maximumNumberOfEnniCeVlanIdsPerOvcEndPoint: Integer
    ingressBandwidthProfile: List<BwpFlow>
    egressBandwidthProfile: List<BwpFlow>
    l2cpAddressSet: L2cpAddressSet
    l2cpPeering: L2cpPeering
    mepList: List<MepLevelAndDirection>
    ovcEndPoint: List<CarrierEthernetOvcEndPointRef>
}

entity CarrierEthernetVirtualUniRef { 
    href: URI
    id: UUID
}

entity ClassOfServiceEgressBandwidthProfile { 
    classOfServiceName: String
    egressBwpFlow: EgressBwpFlow
}

entity ColorFieldType { 
    value: String
}

entity ColorIdentifier { 
    colorFieldType: ColorFieldType
    deiColorPac: List<Object>
    pcpColorPac: List<PcpColorIdPac>
    sepColorPac: List<SepColorIdPac>
    dscpColorPac: List<DscpColorIdPac>
}

entity ColorMode { 
    value: String
}

entity ConnectionType { 
}

entity ConversationIdToAggregationLinkMap { 
    conversationId: List<Integer>
    linkNumberIdList: List<Integer>
}

entity CosIdentifier { 
    cosName: String
    l2cpProtocolList: List<L2cpProtocol>
    sepCosIdPac: List<OasAnyTypeNotMapped>
    pcpCosIdPac: List<PcpCosIdPac>
    dscpCosIdPac: List<DscpCosIdPac>
}

entity CosMap { 
    cosMappingType: CosMappingType
    cosMapping: List<CosIdentifier>
}

entity CosMappingType { 
    value: String
}

entity CosNameAndColorToDeiPac { 
    ingressCosName: String
    ingressColor: FrameColor
    deiValue: DeiOrDiscard
}

entity CosNameAndColorToPcpPac { 
    ingressCosName: String
    ingressColor: FrameColor
    pcpValue: PcpOrDiscard
}

entity CosNameToPcpPac { 
    ingressCosName: String
    pcpValue: PcpOrDiscard
}

entity DeiOrDiscard { 
    value: String
}

entity DscpColorIdPac { 
    ipVersion: IpVersion
    dscpValueForGreenList: List<Integer>
    dscpValueForYellowList: List<Integer>
}

entity DscpCosIdPac { 
    dscpValueList: List<DscpValue>
    ipVersion: IpVersion
}

entity DscpEecIdPac { 
    ipVersion: IpVersion
    dscpValueList: List<DscpValue>
}

entity DscpValue { 
}

entity EecIdentifier { 
    eecName: String
    l2cpProtocolList: List<L2cpProtocol>
    pcpEecIdPac: List<PcpEecIdPac>
    dscpEecIdPac: List<DscpEecIdPac>
}

entity EecMap { 
    eecMappingType: EecMappingType
    eecMapping: List<EecIdentifier>
}

entity EecMappingType { 
    value: String
}

entity EgressBwpFlow { 
    cir: Integer
    cirMax: Integer
    rank: Integer
    envelope: Envelope
}

entity EnabledDisabled { 
}

entity Envelope { 
    envelopeId: String
    couplingFlagForIndexZero: Boolean
}

entity EthernetFrameFormat { 
    type: String
}

entity EvcEndPointRole { 
}

entity EvcEpEgressMap { 
    cosName: String
    color: FrameColor
    pcp: PcpOrDiscard
    dei: DeiOrDiscard
}

entity FrameColor { 
}

entity FrameDelivery { 
}

entity FrameDisposition { 
    unicast: FrameDelivery
    multicast: FrameDelivery
    broadbast: FrameDelivery
}

entity IpVersion { 
}

entity L2cpAddressSet { 
    bridgedAddresses: String
}

entity L2cpPeering { 
    protocolId: L2cpProtocol
    destinationAddress: String
    linkIdList: List<String>
}

entity L2cpProtocol { 
    l2cpProtocolType: L2cpProtocolType
    llcAddressOrEtherType: Integer
    subType: List<Integer>
}

entity L2cpProtocolType { 
    vlanType: String
}

entity LinkAggregation { 
}

entity MegLevel { 
}

entity MepDirection { 
}

entity MepLevelAndDirection { 
    mepDirection: MepDirection
    level: Integer
}

entity OneWayAvailabilityPmMetric { 
    orderedPairs: List<OrderedPair>
    oneWayAvailabilityObjective: BigDecimal
}

entity OneWayCompositePmMetric { 
    orderedPairs: List<OrderedPair>
    compositePerformanceIndicatorThreshold: BigDecimal
    compositeFrameLoss: Integer
    compositeFrameDelay: Integer
    compositeFrameDelayVariation: Integer
    oneWayFdThreshold: Time
    oneWayIfdvThreshold: Time
    cpmObjective: BigDecimal
}

entity OneWayConsecutiveHighLossIntervalsPmMetric { 
    orderedPairs: List<OrderedPair>
    consecutiveNumberP: Integer
    oneWayChliObjective: Integer
}

entity OneWayFrameDelayPmMetric { 
    orderedPairList: List<OrderedPair>
    oneWayFdPercentile: BigDecimal
    oneWayFdObjective: Time
}

entity OneWayFrameLossRatioPmMetric { 
    orderedPairs: List<OrderedPair>
    oneWayFrameLossRatioObjective: BigDecimal
}

entity OneWayGroupAvailabilityPmMetric { 
    setOfOrderedPairs: List<SetOfOrderedPairs>
    minimumNumberOfSetsAvailableK: Integer
    oneWayGroupAvailabilityObjective: BigDecimal
}

entity OneWayHighLossIntervalPmMetric { 
    orderedPairs: List<OrderedPair>
    oneWayHighLossIntervalsObjective: Integer
}

entity OneWayInterFrameDelayVariationPmMetric { 
    orderedPairs: List<OrderedPair>
    timeDuration: Time
    oneWayIfdvPercentile: BigDecimal
    oneWayIfdvObjective: Time
}

entity OneWayMeanFrameDelayPmMetric { 
    orderedPairs: List<OrderedPair>
    oneWayMfdObjective: Time
}

entity OneWayMeanFrameDelayRangePmMetric { 
    orderedPairs: List<OrderedPair>
    oneWayFdrPercentile: BigDecimal
    oneWayFdrObjective: Time
}

entity OperationalState { 
    state: String
}

entity OrderedPair { 
    toUni: String
    fromUni: String
}

entity OvcEgressMapType { 
    type: String
}

entity OvcEndPointMap { 
    ovcEndPointMapForm: String
    ovcEndPointMapFormT: List<OvcEndPointMapFormT>
    ovcEndPointMapFormV: List<OvcEndPointMapFormV>
    ovcEndPointMapFormU: List<OvcEndPointMapFormU>
    ovcEndPointMapFormE: List<OvcEndPointMapFormE>
}

entity OvcEndPointMapFormE { 
    sVlanIdList: VlanIdListing
}

entity OvcEndPointMapFormT { 
    rootSVlan: VlanId
    leafSVlan: VlanId
}

entity OvcEndPointMapFormU { 
    ceVlanIdList: VlanIdListing
}

entity OvcEndPointMapFormV { 
    sVlan: VlanId
    enniCeVlanIdList: VlanIdListing
}

entity OvcEndPointRole { 
}

entity OvcEpEgressMap { 
    egressMapType: OvcEgressMapType
    cosNameAndColorToDeiPacList: List<CosNameAndColorToDeiPac>
    cosNameToPcpPacList: List<CosNameToPcpPac>
    cosNameAndColorToPcpPacList: List<CosNameAndColorToPcpPac>
}

entity PcpColorIdPac { 
    pcpValueForGreenList: List<Integer>
    pcpValueForYellowList: List<Integer>
}

entity PcpCosIdPac { 
    pcpValueList: List<PcpOrUntagged>
}

entity PcpEecIdPac { 
    pcpValueList: List<PcpOrUntagged>
}

entity PcpOrDiscard { 
    value: String
}

entity PcpOrUntagged { 
}

entity PhysicalLayer { 
}

entity SepColorIdPac { 
    color: FrameColor
}

entity SetOfOrderedPairs { 
    orderedPairsList: List<OrderedPair>
}

entity SlsCosNameEntry { 
    cosName: String
    deltaT: Integer
    thresholdC: BigDecimal
    consecutiveIntervalN: Integer
    oneWayFrameDelayPmMetric: List<OneWayFrameDelayPmMetric>
    oneWayInterFrameDelayVariationPmMetric: List<OneWayInterFrameDelayVariationPmMetric>
    oneWayMeanFrameDelayPmMetric: List<OneWayMeanFrameDelayPmMetric>
    oneWayFrameLossRatioPmMetric: List<OneWayFrameLossRatioPmMetric>
    oneWayMeanFrameDelayRangePmMetric: List<OneWayMeanFrameDelayRangePmMetric>
    oneWayAvailabilityPmMetric: List<OneWayAvailabilityPmMetric>
    oneWayHighLossIntervalPmMetric: List<OneWayHighLossIntervalPmMetric>
    oneWayConsecutiveHighLossIntervalsPmMetric: List<OneWayConsecutiveHighLossIntervalsPmMetric>
    oneWayCompositePmMetric: List<OneWayCompositePmMetric>
    oneWayGroupAvailabilityPmMetric: List<OneWayGroupAvailabilityPmMetric>
}

entity SourceMacAddressLimit { 
    limit: Integer
    interval: Integer
}

entity SubscriberUniPhysicalLinks { 
    id: String
    physicalLink: PhysicalLayer
    synchronousEthernet: EnabledDisabled
    precisionTiming: EnabledDisabled
}

entity SvlanIdControl { 
    value: String
}

entity SyncModePerLink { 
    syncModeEnabled: Boolean
}

entity TaggedL2cpProcessing { 
    type: String
}

entity Time { 
    number: BigDecimal
    unit: String
}

entity TimeAndDate { 
    day: Integer
    hour: Integer
    minute: Integer
    month: Integer
    second: Integer
    year: Integer
}

entity TimeIntervalT { 
    number: Integer
    unit: String
}

entity VlanId { 
    vlanId: Integer
}

entity VlanIdListOrUntag { 
    type: VlanIdMappingTypeOrUntag
    vlanIdList: List<VlanId>
}

entity VlanIdListing { 
    type: VlanIdMappingType
    vlanIdList: List<VlanId>
}

entity VlanIdMappingType { 
}

entity VlanIdMappingTypeOrUntag { 
}

entity VlanIdPreservation { 
}

CarrierEthernetExternalInterface <|--- CarrierEthernetEnni
CarrierEthernetService <|--- CarrierEthernetEvc
CarrierEthernetServiceEndPoint <|--- CarrierEthernetEvcEndPoint
CarrierEthernetUni <|--- CarrierEthernetOperatorUni
CarrierEthernetService <|--- CarrierEthernetOvc
CarrierEthernetServiceEndPoint <|--- CarrierEthernetOvcEndPoint
CarrierEthernetUni <|--- CarrierEthernetSubscriberUni
CarrierEthernetExternalInterface <|--- CarrierEthernetUni

EgressBwpFlow -- Envelope : envelope
VlanIdListing -- "0..*" VlanId : vlanIdList
CosIdentifier -- "0..*" L2cpProtocol : l2cpProtocolList
CosIdentifier -- "0..*" PcpCosIdPac : pcpCosIdPac
CosIdentifier -- "0..*" DscpCosIdPac : dscpCosIdPac
DscpEecIdPac -- IpVersion : ipVersion
L2cpPeering -- L2cpProtocol : protocolId
BandwidthProfilePerEquivalenceClassName -- BwpFlow : bwpFlow
EvcEpEgressMap -- FrameColor : color
EvcEpEgressMap -- PcpOrDiscard : pcp
EvcEpEgressMap -- DeiOrDiscard : dei
OvcEndPointMapFormT -- VlanId : rootSVlan
OvcEndPointMapFormT -- VlanId : leafSVlan
OvcEndPointMapFormV -- VlanId : sVlan
OvcEndPointMapFormV -- VlanIdListing : enniCeVlanIdList
OvcEndPointMapFormU -- VlanIdListing : ceVlanIdList
SubscriberUniPhysicalLinks -- PhysicalLayer : physicalLink
SubscriberUniPhysicalLinks -- EnabledDisabled : synchronousEthernet
SubscriberUniPhysicalLinks -- EnabledDisabled : precisionTiming
CarrierEthernetOvcEndPointRef -- CarrierEthernetOvcRef : ovcRef
ColorIdentifier -- ColorFieldType : colorFieldType
ColorIdentifier -- "0..*" PcpColorIdPac : pcpColorPac
ColorIdentifier -- "0..*" SepColorIdPac : sepColorPac
ColorIdentifier -- "0..*" DscpColorIdPac : dscpColorPac
CosNameAndColorToDeiPac -- DeiOrDiscard : deiValue
CarrierEthernetSls -- TimeIntervalT : timeInterval
CarrierEthernetSls -- TimeAndDate : startTime
CarrierEthernetSls -- "0..*" SlsCosNameEntry : slsCosNameEntry
CarrierEthernetServiceEndPoint -- AdminState : administrativeState
CarrierEthernetServiceEndPoint -- OperationalState : operationalState
CarrierEthernetServiceEndPoint -- CosMap : ingressClassOfServiceMap
CarrierEthernetServiceEndPoint -- ColorIdentifier : colorMap
CarrierEthernetServiceEndPoint -- "0..*" BwpFlow : ingressBandwidthProfilePerEndPoint
CarrierEthernetServiceEndPoint -- "0..*" BandwidthProfilePerClassOfServiceName : ingressBandwidthProfilePerCosName
CarrierEthernetServiceEndPoint -- "0..*" SourceMacAddressLimit : sourceMacAddressLimit
OneWayMeanFrameDelayPmMetric -- "0..*" OrderedPair : orderedPairs
OneWayMeanFrameDelayPmMetric -- Time : oneWayMfdObjective
CarrierEthernetEvcEndPointRef -- CarrierEthernetEvcRef : evcRef
CarrierEthernetService -- AdminState : administrativeState
CarrierEthernetService -- OperationalState : operationalState
CarrierEthernetService -- EnabledDisabled : cTagPcpPreservation
CarrierEthernetService -- EnabledDisabled : cTagDeiPreservation
CarrierEthernetService -- FrameDisposition : frameDisposition
CarrierEthernetService -- "0..*" CarrierEthernetSls : carrierEthernetSls
ClassOfServiceEgressBandwidthProfile -- EgressBwpFlow : egressBwpFlow
OneWayInterFrameDelayVariationPmMetric -- "0..*" OrderedPair : orderedPairs
OneWayInterFrameDelayVariationPmMetric -- Time : timeDuration
OneWayInterFrameDelayVariationPmMetric -- Time : oneWayIfdvObjective
EecIdentifier -- "0..*" L2cpProtocol : l2cpProtocolList
EecIdentifier -- "0..*" PcpEecIdPac : pcpEecIdPac
EecIdentifier -- "0..*" DscpEecIdPac : dscpEecIdPac
SepColorIdPac -- FrameColor : color
OvcEpEgressMap -- OvcEgressMapType : egressMapType
OvcEpEgressMap -- "0..*" CosNameAndColorToDeiPac : cosNameAndColorToDeiPacList
OvcEpEgressMap -- "0..*" CosNameToPcpPac : cosNameToPcpPacList
OvcEpEgressMap -- "0..*" CosNameAndColorToPcpPac : cosNameAndColorToPcpPacList
OneWayGroupAvailabilityPmMetric -- "0..*" SetOfOrderedPairs : setOfOrderedPairs
SetOfOrderedPairs -- "0..*" OrderedPair : orderedPairsList
CarrierEthernetExternalInterface -- AdminState : admininstrativeState
CarrierEthernetExternalInterface -- OperationalState : operationalState
CarrierEthernetExternalInterface -- EthernetFrameFormat : externalInterfaceframeFormat
CarrierEthernetExternalInterface -- EnabledDisabled : linkOam
CarrierEthernetExternalInterface -- "0..*" L2cpPeering : l2cpPeering
CarrierEthernetExternalInterface -- EnabledDisabled : lagLinkMeg
CarrierEthernetExternalInterface -- EnabledDisabled : meg
CarrierEthernetExternalInterface -- "0..*" ConversationIdToAggregationLinkMap : aggregationLinkMap
DscpColorIdPac -- IpVersion : ipVersion
L2cpProtocol -- L2cpProtocolType : l2cpProtocolType
OneWayConsecutiveHighLossIntervalsPmMetric -- "0..*" OrderedPair : orderedPairs
AggLinkDepth -- VlanId : vlanId
EecMap -- EecMappingType : eecMappingType
EecMap -- "0..*" EecIdentifier : eecMapping
OneWayHighLossIntervalPmMetric -- "0..*" OrderedPair : orderedPairs
BandwidthProfilePerClassOfServiceName -- BwpFlow : bwpFlow
CosNameAndColorToPcpPac -- PcpOrDiscard : pcpValue
OvcEndPointMapFormE -- VlanIdListing : sVlanIdList
CarrierEthernetEnniService -- SvlanIdControl : svlanIdControl
CarrierEthernetEnniService -- "0..*" Envelope : envelopes
CarrierEthernetEnniService -- "0..*" CarrierEthernetVirtualUniRef : vuniList
CarrierEthernetEnniService -- "0..*" CarrierEthernetOvcEndPointRef : ovcEndPoint
OvcEndPointMap -- "0..*" OvcEndPointMapFormT : ovcEndPointMapFormT
OvcEndPointMap -- "0..*" OvcEndPointMapFormV : ovcEndPointMapFormV
OvcEndPointMap -- "0..*" OvcEndPointMapFormU : ovcEndPointMapFormU
OvcEndPointMap -- "0..*" OvcEndPointMapFormE : ovcEndPointMapFormE
CosMap -- CosMappingType : cosMappingType
CosMap -- "0..*" CosIdentifier : cosMapping
CarrierEthernetVirtualUni -- AdminState : adminState
CarrierEthernetVirtualUni -- OperationalState : operationalState
CarrierEthernetVirtualUni -- VlanId : sVlanId
CarrierEthernetVirtualUni -- VlanId : defaultEnniCeVlanId
CarrierEthernetVirtualUni -- "0..*" BwpFlow : ingressBandwidthProfile
CarrierEthernetVirtualUni -- "0..*" BwpFlow : egressBandwidthProfile
CarrierEthernetVirtualUni -- L2cpAddressSet : l2cpAddressSet
CarrierEthernetVirtualUni -- L2cpPeering : l2cpPeering
CarrierEthernetVirtualUni -- "0..*" MepLevelAndDirection : mepList
CarrierEthernetVirtualUni -- "0..*" CarrierEthernetOvcEndPointRef : ovcEndPoint
OneWayFrameLossRatioPmMetric -- "0..*" OrderedPair : orderedPairs
OneWayFrameDelayPmMetric -- "0..*" OrderedPair : orderedPairList
OneWayFrameDelayPmMetric -- Time : oneWayFdObjective
SlsCosNameEntry -- "0..*" OneWayFrameDelayPmMetric : oneWayFrameDelayPmMetric
SlsCosNameEntry -- "0..*" OneWayInterFrameDelayVariationPmMetric : oneWayInterFrameDelayVariationPmMetric
SlsCosNameEntry -- "0..*" OneWayMeanFrameDelayPmMetric : oneWayMeanFrameDelayPmMetric
SlsCosNameEntry -- "0..*" OneWayFrameLossRatioPmMetric : oneWayFrameLossRatioPmMetric
SlsCosNameEntry -- "0..*" OneWayMeanFrameDelayRangePmMetric : oneWayMeanFrameDelayRangePmMetric
SlsCosNameEntry -- "0..*" OneWayAvailabilityPmMetric : oneWayAvailabilityPmMetric
SlsCosNameEntry -- "0..*" OneWayHighLossIntervalPmMetric : oneWayHighLossIntervalPmMetric
SlsCosNameEntry -- "0..*" OneWayConsecutiveHighLossIntervalsPmMetric : oneWayConsecutiveHighLossIntervalsPmMetric
SlsCosNameEntry -- "0..*" OneWayCompositePmMetric : oneWayCompositePmMetric
SlsCosNameEntry -- "0..*" OneWayGroupAvailabilityPmMetric : oneWayGroupAvailabilityPmMetric
DscpCosIdPac -- IpVersion : ipVersion
BwpFlow -- ColorMode : colorMode
OneWayCompositePmMetric -- "0..*" OrderedPair : orderedPairs
OneWayCompositePmMetric -- Time : oneWayFdThreshold
OneWayCompositePmMetric -- Time : oneWayIfdvThreshold
CosNameToPcpPac -- PcpOrDiscard : pcpValue
OneWayAvailabilityPmMetric -- "0..*" OrderedPair : orderedPairs
VlanIdListOrUntag -- "0..*" VlanId : vlanIdList
OneWayMeanFrameDelayRangePmMetric -- "0..*" OrderedPair : orderedPairs
OneWayMeanFrameDelayRangePmMetric -- Time : oneWayFdrObjective

@enduml