@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class Memory {
    buildingBlockIdentifier: String[1]
    memoryAmount: MemoryAmount[1]
}

MefServiceConfiguration <|-- Memory
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml