@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ServiceValue {
    id: String
    href: String
    place: RelatedPlaceRefOrValue
    serviceOffering: ServiceOfferingRef
    serviceRelationship: ServiceRelationship
    << ...attributes are skipped ...>>
}

class MefServiceConfiguration {
    @type: String <<discriminator>>
}

class Processor {
    buildingBlockIdentifier: String[1]
    processorManufacturerIdentifier: ProcessorManufacturerIdentifier[1]
    manufacturerModelIdentifier: ManufactureModelIdentifier[1]
    processorArchitecture: ProcessArchitecture[1]
    clockSpeedRange: ClockSpeedRange[1]
    numnberOfCores: NumberOrUnspecified[1]
    numberOfThreads: NumberOrUnspecified[1]
    level1Cache: CacheSizeOrUnspecified[1]
    level2Cache: CacheSizeOrUnspecified[1]
    instructionsPerClockCycle: InstructionPerClockCycleOrUnspecified[1]
    quantity: Integer[1]
}

enum ProcessorArchitecture {
    X86
    ARM
    GRP
    OTHER
    UNSPECIFIED
}

MefServiceConfiguration <|-- Processor
ServiceValue "1" *--> "0..1" MefServiceConfiguration: serviceConfiguration

@enduml