@startuml performanceMonitoringAsyncSeq

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S

B -> S: POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
...
note over B
    Create the Envelope part for POST request
end note


B -> B: PerformanceJobCreate pjc = new PerformanceJobCreate();
loop for each attribute
    B -> B: pjc.setAttributes();
end

note over B
    Create a technology-specific payload
    (e.g. BFD Configuration)
end note

B -> B: BfdConfiguration bfdc = new BfdConfiguration();
loop for each attribute
    B -> B: bfdc.setAttributes();
end

note over B
    Associate the payload (BFD Configuration) 
    with the envelope
end note

B -> B: pjc.servicePayloadSpecificAttributes(bfdc);


B -> S: POST {{baseUrl}}/performanceJob (PerformanceJob_Create)
S -> S: basic validation

alt succesful inquiry
  S --> B: 201 PerformanceJob with {{id}}, `acknowledged` state 
  S -> B: {{callbackUrl}}/listener/performanceJobCreateEvent ({{id}})
  B --> S: 204 confirmation

  ...

  group loop [until Performance Job in terminal state]
      S -> B: {{callbackUrl}}/listener/performanceJobStateChangeEvent ({{id}})
      B --> S: 204 confirmation
      B -> S:   GET {{baseUrl}}/performanceJob/{{id}}

      note over S
        Create PerformanceJob for Response
      end note

      S -> S: PerformanceJob perfjob = new PerformanceJob();
      loop for each attribute
        S -> S: perfjob.setAttributes()
      end
    note over S
        Create technology-specific payload results
    end note

    S -> S: IpPerformanceMonitoringReport ippmr = new IpPerformanceMonitoringReport();
    loop for each attribute
        S -> S: ippmr.setAttributes()
    end

    note over S
        Associate the payload (IP Performance Monitoring Report) 
        with the PerformanceJob
    end note

    S -> S: perfjob.setServicePayloadSpecificAttributes(ippmr);


      return 200 PerformanceJob in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end 

...

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S --> B : 204 confirmation

@enduml