@startuml

class Ipvc {
    "...attributes are not shown"
}

class IpvcEndPoint {
    "...attributes are not shown"
}


class IpEnni {
        "...attributes are not shown"
}

class IpEnniCommon {
    "...attributes are not shown"
}

class IpEnniLink {
    "...attributes are not shown"
}


Ipvc "1" *--> "1..*" IpvcEndPoint: IP_ENNI_ENDPOINT_OF_IPVC
IpvcEndPoint "1" o--> "1" IpEnni: CONNECTS_TO_IP_ENNI
IpEnniLink "0..*" o--> "1" IpEnni: CARRIED_OVER_ENNI_LINK

IpEnniCommon <|-- IpEnni: HAS_COMMON_ATTRIBUTES

@enduml