@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class IpSls << (D, Gray) >> {
    startTime: DateTime [1]
    periodOfTime: Duration [1]
    oneWayMeanPacketDelay: OneWayMeanPacketDelay [0..*]
    oneWayInterPacketDelayVariation:OneWayInterPacketDelayVariation [0..*]
    oneWayPacketDelayPercentile: OneWayPacketPercentile [0..*]
    oneWayPacketDelayRange: OneWayPacketDelayRange [0..*]
    oneWayPacketLossRatio: OneWayPacketLossRatio [0..*]
    serviceUptime: ServiceUpTime [0..*]
    meanTimeToRepair: MeanTimeToRepair [0..*]
    locationList: Location [1..*]
    }

class OneWayMeanPacketDelayPercentile << (D, Gray) >> {
    cosName: String [1]
    slsRpPairs: SlsRpPair [1..*]
    packetDelayPercentile: Percentage [1]
    packetDelayObjective: Real [1]
}

class OneWayMeanPacketDelay << (D, Gray) >> {
    cosName: String [1]
    slsRpPairs: SlsRpPair [1..*]
    packetArrivalTimeDifference: Real [1]
    interPacketDelayVariationPercentile: Percentage [1]
    interPacketDelayVariationObjective: Real [1]
}

class OneWayMeanPacketDelayVariation << (D, Gray) >> {
    cosName: String [1]
    slsRpPairs: SlsRpPair [1..*]
    meanPacketDelayObjective: Real [1]
}

class OneWayMeanPacketDelayRange << (D, Gray) >> {
    cosName: String [1]
    slsRpPairs: SlsRpPair [1..*]
    packetDelayRangeObjective: Real [1]
    packetDelayRangePercentile: Percentage [1]
}

class OneWayPacketLossRatio << (D, Gray) >> {
    cosName: String [1]
    slsRpPairs: SlsRpPair [1..*]
    packetLossRatioObjective: Percentile [1]
}

class ServiceUpTime << (D, Gray) >> {
    serviceUpTime: Percentile [1]
}

class MeanTimeToRepair<< (D, Gray) >> {
    name: String [1]
    mttrObjective: Duration [1]
}

class SlsRpPair<< (D, Gray) >> {
    toSlsReferencePoint: SlsReferencePoint [1]
    fromSlsReferencePoint: SlsReferencePoint [1]
}

class Location << (D, Gray) >> {

}

abstract class SlsReferencePoint << (D, Gray) >> {

}

class IpvcEndPoint << (D, Gray) >> {

}

IpSls "1" *--> "1..*" OneWayMeanPacketDelayPercentile
IpSls "1" *--> "1..*" OneWayMeanPacketDelay
IpSls "1" *--> "1..*" OneWayMeanPacketDelayVariation
IpSls "1" *--> "1..*" OneWayMeanPacketDelayRange
IpSls "1" *--> "1..*" OneWayPacketLossRatio
IpSls "1" *--> "1..*" ServiceUpTime
IpSls "1" *--> "1..*" MeanTimeToRepair

OneWayMeanPacketDelayPercentile "1" *--> "1..*" SlsRpPair
OneWayMeanPacketDelay "1" *--> "1..*" SlsRpPair
OneWayMeanPacketDelayVariation "1" *--> "1..*" SlsRpPair
OneWayMeanPacketDelayRange "1" *--> "1..*" SlsRpPair
OneWayPacketLossRatio "1" *--> "1..*" SlsRpPair

SlsRpPair "*" --> "1" SlsReferencePoint
SlsRpPair "*" --> "1" SlsReferencePoint

IpvcEndPoint --|> SlsReferencePoint
Location --|> SlsReferencePoint

@enduml