@startuml

hide footbox

participant "Buyer/Client" as B
participant "Seller/Server" as S
note right of B: Buyer/Client subscribes to ServiceOrderNotification with callbackUrl and baseUrl.
B -> S : POST {{baseUrl}}/hub with {{callbackUrl}} details
S --> B: 201 confirmation with {{id}}
note right of B : Buyer/Client builds a ServiceOrder with ServiceOrderItem(s) and IpUni,\nIpvcEndPoint, Ipvc.
B -> B : createIpServiceOrder(IpUni,IpvcEndPoint,Ipvc)

group createServiceOrder
    B -> B: ServiceOrderCreate()

    group createIpUni
    B -> B: createIpUni()
    B -> B: createServiceOrderItem()
    B -> B: addIpUniToServiceOrderItem()
    B -> B: addServiceOrderItemToServiceOrderCreate()
    end group

    group createIpvcEndPoint
    B -> B: createIpvcEndPoint()
    B -> B: createServiceOrderItem()
    B -> B: addIpvcEndPointToServiceOrderItem()
    B -> B: addServiceOrderItemToServiceOrderCreate()
    end group

    group createIpvc
    B -> B: createCarrierEthernetOvc()
    B -> B: createServiceOrderItem()
    B -> B: addIpvcToServiceOrderItem()
    B -> B: addServiceOrderItemToServiceOrderCreate()
    end group
end group

note right of B : Buyer/Client sends the ServiceOrderCreate to the Seller/Server
B -> S : POST {{baseUrl}}/serviceOrder (ServiceOrder_Create)
S -> S : basic validation

alt succesful inquiry
  S --> B : 201 ServiceOrder with {{id}}, `acknowledged` state 

  ...
note left of S : Seller/Server sends asynchronous notification to the Buyer/Client\nwith the ServiceOrderStateChangeEvent
  group loop [until Service Order in terminal state]
      S -> B: {{callbackUrl}}/listener/serviceOrderStateChangeEvent ({{id}})
      B --> S : 204 confirmation
      B -> S :   GET {{baseUrl}}/serviceOrder/{{id}}
      return 200 ServiceOrder in current state
  end

else validation or internal problem
  S --> B : 4xx or 5xx error response
end 

B -> S : DELETE {{baseUrl}}/hub/{{id}} 
S -->  B : 204 confirmation

@enduml