@startuml alarmUsecases

left to right direction

actor "Buyer/Client" as B
actor "Seller/Server" as S

rectangle {
Usecase UC1 as "1. Retrieve Alarm List"
Usecase UC2 as "2. Retrieve Alarm by Alarm Identifier"
Usecase UC3 as "3. Subscribe for Alarm Notifications"
Usecase UC4 as "4. Create Alarm"
Usecase UC5 as "4a. Stateful TCA Alarm"
Usecase UC6 as "4b. Stateless TCA Alarm"
Usecase UC7 as "5. Unsubscribe for Alarm Notification"
}

UC4 <-- S
UC5 <-- S
UC6 <-- S
B --> UC2
B --> UC3
B --> UC1
B --> UC7
@enduml