@startuml statelessTCAAlarmModel
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Alarm {

    externalAlarmId: string
    isRootCause*: boolean
    probableCause: ProbableCause
    sourceSystemId: string
    specificProblem: string
}
Alarm_Common <|-- Alarm

Alarm *-->"*" AlarmedObjectRef : alarmedObject
Alarm *-->"*" Comment : comment
Alarm *--> AlarmRef : parentAlarm
Alarm *--> AlarmSpecificAttributes : alarmSpecificAttributes

class AlarmRef {

}

class AlarmSpecificAttributes {

    @type*: string
}


class Alarm_Common {

    id*: string
    href: uri
    alarmChangedTime: date-time
    alarmClearedTime: date-time
    alarmDetails*: string
    alarmedObjectType: string
    alarmRaisedTime*: date-time
    alarmReportingTime*: date-time
    alarmType*: AlarmType
    perceivedSeverity*: PerceivedSeverity
    plannedOutageIndicator: PlannedOutageIndicator
    reportingSystemId: string
    serviceAffecting*: boolean
    state*: AlarmState
}

Alarm_Common *-->"*" ServiceRef : affectedService
Alarm_Common *-->"*" AlarmRef : correlatedAlarm

class AlarmedObjectRef {
}

class Comment {
}

class TcaStatelessAlarm {

    performanceMetricName: string
    performanceMetricValue: number
    tcaPerformanceThresholdValue: number
    dampingFactor: number
    numberOfPmMetricCalculationIntervals: number
}
AlarmSpecificAttributes <|-- TcaStatelessAlarm



@enduml
