@startuml useCase52Model

class Alarm {

    externalAlarmId: string
    isRootCause*: boolean
    probableCause: ProbableCause
    sourceSystemId: string
    specificProblem: string
}
Alarm_Common <|-- Alarm

Alarm *-->"*" AlarmedObjectRef : alarmedObject
Alarm *-->"*" Comment : comment
Alarm *--> AlarmRef : parentAlarm
Alarm *--> AlarmSpecificAttributes : alarmSpecificAttributes


class Alarm_Common {

    id*: string
    href: uri
    alarmChangedTime: date-time
    alarmClearedTime: date-time
    alarmDetails*: string
    alarmedObjectType: string
    alarmRaisedTime*: date-time
    alarmReportingTime*: date-time
    alarmType*: AlarmType
    perceivedSeverity*: PerceivedSeverity
    plannedOutageIndicator: PlannedOutageIndicator
    reportingSystemId: string
    serviceAffecting*: boolean
    state*: AlarmState
}

Alarm_Common *-->"*" ServiceRef : affectedService
Alarm_Common *-->"*" AlarmRef : correlatedAlarm



class AlarmedObjectRef {

    id*: string
    href: string
    @referredType*: string
}



class AlarmSpecificAttributes {

    @type*: string
}



class AlarmRef {

    id*: string
    href: string
}



enum AlarmType {

    communicationsAlarm
    processingErrorAlarm
    environmentalAlarm
    qualityOfServiceAlarm
    equipmentAlarm
    integrityViolation
    operationalViolation
    physicalViolation
    securityService
    mechanismViolation
    timeDomainViolation
}
class Comment {

    description: string
    systemIdentifier: string
    time: date-time
    userIdentifier: string
}



enum PerceivedSeverity {

    cleared
    critical
    indeterminate
    major
    minor
    warning
}
class ServiceRef {

    href: string
    id*: string
}


@enduml